### ISSUE TITLE
beta.5 使用时发现的几个问题：

### ISSUE THREAD

**Issue by cloth32** [edp963/davinci#1017]
**view部分：**

1. 标签文本写不进内容
2. 堆叠柱状图无法显示标签，一旦勾选就会页面丢失，且柱形颜色更改后无效
3. 折线图显示标签时，设置数值显示格式无效（比如：不能添加千位符和单位）
4. 能否在选择控制器后，默认显示比如近30天的数据展示
5. 控制器配置在选择日期后，勾选多选+默认值就会整个页面垮掉

**Schedule部分：**

1. 定时任务发送不能发图片，且在文件类型选择excel以后再次打开显示是“image”
2. 邮件发送时无法修改邮件内容

感谢开源！

**Comment by lanceleedev** [comment]
标签文本写入是回车触发，可以写入的

**Comment by cloth32** [comment]
> 标签文本写入是回车触发，可以写入的

OK，刚刚试了，回车之后可以使用。THX
