### ISSUE TITLE
branch 0.3 web build fail

### ISSUE THREAD

**Issue by hf200012** [edp963/davinci#1018]
ERROR in ./app/containers/Dashboard/components/DashboardItem.tsx
Module not found: Error: Can't resolve '../../../components/DownloadCsv' in '/soft/davinci/webapp/app/containers/Dashboard/components'
 @ ./app/containers/Dashboard/components/DashboardItem.tsx 78:0-58 885:81-92 929:31-42
 @ ./share/containers/Dashboard/index.tsx
 @ ./share/routes.ts
 @ ./share/app.tsx
 @ multi ./node_modules/react-app-polyfill/ie11.js ./share/app.tsx

ERROR in ./app/containers/Widget/components/Workbench/OperatingPanel.tsx
Module not found: Error: Can't resolve '../ComputedConfigForm' in '/soft/davinci/webapp/app/containers/Widget/components/Workbench'
 @ ./app/containers/Widget/components/Workbench/OperatingPanel.tsx 81:0-55 2430:29-47
 @ ./app/containers/Widget/components/Workbench/index.tsx
 @ ./app/routes.ts
 @ ./app/app.tsx
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.tsx

ERROR in ./app/containers/Dashboard/components/DashboardItem.tsx
Module not found: Error: Can't resolve './DashboardItemMask' in '/soft/davinci/webapp/app/containers/Dashboard/components'
 @ ./app/containers/Dashboard/components/DashboardItem.tsx 76:0-52 1061:38-55
 @ ./share/containers/Dashboard/index.tsx
 @ ./share/routes.ts
 @ ./share/app.tsx
 @ multi ./node_modules/react-app-polyfill/ie11.js ./share/app.tsx

ERROR in ./app/containers/Widget/components/Workbench/OperatingPanel.tsx
Module not found: Error: Can't resolve './Dropbox' in '/soft/davinci/webapp/app/containers/Widget/components/Workbench'
 @ ./app/containers/Widget/components/Workbench/OperatingPanel.tsx 74:0-32 1987:35-42
 @ ./app/containers/Widget/components/Workbench/index.tsx
 @ ./app/routes.ts
 @ ./app/app.tsx
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.tsx

ERROR in ./app/containers/Widget/components/Workbench/index.tsx
Module not found: Error: Can't resolve 'containers/Dashboard/components/DashboardItemMask' in '/soft/davinci/webapp/app/containers/Widget/components/Workbench'
 @ ./app/containers/Widget/components/Workbench/index.tsx 77:0-82 685:37-54 686:35-52
 @ ./app/routes.ts
 @ ./app/app.tsx
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.tsx
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
Child html-webpack-plugin for "share.html":
     1 asset
    Entrypoint undefined = share.html

**Comment by AndyFong** [comment]
Please provide your build environment information.

**Comment by hf200012** [comment]
ubuntu 16.04
node  v10.15.3
npm 6.4.1
yarn 1.16.0

**Comment by AndyFong** [comment]
It is caused by the case sensitivity of the file name in linux OS system, we will fix it in time.

**Comment by AndyFong** [comment]
fixed: #1025

**Comment by AndyFong** [comment]
#1035 add webpack case sensitive plugin to check this problem when build on no-case-sensitive file name OS.
