### ISSUE TITLE
Can we support base charts Line + Bar in Davinci?

### ISSUE THREAD

**Issue by lanceleedev** [edp963/davinci#1027]
Here are the renderings of other products：
![企业微信截图_15609140801825](https://user-images.githubusercontent.com/20727676/59734533-5f141200-9284-11e9-9bcc-fd3f969d0d33.png)
![clipboard](https://user-images.githubusercontent.com/20727676/59734534-60453f00-9284-11e9-878a-0edb41fd8d99.png)
it looks pretty, right?

**Comment by AndyFong** [comment]
You can use double Y chart.  
![image](https://user-images.githubusercontent.com/6837655/64579444-8bd45300-d3b5-11e9-9166-c942b880982f.png)
