### ISSUE TITLE
executeParam.filters could not append KeywordPrefix， thus querysql is Unrecognized token

### ISSUE THREAD

**Issue by lanceleedev** [edp963/davinci#1028]
filter param has already assembled when passing values to the background
![1](https://user-images.githubusercontent.com/20727676/59741419-862b0d80-929d-11e9-8a71-f98132d22f3a.png)
![2](https://user-images.githubusercontent.com/20727676/59741420-862b0d80-929d-11e9-9ad9-a69f94f7da7c.png)
filter not append KeywordPrefix when SQL assembled, thus SQL is error.
![3](https://user-images.githubusercontent.com/20727676/59741421-86c3a400-929d-11e9-8f20-8a843352f56f.png)

**Comment by lanceleedev** [comment]
also, config in view with alias, found the same wrong info.
![4](https://user-images.githubusercontent.com/20727676/59748902-a4e5d000-92ae-11e9-80a4-d06d0c5d5d18.png)
![5](https://user-images.githubusercontent.com/20727676/59748903-a57e6680-92ae-11e9-8b2d-61cbe94bfabe.png)
![6](https://user-images.githubusercontent.com/20727676/59748905-a57e6680-92ae-11e9-9e41-8d770643bf6f.png)

### Error info
> StatementCallback; uncategorized SQLException for SQL [SELECT `时间`,`机构id` FROM (SELECT txTime AS `时间`, institutionID as `机构id` FROM QuickPaymentBinding) T WHERE <b>机构id in ('000000','000001') </b> GROUP BY `时间`,`机构id` ]; SQL state [null]; error code [62]; ClickHouse exception, code: 62, host: 172.31.1.231, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 124: 机构id in ('000000','000001') GROUP BY `时间`,`机构id` FORMAT TabSeparatedWithNamesAndTypes;. Unrecognized token (version 19.8.3.8) ; nested exception is ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 62, host: 172.31.1.231, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 124: 机构id in ('000000','000001') GROUP BY `时间`,`机构id` FORMAT TabSeparatedWithNamesAndTypes;. Unrecognized token (version 19.8.3.8)

**Comment by AndyFong** [comment]
@shanmengm

**Comment by AndyFong** [comment]
It is caused by the dynamic filters assembly passed by the front end, and with no specific `Source` process.  
We will refactor the data structure of the filters in this case and let the back end adapt the sql based on the specific type of the `Source` that corresponding to the `View` used by the `Widget`.

**Comment by lanceleedev** [comment]
Davinci will be online tomorrow for trial, and there are bugs, to be honest, i am a little nervous. So when can we solve this problem...

**Comment by lanceleedev** [comment]
Our data source is clickhouse,  it is fixed ,  so i think we can fix this temporarily by writing the prefix in the source code. After Davinci is repaired, we will remove it. Thus, can you tell me where to add it, please

**Comment by lanceleedev** [comment]
This bug has been temporarily fixed. Our data source is clickhouse，I directly use hardcoded, if data source is multi, you can obtain widget source, determine database, dynamic appending by DataTypeEnum config
![企业微信截图_15635040959249](https://user-images.githubusercontent.com/20727676/61505559-d4a10880-aa11-11e9-87e9-0dec7ac76663.png)

**Comment by AndyFong** [comment]
@Mrclg @ruanhan
