### ISSUE TITLE
davinci 0.3 Email registration failed

### ISSUE THREAD

**Issue by tutengfei123** [edp963/davinci#1043]
When I click to activate the user, the website cannot be accessed. and then landing the user failed.
internal service error.

**Comment by AndyFong** [comment]
Please post the UI and command line error screenshot.

**Comment by 600ly** [comment]
![image](https://user-images.githubusercontent.com/48941084/63180339-a8b08b80-c080-11e9-8a74-ab1d20ce710e.png)
