### ISSUE TITLE
Initialize database without data（初始化数据库无数据）

### ISSUE THREAD

**Issue by Simbleming** [edp963/davinci#1074]
I use davinci. SQL to initialize the database. I can only create tables without data to import. Do you have test data? Because I created JS errors in Source and got missing data.（我使用davinci.sql初始化数据库，只能创建表，并没有数据去导入，请问有测试数据吗？因为我自己在Source中创建时会有JS错误，获取的数据有缺失）

**Comment by AndyFong** [comment]
Does error occur when add `Source`? Please provide detailed information.

**Comment by Simbleming** [comment]
> Does error occur when add `Source`? Please provide detailed information.
Thank you for your attention. I use eclipse to start the project and configure it in application.
Configure the following information in application.yml in src/main/resources
`datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    time-between-eviction-runs-millis: 30000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filters: stat
    break-after-acquire-failure: true
    connection-error-retry-attempts: 3
    validation-query: SELECT 1
    url: jdbc:mysql://localhost:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    min-idle: 1
    max-wait: 60000
    max-active: 10`

**Comment by AndyFong** [comment]
Please make sure that the mysql database can be connected successfully.

**Comment by Simbleming** [comment]
> Please make sure that the mysql database can be connected successfully.

MySQL is successfully connected. Did you create a new table and import data when you initialized the database? I see that the davinci. sql file has only statements that create tables.

**Comment by AndyFong** [comment]
All data in `Davinci` is user generated so the table in database does not have any data from the start of system deployment.

**Comment by Simbleming** [comment]
> Please make sure that the mysql database can be connected successfully.

Which version do you use? I can't use 0.3.0-bate. 5 or 0.3.0-bate. 6 with

**Comment by Simbleming** [comment]
> All data in `Davinci` is user generated so the table in database does not have any data from the start of system deployment.

Okay, I can successfully build tables here, and then I create a new organization and prepare to add a new Source, but this page reported an error in the Google console. We queried the data passed in the Java code.It's like
 ```
payload = [Source {
		id = 19, name = 'test', description = '', type = 'jdbc', projectId = 15, 
		config = '{"parameters":"","password":"123123","url":"jdbc:mysql://localhost:3306/davinci0.3","username":"root"}'
	}]
```
But only the JS receiving data of the front desk error report
```
payload = [Source {
		id = 19, name = 'test', description = '', type = 'jdbc', projectId = 15	}]
```

**Comment by AndyFong** [comment]
Cause the `Source` config is confidential info, including user name and password, so when fetch `Source` list data, the config field is omitted.

**Comment by Simbleming** [comment]
> Cause the `Source` config is confidential info, including user name and password, so when fetch `Source` list data, the config field is omitted.

Well, thank you. I noticed that the loss was due to a mistake in the console. When I checked, I said online that it was due to illegal characters. The questions are as follows
```
vendor.b3714924781d0b607281.chunk.js:1 
uncaught at jo SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at http://localhost:8085/app.90fcb7b6f577eb172b53.chunk.js:1:115386
    at Array.map (<anonymous>)
    at mo (http://localhost:8085/app.90fcb7b6f577eb172b53.chunk.js:1:115331)
    at http://localhost:8085/vendor.b3714924781d0b607281.chunk.js:1:4043001
    at Array.forEach (<anonymous>)
    at http://localhost:8085/vendor.b3714924781d0b607281.chunk.js:1:4042967
    at t.kt [as withMutations] (http://localhost:8085/vendor.b3714924781d0b607281.chunk.js:1:1154726)
    at http://localhost:8085/vendor.b3714924781d0b607281.chunk.js:1:4042939
    at v (http://localhost:8085/vendor.b3714924781d0b607281.chunk.js:1:3149872)
```

**Comment by AndyFong** [comment]
You can debug by yourself to find where the problem is.

**Comment by Simbleming** [comment]
> You can debug by yourself to find where the problem is.

Okay, thank you again for your help.
