### ISSUE TITLE
PostgreSQL datasource not supported in v0.3.0-beta.6 ?

### ISSUE THREAD

**Issue by lxneng** [edp963/davinci#1077]
I've successfully deploy datavinci via [edp963/davinci-docker](https://github.com/edp963/davinci-docker). but got a `Not supported data type: jdbcUrl=jdbc:postgresql://****************` in add new datasource page.

**Comment by AndyFong** [comment]
https://edp963.github.io/davinci/deployment.html#3-%E6%95%B0%E6%8D%AE%E6%BA%90%E9%85%8D%E7%BD%AE
