### ISSUE TITLE
I built davinci in remote server, and it's always failed connect when I browse it 

### ISSUE THREAD

**Issue by kingking0803** [edp963/davinci#1079]
when I browse davinci with remote server's IP(47.99.170.150), such as http://47.99.170.150:8080, it will show "curl: (7) Failed connect to 47.99.170.150:8080; 拒绝连接";
I changed the server.address=47.99.170.150, and there was a error when I start the server
<img width="564" alt="屏幕快照 2019-07-04 17 53 52" src="https://user-images.githubusercontent.com/22694253/60657910-b6b99c80-9e84-11e9-889b-0474568175a8.png">

**Comment by tangbinbinyes** [comment]
我也是这样，我想远程连接，可是连接不上。到时候把davinci部署好了总不能让别人都来机房看吧....请问你解决这个问题了吗？

**Comment by kingking0803** [comment]
最近没有在弄这个

**Comment by mnikogit** [comment]
set server.address=0.0.0.0
