### ISSUE TITLE
npm install error:"Unexpected end of JSON input while parsing near '...0460eebe08eb","tarbal'"

### ISSUE THREAD

**Issue by AngelaFighting** [edp963/davinci#1086]
I clone the project into my desktop。 Enter the webapp directory, and try to run the command `npm install`, get the following error information:

![image](https://user-images.githubusercontent.com/24426189/60799693-33f75100-a1a6-11e9-9e0b-5aff8fcadc37.png)

Then I use the command `cnpm install` to download the dependencies, it works. But the typescript verison is 3.5.2, and the webstorm IDE will warn the problem TS2322.

In order to fix the TS2322 problem, I reinstall the typescript version as 3.2.2, and this problem is fixed.

My issues are: 
1. Can I use `npm install` not `cnpm install`? 
2. Maybe you should update the typescript version to fix the TS2322 error?

**Comment by AndyFong** [comment]
1. use `npm install`
2. Typescript has upgraded to `3.5.2` in branch `dev-0.3`
