### ISSUE TITLE
有没有全一点操作手册，不知道怎么弄

### ISSUE THREAD

**Issue by ylh23y** [edp963/davinci#1101]

**Comment by ylh23y** [comment]
请问来下来的代码是否可以运行

**Comment by ylh23y** [comment]
邮箱配置好后正常

**Comment by ylh23y** [comment]
![搜狗截图20190717180448](https://user-images.githubusercontent.com/13464610/61367036-69462200-a8bd-11e9-8b17-33da85599e98.png)

**Comment by ylh23y** [comment]
有没有全一点的操作手册

**Comment by scottsut** [comment]
https://edp963.github.io/davinci/

**Comment by phineasliu** [comment]
这个文档很恶心的。。看这情况不是给小白开源的。。没有点开发经验是白搭的。
