### ISSUE TITLE
JDK问题 | Problem With Jdk

### ISSUE THREAD

**Issue by ferried** [edp963/davinci#1103]
ListBuffer为sun.util包中的class但OpenJdk中没有,现今状况下是否应该避免使用Oracle JDK开发转为OpenJdk?
---------------------------------------------------------------------------------------------------
Q1:ListBuffer is a class in the com.sun.util's package and that defined in OracleJdk,But my env was OpenJdk not OracleJdk,So how to solve the problem?

Q2:Why not use the OpenJdk?

**Comment by ylh23y** [comment]
![搜狗截图20190717155158](https://user-images.githubusercontent.com/13464610/61357615-3135e380-a8ab-11e9-8dcb-72e67147a16d.png)

**Comment by ylh23y** [comment]
davinci-server_3.01的pom文件加一个依赖

**Comment by ferried** [comment]
![image](https://user-images.githubusercontent.com/26159886/61357940-d5b82580-a8ab-11e9-84f6-27720385aa54.png)

I checked my JDK's tool.jar that has the class named ListBuffer

**Comment by ferried** [comment]
> ![image](https://user-images.githubusercontent.com/26159886/61357940-d5b82580-a8ab-11e9-84f6-27720385aa54.png)
> 
> I checked my JDK's tool.jar that has the class named ListBuffer
