### ISSUE TITLE
上传csv文件的时候报错：Unknown Type: 1

### ISSUE THREAD

**Issue by ylh23y** [edp963/davinci#1107]
Unknown Type: 1
![搜狗截图20190717182803](https://user-images.githubusercontent.com/13464610/61368609-d0b1a100-a8c0-11e9-8f79-ea4476f9fe5c.png)

**Comment by AndyFong** [comment]
https://edp963.github.io/davinci/source_guide.html#2-%E4%B8%8A%E4%BC%A0-csv-%E6%95%B0%E6%8D%AE%E6%96%87%E4%BB%B6

**Comment by eric20141111** [comment]
> https://edp963.github.io/davinci/source_guide.html#2-%E4%B8%8A%E4%BC%A0-csv-%E6%95%B0%E6%8D%AE%E6%96%87%E4%BB%B6

404了，也遇到这个问题了。。。
