### ISSUE TITLE
need to update version of fastjson

### ISSUE THREAD

**Issue by bbdrlancy** [edp963/davinci#1118]
project: davinci-Docker 
issue: 
There is a Code Execution Vulnerability in version < 1.2.51 of fastjson. 
When a user submits a well-constructed malicious serialized data to the server, fastjson has a vulnerability in deserialization, which can lead to remote arbitrary code execution.
 Aliyun Emergency Response Center reminds fastjson users to take security measures to prevent vulnerability attacks as soon as possible. 
Suggestions for repair Upgrade fastjson components according to official vulnerability announcements 
https://github.com/alibaba/fastjson/wiki/update_faq_20190722

**Comment by shanmengm** [comment]
Thanks for you suggestion, we will upgrade the version of fastjson in the source code and next release.
