### ISSUE TITLE
Line chart does not support more dimensional display

### ISSUE THREAD

**Issue by ZengTianShengZ** [edp963/davinci#1128]
more dimensional

![image](https://user-images.githubusercontent.com/15622519/61841008-cba6b000-aec5-11e9-8a31-54134ca28f0e.png)

normal display like SENSOR

![image](https://user-images.githubusercontent.com/15622519/61841062-fb55b800-aec5-11e9-9400-a48f0ba12fe2.png)

**Comment by AndyFong** [comment]
use chart-driven mode to create line chart
