### ISSUE TITLE
The software can't start without any error log

### ISSUE THREAD

**Issue by EmperorisMe** [edp963/davinci#1139]
The software can't start without any error log, any big god can help? Thanks very much @AndyFong @ruanhan @scottsut @yuhouchuhe1 @whtblktone 

Configure and log file as attach:
[davinci.2019-07-31.log.txt](https://github.com/edp963/davinci/files/3455264/davinci.2019-07-31.log.txt)
[application.yml.txt](https://github.com/edp963/davinci/files/3455265/application.yml.txt)

**Comment by X010** [comment]
1、application log level is INFO，please change to debug
2、check config application.yaml
