### ISSUE TITLE
Display designer suggestion

### ISSUE THREAD

**Issue by tangxg** [edp963/davinci#1155]
Front end suggestions:
In the display design interface, when selecting a specific layer on the right side of the layer, it is recommended to select the entire line. You can push the code if you want.
前端建议：
在display 设计界面，右边“图层”选择具体图层时建议选中整行。如需要可以推送代码。

**Comment by AndyFong** [comment]
resolved in [v0.3.0-beta.9](https://github.com/edp963/davinci/releases/tag/v0.3.0-beta.9)
