### ISSUE TITLE
Use of map and query variables

### ISSUE THREAD

**Issue by haibucuoba** [edp963/davinci#1178]
How to use map display, is there an example?
The query variable is used in the form of $variable$. Is it necessary to have a default value, otherwise the execution will report an error.

**Comment by haibucuoba** [comment]
<img width="364" alt="Snipaste_2019-08-26_16-13-24" src="https://user-images.githubusercontent.com/32813064/63675970-8f47d600-c81c-11e9-9ac3-ac1a6f727c41.png">
<img width="964" alt="Snipaste_2019-08-26_16-13-57" src="https://user-images.githubusercontent.com/32813064/63675971-8fe06c80-c81c-11e9-8350-31f06a28466a.png">
There is no data displayed on the map.

**Comment by AndyFong** [comment]
You need to set the proper `Visual Type` of the `View Model`.

https://edp963.github.io/davinci/widget_guide.html#3-%E7%89%B9%E6%AE%8A%E5%9B%BE%E8%A1%A8%E7%9A%84%E9%85%8D%E7%BD%AE

**Comment by AndyFong** [comment]
Is it necessary to have a default value of a `View` `Variable`?
---
It is up to your scenario.
