### ISSUE TITLE
Is there any version of the js source code that has not been compressed and confusing, easy to read? Thank you.

### ISSUE THREAD

**Issue by oaHeZgnoS** [edp963/davinci#1180]
Because I want to see the execution logic of js, but the source code is compressed and confusing, it is not conducive to reading and analysis, requesting to provide a js file that is not compressed and confused.

**Comment by scottsut** [comment]
Webapp folder is front-end codebase

**Comment by oaHeZgnoS** [comment]
Have found it, thx so much!
