### ISSUE TITLE
Druid can only see the sql of the primary data source

### ISSUE THREAD

**Issue by oaHeZgnoS** [edp963/davinci#1189]
Druid can only see the sql of the **primary data source**, can not see the sql of the **business data source**.
Is there any problem about my configs, or It was originally a bug?

**Comment by oaHeZgnoS** [comment]
Waiting for replying, thx a lot.

**Comment by oaHeZgnoS** [comment]
I guess, JdbcDataSource.java missing a attribute(filters).

**Comment by oaHeZgnoS** [comment]
Another tiny question，line 711 in edp.core.utils.SqlUtils should be 10000 rather than 1000.
`//每10000条commit一次`

**Comment by shanmengm** [comment]
Business datasource sql logs in the `logs/user/sql` directory, default log config in config/logback.xml

**Comment by oaHeZgnoS** [comment]
> 
> 
> Business datasource sql logs in the `logs/user/sql` directory, default log config in config/logback.xml

I want to see those business sql in druid, not in log file.

**Comment by shanmengm** [comment]
We can't open druid's monitoring of business sql based on security considerations, but if your business is a single datasource, you can modify the source code by yourself.

**Comment by oaHeZgnoS** [comment]
> 
> 
> We can't open druid's monitoring of business sql based on security considerations, but if your business is a single datasource, you can modify the source code by yourself.

Oh, I see it. Thanks a lot!
