### ISSUE TITLE
如何根据登录用户限制数据查询？

### ISSUE THREAD

**Issue by redfeng** [edp963/davinci#1191]
就是在查询sql中增加登录用户的变量

**Comment by AndyFong** [comment]
Different values of SQL query variables to different login users is under the terms of one specific `Project`.  
Let's say in a Davinci `Project`, the `owner` can create some `roles`, you can pull some `users` to its corresponding `role`. Then the `owner` create a `View`,  add authorization variables,  use them in sql, and distribute different values to all the `roles` in current `Project`.  
Last, when the user visit a `Dashboard` in this `Project`, Davinci will look up its `Role`, and assemble the sql in the `View` behind the `Widget` with the values of authorization variables that the `owner` set to this role.
