### ISSUE TITLE
When modifying a table or a full screen table, clicking on the table contents will error

### ISSUE THREAD

**Issue by justeene** [edp963/davinci#1195]
When modifying a table or a full screen table, clicking on the table contents will error ,and page is blank.
![image](https://user-images.githubusercontent.com/6252314/64157115-b0d23e80-ce68-11e9-8c50-0209350d0ec2.png)
![image](https://user-images.githubusercontent.com/6252314/64157156-c6dfff00-ce68-11e9-8a7e-923280fe8715.png)

**Comment by AndyFong** [comment]
This bug has fixed in branch dev-0.3
