### ISSUE TITLE
新功能讨论

### ISSUE THREAD

**Issue by lzy305** [edp963/davinci#1196]
可否增加以下功能点:
         1.  地图功能增加一个 “经纬度”
         2. 全局控制器配置 - 下拉菜单   可以直接从view读取数据.

**Comment by AndyFong** [comment]
1. 增加经纬度的展示跟现在有什么区别  
2. 现在下拉菜单项的数据来源已经肯定指定来源于 View 字段中的数据

**Comment by lzy305** [comment]
1.  地图描点 !  类似
![image](https://user-images.githubusercontent.com/38307479/64166450-b8e6aa00-ce79-11e9-9cd7-bbff7578ce73.png)

2.  全局控制器配置 - 下拉菜单 可以直接从view读取数据.  指的是可以从例外从例外一张配置表.
   比如 省份, 城市.  可以从维度表 dw_prov_city_info表取

**Comment by AndyFong** [comment]
1. 欢迎提供样例东莞市的经纬度 Demo 数据供我们开发测试。  
2. 这个之前内部做过讨论，结论是把对应的 View 范围缩小到当前 Dashboard 所使用的 View（这也是当前的方案），主要是出于级联过滤时页面和逻辑的复杂度的考虑。这块我们会继续迭代，看看怎么优化支持。

**Comment by lzy305** [comment]
讨论讨论
3.  Viz - 全局控制器配置
     控制器配置 所有类型都可以设置默认值 , 取值优先级: 控制器配置的默认值> View的默认值

4. 角色 权限变量值设置 
   4.1. 先在项目设置
       4.1.1 增加"设置"按钮，设置值
        4.1.2 增加一个"同步"按钮. 修改的时候,可以同步到相关涉及的模块(比如View)
   4.2. 再在View -> Auth,  优先取项目设置的默认值.
     若用户手动设置. 则保存手动设置的值

5. Viz - 联动关系配置
      支持多个字段

**Comment by AndyFong** [comment]
@RichardShan please describe the DAC customized module implemented in Davinci which relates to 4th mentioned above.

**Comment by ek912** [comment]
> 1. 地图描点 !  类似
>    ![image](https://user-images.githubusercontent.com/38307479/64166450-b8e6aa00-ce79-11e9-9cd7-bbff7578ce73.png)
> 2. 全局控制器配置 - 下拉菜单 可以直接从view读取数据.  指的是可以从例外从例外一张配置表.
>    比如 省份, 城市.  可以从维度表 dw_prov_city_info表取

希望下拉菜单从另一张表(维度表)中取数功能实现时，附带上级联功能，例如省份和城市。
