### ISSUE TITLE
漏斗图的百分比值, 应该是两个指标的比值,而不应该是指标的占比哦!!!

### ISSUE THREAD

**Issue by daxiongll** [edp963/davinci#1246]
如标题

**Comment by scottsut** [comment]
![65A1D3A5-C8E0-4C22-83BE-A61039BB4637](https://user-images.githubusercontent.com/4098913/65400986-e4651080-ddf7-11e9-8556-d335f35e0755.jpeg)
![E3E34D5B-C79D-4F11-B24B-49553FFA7FC5](https://user-images.githubusercontent.com/4098913/65400987-e4fda700-ddf7-11e9-8858-344ba5cef902.jpeg)

There are two situations, and we have all supported.

**Comment by daxiongll** [comment]
我的意思是, 你图里的百分比的数值, 不应该是占比哦, 我理解的漏斗图,主要展示的数据类型是数据的转化率.

**Comment by daxiongll** [comment]
![图片](https://user-images.githubusercontent.com/29703785/65411955-c4961280-de20-11e9-815c-1521d6af0796.png)

**Comment by daxiongll** [comment]
@AndyFong

**Comment by AndyFong** [comment]
We will look into this and make the proper adjustment.
