### ISSUE TITLE
How to add slider to bar chart?

### ISSUE THREAD

**Issue by justeene** [edp963/davinci#1251]
用户手册有例子
![image](https://user-images.githubusercontent.com/6252314/65589989-951c0d00-dfbc-11e9-80a8-67cd00d513c8.png)
但是我实际使用时设置了超出后缩放还是没有效果
![image](https://user-images.githubusercontent.com/6252314/65589940-7ddd1f80-dfbc-11e9-9725-e2c5fa362bf5.png)

**Comment by AndyFong** [comment]
This is Davinci version 0.2.

**Comment by justeene** [comment]
> This is Davinci version 0.2.

Doesn't this function exist on the 0.3 branch?

**Comment by scottsut** [comment]
Related to #1714
