### ISSUE TITLE
I need to create a new calculated field

### ISSUE THREAD

**Issue by zhere** [edp963/davinci#1252]
The new field can be calculated by the existing field, and the calculation formula includes addition, subtraction, multiplication and division.

**Comment by AndyFong** [comment]
Calculate fields feature support.

**Comment by fancyChuan** [comment]
how to use?  Can davinci support such calculation like 
`
select A
        , sum(A) / count(distinct B) as field1
        , sum(A)-sum(C) as fields 
from viewx group by A
`

**Comment by scottsut** [comment]
Related to #1735
