### ISSUE TITLE
drill -through

### ISSUE THREAD

**Issue by Suarez999** [edp963/davinci#1262]
hello,how to use drill -through
![1570762186(1)](https://user-images.githubusercontent.com/28488641/66620949-f545bc80-ec14-11e9-8081-adc454e001d9.jpg) 
why i cannot edit it?

**Comment by AndyFong** [comment]
Please post `View` model fields, it seems that the `View` only has one field, so it can not be drilled.

**Comment by Suarez999** [comment]
> Please post `View` model fields, it seems that the `View` only has one field, so it can not be drilled.

OK.Thank you.It works.And can i use this to drill data from another chart?

**Comment by Suarez999** [comment]
OK.Thank you.It works.And can i use this to drill data from another chart?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"andyfong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月12日(星期六) 下午3:35
收件人:&nbsp;"edp963/davinci"<davinci@noreply.github.com&gt;;
抄送:&nbsp;"‖B.【A.R】.S）"<xxin.5425@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [edp963/davinci] drill -through (#1262)




Please post View model fields, it seems that the View only has one field, so it can not be drilled.

**Comment by AndyFong** [comment]
We support drill operation in some charts, but not including like sankey, parallel and some others. You can try it by yourself to see the exact support.

**Comment by Suarez999** [comment]
OK.Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"andyfong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月12日(星期六) 下午5:54
收件人:&nbsp;"edp963/davinci"<davinci@noreply.github.com&gt;;
抄送:&nbsp;"‖B.【A.R】.S）"<xxin.5425@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [edp963/davinci] drill -through (#1262)




We support drill operation in some charts, but not including like sankey, parallel and some others. You can try it by yourself to see the exact support.
