### ISSUE TITLE
add datasource

### ISSUE THREAD

**Issue by wangnannan** [edp963/davinci#1266]
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder

**Comment by AndyFong** [comment]
https://edp963.github.io/davinci/deployment.html#3-%E6%95%B0%E6%8D%AE%E6%BA%90%E9%85%8D%E7%BD%AE

**Comment by wangnannan** [comment]
谢谢我降低了JDK版本,之前的是openJDK11 后来降低到8解决了
