### ISSUE TITLE
The widget filter is not valid in display

### ISSUE THREAD

**Issue by allentern** [edp963/davinci#1271]
Widget has filter, the filter is not valid in display, but is valid in Dashboard.
This bug has a relatively large impact on display, will occur a lot of rework,hope to be able to change, Thanks!

![微信截图_20191017135117](https://user-images.githubusercontent.com/776181/66981061-45c18c00-f0e5-11e9-936c-d1e1c11b9551.png)
![微信截图_20191017134859](https://user-images.githubusercontent.com/776181/66981072-4c500380-f0e5-11e9-91bf-548152f419d8.png)
![微信截图_20191017134833](https://user-images.githubusercontent.com/776181/66981076-4e19c700-f0e5-11e9-97b8-4072b36c3f87.png)

**Comment by ruanhan** [comment]
fix #1282
