### ISSUE TITLE
DisplayA's widgets cannot be copied to DisplayB

### ISSUE THREAD

**Issue by allentern** [edp963/davinci#1273]
DisplayA's widgets cannot be copied to DisplayB. 
Copying between Display is a great way to improve efficiency, QIANG LIE JIAN YI KE YI YOU...:)
![微信截图_20191017163557](https://user-images.githubusercontent.com/776181/66992615-b45e1400-f0fc-11e9-99c0-ece8bbac084e.png)

**Comment by AndyFong** [comment]
1. Copy and Paste operations have been supported between slides in a display.
2. When comes in displays, we recommend using Display copy feature. #1272
