### ISSUE TITLE
How to implement the filtering of role permissions in the latest version

### ISSUE THREAD

**Issue by lzymax** [edp963/davinci#1285]
Currently, you can use the "role" to implement the permission control of the table field. I want to know how to set up the filtering of a certain field. For example, restricting a character can only view the "male" under the "gender" field. (Chinese documentation is no longer The latest version)

**Comment by lzymax** [comment]
The old version:
![image](https://user-images.githubusercontent.com/48306335/67845841-2726b080-fb3b-11e9-9c62-9f773a9dfb5d.png)
The new version：
![image](https://user-images.githubusercontent.com/48306335/67845878-3ad21700-fb3b-11e9-91d7-99115c046307.png)

**Comment by lzymax** [comment]
The old version:
![image](https://user-images.githubusercontent.com/48306335/67846081-90a6bf00-fb3b-11e9-8936-04fae2734756.png)
The new version:
![image](https://user-images.githubusercontent.com/48306335/67846123-a61be900-fb3b-11e9-855b-11bc2c827619.png)

**Comment by AndyFong** [comment]
Steps:  
1. Add roles in the Organization,
2. Relate them to a certain Project in the Organization
3. Edit view with sql and auth params in new View editing page
4. As the screenshot 2 you post, distribute params' value to the current roles  in this Project (setting in step 2) which shown in the page table columns
5. Test the auth params value by login with corresponding role of user
