### ISSUE TITLE
bus about data drill and data linkage

### ISSUE THREAD

**Issue by Suarez999** [edp963/davinci#1290]
when you first use data drills and then use data linkage,some bugs will appear.The first picture is the correct situation.But when you use data linkage on it,you can see the second picture,some bugs appear,like undefined,and show all data,not drill data.
![1572859453(1)](https://user-images.githubusercontent.com/28488641/68110640-5452d480-ff28-11e9-834c-448b3be95d8b.jpg)
![1572859417(1)](https://user-images.githubusercontent.com/28488641/68110648-587ef200-ff28-11e9-9142-67854a3e826a.jpg)

**Comment by ruanhan** [comment]
fixed #1350
