### ISSUE TITLE
Can't save name of grobal controller name.

### ISSUE THREAD

**Issue by dawsongzhao** [edp963/davinci#1294]
![图片](https://user-images.githubusercontent.com/7078308/68273004-41fba680-00a0-11ea-9907-97ed582ddaf7.png)
Can't save the name.
davinci version:davinci-assembly_3.0.1-0.3.1-SNAPSHOT-dist-beta.7.zip

**Comment by AndyFong** [comment]
![image](https://user-images.githubusercontent.com/6837655/68273983-dcf58000-00a2-11ea-84d7-7ac46dc1e0d3.png)

Edit and delete buttons will be shown when the mouse hovers on the item, if not, please provide more info, for OS system, Browser version, Davinci version and some others.
