### ISSUE TITLE
Role variable cannot be saved.

### ISSUE THREAD

**Issue by archongum** [edp963/davinci#1304]
SQL
![Snipaste_2019-11-08_16-21-02](https://user-images.githubusercontent.com/20929338/68461271-c7b85700-0244-11ea-8bce-bad33841a65a.jpg)
Set permissions
![Snipaste_2019-11-08_16-21-30](https://user-images.githubusercontent.com/20929338/68461272-c7b85700-0244-11ea-8cf7-7028a5a8968a.jpg)
Link user to role
![Snipaste_2019-11-08_16-23-25](https://user-images.githubusercontent.com/20929338/68461273-c850ed80-0244-11ea-95cb-d78c8e3950f0.jpg)
Query by `dev`'s user `qq`
![Snipaste_2019-11-08_16-25-25](https://user-images.githubusercontent.com/20929338/68461275-c850ed80-0244-11ea-8a59-e4126fe7b945.jpg)

Logs
```
context [anonymous] 1:39 attribute weekday isn't defined
```

**Comment by AndyFong** [comment]
![image](https://user-images.githubusercontent.com/6837655/68462103-ce47ce00-0246-11ea-8e4e-6852f307d25c.png)

try  wrap the sql condition with parentheses:  
`(where weekday in ($weekday$))`

**Comment by archongum** [comment]
@AndyFong

**Comment by scottsut** [comment]
@archongum try this `where (weekday = $weekday$)`

**Comment by archongum** [comment]
@scottsut 
It works! And it automatically uses `IN` if the variable has multipule values!
Thanks!
![Snipaste_2019-11-08_17-37-27](https://user-images.githubusercontent.com/20929338/68465974-7614ca00-024e-11ea-9e94-43cadd688b1d.jpg)

---

Should change the docs in here: https://edp963.github.io/davinci/view_guide.html
![Snipaste_2019-11-08_17-39-54](https://user-images.githubusercontent.com/20929338/68466237-f1767b80-024e-11ea-8dbc-88f85e040626.jpg)

**Comment by scottsut** [comment]
@archongum new documents will be release soon
