### ISSUE TITLE
The bar chart shows object

### ISSUE THREAD

**Issue by justeene** [edp963/davinci#1308]
柱状图点击时显示一堆object。
![image](https://user-images.githubusercontent.com/6252314/68728960-a91add00-0603-11ea-87a5-b6eae8c5f475.png)

**Comment by AndyFong** [comment]
Please provide reproduction steps.

**Comment by justeene** [comment]
1，新建柱状图，添加维度，指标，颜色
2，在样式勾选条形图，设置堆叠
3，在dashboard添加该柱状图，并且点击其中一条柱。

**Comment by ruanhan** [comment]
fixed
