### ISSUE TITLE
How to realize this bar graph

### ISSUE THREAD

**Issue by TsienG** [edp963/davinci#1313]
How to realize this bar graph

<img width="684" alt="微信图片_20191114165604" src="https://user-images.githubusercontent.com/4916372/68841870-5bd06580-0700-11ea-99cc-cc7e02d4e9fe.png">

**Comment by AndyFong** [comment]
![image](https://user-images.githubusercontent.com/6837655/69005423-19579480-095d-11ea-9d58-2e760061c8c4.png)

**Comment by TsienG** [comment]
I mean, what is the implementation technique of this chart?

**Comment by AndyFong** [comment]
Davinci uses echarts as its chart render library.
