### ISSUE TITLE
After npm start, the tsx file reports many error！How to solve quickly？

### ISSUE THREAD

**Issue by xudianz** [edp963/davinci#1319]
After npm start, the tsx file reports many error！How to solve quickly？

**Comment by AndyFong** [comment]
Typescript typing errors do not have any effects to the running and debug of the  web application.  
We will solve the typing errors in next few versions gradually.

**Comment by 1292150917** [comment]
It has a great impact. At the very beginning, when my computer was running, many errors were reported, which would lead to the computer directly card machine to output more than 100 errors in about 4 seconds and 1 second

**Comment by 1292150917** [comment]
@AndyFong
