### ISSUE TITLE
where the antd.css is imported from? a tech oroblem

### ISSUE THREAD

**Issue by WilkinWendy** [edp963/davinci#1321]
I have found anywhere,but I can't find out where the antd.css is imported, because of which i can't corrent the strategy of  antd varibles'override from lessloaderConfig to .less

**Comment by AndyFong** [comment]
`refs`:
1. https://ant.design/docs/react/use-with-create-react-app-cn#%E4%BD%BF%E7%94%A8-babel-plugin-import
2. https://github.com/edp963/davinci/blob/master/webapp/babel.config.js#L16
