### ISSUE TITLE
Not have super@davinci.com user and not have dabinci0.3 documents？

### ISSUE THREAD

**Issue by cong520** [edp963/davinci#1331]
The old documents:
![image](https://user-images.githubusercontent.com/18363125/69202470-c2300a80-0b7c-11ea-8b72-c0fd670d5db0.png)
Or my:
![image](https://user-images.githubusercontent.com/18363125/69201571-af680680-0b79-11ea-8c01-ddd0cf93a5fe.png)
Want to know if I am  an administrator?

**Comment by AndyFong** [comment]
Davinci 0.3 no longer creates initial account super@davinci.com, the creation of user comes by register operation in login page.  
The user who creates a specific project is the administrator of the project, and also can assign administrator role the other users. 

Davinci 3 online document: 
https://edp963.github.io/davinci/quickStart.html
