### ISSUE TITLE
Why do I have no default user installed?

### ISSUE THREAD

**Issue by zhaoyufei11011** [edp963/davinci#1338]
After I install and start the service according to the document, I can't use the default super@davinci.com user to log in, indicating that I don't have this user. I click to register and fill in the information without any response. Later, I added a user to the user table of the database to prompt me that the password is wrong. What is the way to encrypt the password field of the user table? How can I solve the problem of unable to log in?

**Comment by dt1018614769** [comment]
me too   !

**Comment by dt1018614769** [comment]
If you know, please let me know. Thank you!

**Comment by scottsut** [comment]
![image](https://user-images.githubusercontent.com/4098913/69521414-e2efca00-0f99-11ea-949b-5a82f7454358.png)

From [documents](https://edp963.github.io/davinci/)

**Comment by scottsut** [comment]
The updated [documents](https://edp963.github.io/davinci/docs/zh/1.1-deployment) may help you.

**Comment by zhaoyufei11011** [comment]
我没有任何用户可以登录到系统关键是这个，我点击注册也是没有任何反映，我在数据库加入用户后告诉我密码不对。我需要告诉我怎么来创建第一个用户？

**Comment by scottsut** [comment]
![image](https://user-images.githubusercontent.com/4098913/69524657-7f699a80-0fa1-11ea-8625-95466f8aa324.png)

**Comment by scottsut** [comment]
[Mail Configuration](https://edp963.github.io/davinci/docs/zh/1.1-deployment#243-mail-%E9%85%8D%E7%BD%AE)

**Comment by zhaoyufei11011** [comment]
非常感谢 确实是邮件的问题，
