### ISSUE TITLE
Start running a lot of warnings

### ISSUE THREAD

**Issue by 1292150917** [edp963/davinci#1342]
How do you use a lot of warning errors when you start running?

**Comment by 1292150917** [comment]
请注意查看

**Comment by 1292150917** [comment]
怎么发图片呢

**Comment by 1292150917** [comment]
![1574748246(1)](https://user-images.githubusercontent.com/24564509/69603598-1ee86500-1056-11ea-95d4-ad7e97521ec1.jpg)

**Comment by AndyFong** [comment]
duplicated of #1319
