### ISSUE TITLE
screenshots by phantomjs always http://localhost.. not the server ip address I set

### ISSUE THREAD

**Issue by yingw** [edp963/davinci#1344]
If I set server address to localhost:8080, the service can't be access from intranet IP, the opposite way is the same. So I set server address as inter ip and access from ELB to IP , but when I use the phantomjs screenshot function, I found the phantomjs always try to access localhost:8080, so the screenshots failed always.

I fix this temporaryly by set localhost point to the ip address in /etc/hots. But I think the phantomjs should access the real IP adderss in the applicaton.yml's server address property.

我的配置文件设置了服务器的地址通过IP访问，没什么问题。但是在phantomjs截屏的时候，还是调用的localhost地址，没有用到配置文件里面的IP地址，会调不到。临时解决办法是在hosts里面把localhost指向IP地址

**Comment by RichardShan** [comment]
If you deploy Davinci on cloud server,  you can try set `server.address` to 0.0.0.0 ,  and set `server.access.address` to your IP.

**Comment by yingw** [comment]
thanks, It works
