### ISSUE TITLE
Chart driven not s driven not suppor Multi indicator display？

### ISSUE THREAD

**Issue by ranmao** [edp963/davinci#1348]
![image](https://user-images.githubusercontent.com/1316986/69804836-5ef84500-121a-11ea-9009-5186968187c5.png)
![image](https://user-images.githubusercontent.com/1316986/69805054-cc0bda80-121a-11ea-95c6-d43373cdae88.png)

This is what I used metabase to do. Indicators of multiple districts and counties can be displayed on a graph
![image](https://user-images.githubusercontent.com/1316986/69804852-6881ad00-121a-11ea-9c98-18ac3f09b9e4.png)

**Comment by scottsut** [comment]
Follow [the document](https://edp963.github.io/davinci/docs/zh/2.3-widget#224-%E9%A2%9C%E8%89%B2)
