### ISSUE TITLE
Auth variable does not take effect 

### ISSUE THREAD

**Issue by wyr020040** [edp963/davinci#1360]
Unable to get the auth variable existed in the database in view. After viewing the code, I found that channels have always been null, resulting in the failure to obtain the permission variable from the database.

**Comment by scottsut** [comment]
I suggest you read the code carefully. Auth variables usually related to roles, and are
not strongly dependent on channels.

**Comment by wyr020040** [comment]
![角色](https://user-images.githubusercontent.com/23185591/70719373-d8208d80-1d2c-11ea-882e-1615f5203ee4.png)
![关联用户](https://user-images.githubusercontent.com/23185591/70719397-e1115f00-1d2c-11ea-9901-8b752d3599be.png)
![设置权限变量](https://user-images.githubusercontent.com/23185591/70719428-ef5f7b00-1d2c-11ea-8203-ec4c0cb0f7fc.png)
![使用权限变量](https://user-images.githubusercontent.com/23185591/70719437-f5555c00-1d2c-11ea-8323-e9b5de2bc08e.png)
![角色设置权限变量的值](https://user-images.githubusercontent.com/23185591/70719453-fd150080-1d2c-11ea-8a4e-d6dc05e96b93.png)
![错误的结果](https://user-images.githubusercontent.com/23185591/70719469-04d4a500-1d2d-11ea-8302-3d12f6ee9ab6.png)

I set the Auth variable as the new ducument,but did not take effect.

**Comment by xuronglian** [comment]
I encountered the same problem。Is a bug in version 0.3???

**Comment by AndyFong** [comment]
You  need to relate the `Role` to a specific `Project` in the `Organization`.  

ref:   
Page https://edp963.github.io/davinci/docs/zh/3.4-project
Part 3.1

**Comment by xuronglian** [comment]
其实操作说明文档很清晰，我们是完全按照说明文档操作的，其他功能都可以，列权限也生效，就是行级权限不行。我看到0.3-beta.8版本修复了行级权限的问题。我们目前使用版本就是这个版本，不过我们是在docker里面运行。

**Comment by AndyFong** [comment]
@RichardShan
