### ISSUE TITLE
Problem in permission control of the table field

### ISSUE THREAD

**Issue by humphreyzzz** [edp963/davinci#1366]
I followed the steps to implement the filtering of role permissions you offered in Issue [How to implement the filtering of role permissions in the latest version](https://github.com/edp963/davinci/issues/1285) but it didn't work. I tried to read the source code and found that the process of assembling SQL statement leads to the function **parseSql** . In **parseSql**, the code tries to get the value of the variable I set in SQL statement with the function **getAuthVarValue**. Function **getAuthVarValue** takes in a instance of class SqlVariable and when SqlVariable.channel is null, it will call another function,   **SqlVariableValueTypeEnum.getValues**, to get the value. **SqlVariableValueTypeEnum.getValues** will return null when the default value of SqlVariable is null. The problem is that the sqlVariable.channel and sqlVariable.defaultValues are always null in my situation, which leads to the failure of my filter. Could you please explain how sqlVariable.channel can be set or how can I solve this problem?

**Comment by scottsut** [comment]
[Documents](https://edp963.github.io/davinci/docs/zh/2.2-view#112-%E6%9D%83%E9%99%90%E5%8F%98%E9%87%8F) has been updated, maybe you should read it first
