### ISSUE TITLE
启动到相同的位置，windows环境下意外退出，centos环境下无法往下执行

### ISSUE THREAD

**Issue by shupeaceful** [edp963/davinci#1371]
15:37:58.589 [background-preinit] DEBUG org.jboss.logging - Logging Provider: or
g.jboss.logging.Log4j2LoggerProvider
15:37:58.599 [background-preinit] INFO org.hibernate.validator.internal.util.Ver
sion - HV000001: Hibernate Validator 6.0.11.Final
15:37:58.623 [background-preinit] DEBUG org.hibernate.validator.internal.engine.
resolver.TraversableResolvers - Found javax.persistence.Persistence on classpath
 containing 'getPersistenceUtil'. Assuming JPA 2 environment. Trying to instanti
ate JPA aware TraversableResolver
15:37:58.629 [background-preinit] DEBUG org.hibernate.validator.internal.engine.
resolver.TraversableResolvers - Instantiated JPA aware TraversableResolver of ty
pe org.hibernate.validator.internal.engine.resolver.JPATraversableResolver.
15:37:58.639 [background-preinit] DEBUG org.hibernate.validator.internal.xml.con
fig.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based V
alidator configuration.
15:37:58.645 [background-preinit] DEBUG org.hibernate.validator.internal.xml.con
fig.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
15:37:58.647 [background-preinit] DEBUG org.hibernate.validator.internal.xml.con
fig.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate
Validator's class loader
15:37:58.651 [background-preinit] DEBUG org.hibernate.validator.internal.xml.con
fig.ValidationXmlParser - No META-INF/validation.xml found. Using annotation bas
ed configuration only.
15:37:58.988 [background-preinit] DEBUG org.hibernate.validator.messageinterpola
tion.ResourceBundleMessageInterpolator - Loaded expression factory via original
TCCL
15:37:59.005 [background-preinit] DEBUG org.hibernate.validator.internal.engine.
ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolat
ion.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpo
lator.
15:37:59.007 [background-preinit] DEBUG org.hibernate.validator.internal.engine.
ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.r
esolver.JPATraversableResolver as ValidatorFactory-scoped traversable resolver.
15:37:59.010 [background-preinit] DEBUG org.hibernate.validator.internal.engine.
ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.Exe
cutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.

15:37:59.012 [background-preinit] DEBUG org.hibernate.validator.internal.engine.
ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.D
efaultClockProvider as ValidatorFactory-scoped clock provider.
15:37:59.014 [background-preinit] DEBUG org.hibernate.validator.internal.engine.
ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.s
cripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluat
or factory.

**Comment by tcdjl** [comment]
麻烦问下、怎么处理的？

**Comment by HongXiang1314** [comment]
Please ask, how to deal with it?

**Comment by hldiao** [comment]
最后怎么处理的呢？
