### ISSUE TITLE
麻烦帮忙看下连接Mysql老是不行

### ISSUE THREAD

**Issue by dt1018614769** [edp963/davinci#1379]
您好，我想连接Mysql  数据库版本是5.6 正常都没问题。驱动包也有 也有错误日志
![7](https://user-images.githubusercontent.com/28726343/70614096-dc717b80-1c44-11ea-8b1c-f202de3fa575.png)
![6](https://user-images.githubusercontent.com/28726343/70614113-e2675c80-1c44-11ea-9aec-ee02257d7af3.png)
![5](https://user-images.githubusercontent.com/28726343/70614117-e5624d00-1c44-11ea-8172-e6ee96a82c32.png)

**Comment by scottsut** [comment]
We recommend you to use [the latest release](https://github.com/edp963/davinci/releases).
