### ISSUE TITLE
无法拖动维度和指标，mysql数据库

### ISSUE THREAD

**Issue by bobzhanggmail** [edp963/davinci#1381]
版本：davinci-assembly_3.0.1-0.3.1-SNAPSHOT-dist-beta.8.zip
安装成功后，注册登录进去，在widget这里，新建了一个，但发现无法拖动指标或维度字段，看了手册也没提到有这类问题
![微信截图_20191212150224](https://user-images.githubusercontent.com/9858448/70689945-8528e500-1cf0-11ea-9437-85514fb70fd5.png)

**Comment by bobzhanggmail** [comment]
Chrome和IE都试了，都不行。
log里看也没错误信息。

**Comment by scottsut** [comment]
This may not be a common problem, please tell us your browsers version.

**Comment by bobzhanggmail** [comment]
![image](https://user-images.githubusercontent.com/9858448/70772462-92f16f80-1daf-11ea-90c0-90cd6dccce82.png)

**Comment by scottsut** [comment]
Seems like some unexpected problems prevented drag event. I suggest you reinstall Chrome and try again.

**Comment by bobzhanggmail** [comment]
我是部署在虚机里的，虚机重启过，chrome也重启过，几天了都没能成功，F12看这个页面，有个404报错：
![image](https://user-images.githubusercontent.com/9858448/70776188-5590e000-1db7-11ea-91e3-88edee2ab016.png)
10.2.202.212是我虚机的IP。

**Comment by scottsut** [comment]
Reinstall Chrome, not relaunch.

And there are no `layer.css` and `userscript.html` in Davinci's codebase.

**Comment by bobzhanggmail** [comment]
我换了台电脑，用上面的chrome访问后，可以正常使用的，谢谢

**Comment by bobzhanggmail** [comment]
经多次尝试，发现要关掉chrome的油猴，关掉就好了
