### ISSUE TITLE
Error: Could not find or load main class edp.DavinciServerApplication

### ISSUE THREAD

**Issue by dt1018614769** [edp963/davinci#1382]
我用老版本没问题  用新版本就报这个错误
![dav](https://user-images.githubusercontent.com/28726343/70704254-9e3f8f00-1d0c-11ea-9dbc-62f789bf6599.png)

**Comment by dt1018614769** [comment]
能回复下嘛？为什么会报这个错？我看很多有都这个问题

**Comment by RichardShan** [comment]
Are you sure you are deployed a release package instead of the source code?

**Comment by TravelerZw** [comment]
我也遇到这个问题 用maven编译之后 运行start-server.sh 找不到或无法加载主类 edp.DavinciServerApplication
