### ISSUE TITLE
how to add a time picker in dispay.thanks

### ISSUE THREAD

**Issue by chenweizhaoup** [edp963/davinci#1384]
how to add a time picker in dispay.thanks

**Comment by chenweizhaoup** [comment]
![微信图片_20191213101055](https://user-images.githubusercontent.com/17274752/70764023-29626880-1d91-11ea-9de8-1fc322b1a30a.png)
like this.thanks.
@Answer1013

**Comment by scottsut** [comment]
Related to #1734
