### ISSUE TITLE
select json data from mysql without quotes

### ISSUE THREAD

**Issue by kengle** [edp963/davinci#1391]
we use
` select `json`->'\$.name' from table_xx `
in sql editor, the result contains quotes as below

> "fake@email.com"

but if we use 
` select `json`->>'\$.mail' from table_xx `
then we can get the result without quotes but unreadable as blow

> 6C75632E6170617369383840676D61696C2E636F6D

plz upgrade the mysql driver to mysql-connector-java-8.0.18

**Comment by scottsut** [comment]
You can add mysql8 driver as a [custom datasource](https://edp963.github.io/davinci/docs/zh/1.1-deployment#31-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90).
