### ISSUE TITLE
Filter doesn't Support Chinese（MS SQL Server）

### ISSUE THREAD

**Issue by lvchaoin** [edp963/davinci#1412]
It looks like the filter does not support Chinese characters, could you help to make it work ? Since our end user will use Chinese characters in the system.

Normally if we want to use Chinese in MS SQL, the sentence needs to add prefix like this:  N'%短裤%'

![image](https://user-images.githubusercontent.com/506134/71439498-dbf0de80-2734-11ea-8b44-93bb6bbfd660.png)

Thanks a lot !

**Comment by scottsut** [comment]
It works well in our test environment, this may be a connection character set problem, we only support UTF-8.

**Comment by lvchaoin** [comment]
Thanks, ALTER DATABASE COLLATION to Chinese_PRC_CI_AS resolved my issue. It's due to SQL server storage collation not the connection character.
