### ISSUE TITLE
Language is default chinese but not work

### ISSUE THREAD

**Issue by ZengTianShengZ** [edp963/davinci#1415]
```javascript
const render = (messages) => {
  ReactDOM.render(
    <Provider store={store}>
      <LanguageProvider messages={messages}>
        <LocaleProvider locale={zh_CN}>
          <Router
            history={history}
            routes={rootRoute}
            render={applyRouterMiddleware(useScroll())}
          />
        </LocaleProvider>
      </LanguageProvider>
    </Provider>,
    MOUNT_NODE
  )
}
```

The default language is 'zh_CN', but the actual situation is 'en' 

![image](https://user-images.githubusercontent.com/15622519/71471724-69066700-280b-11ea-95b5-6cecb4239d8f.png)

![image](https://user-images.githubusercontent.com/15622519/71503597-d4564480-28b0-11ea-98da-dc95d3e4d577.png)

what should I do to set language to Chinese

**Comment by AndyFong** [comment]
Please update to the the lastest version and this problem has been solved.

**Comment by ZengTianShengZ** [comment]
Can you tell me which branch fixed the problem, I want to see details 🙏
