### ISSUE TITLE
Problem when add Phoenix Driver

### ISSUE THREAD

**Issue by Jianglai113** [edp963/davinci#1423]
When I add Phoenix Driver(org.apache.phoenix.jdbc.PhoenixDriver), I found this problem,
problem:
LoggerFactory is not a Logback LoggerContext but Logback is on the classpath.
Either remove Logback or the competing implementation
If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.Log4jLoggerFactory

please help me, thank you so much.

**Comment by RichardShan** [comment]
You can try [multi-version](https://edp963.github.io/davinci/docs/zh/1.1-deployment#32-%E5%A4%9A%E7%89%88%E6%9C%AC%E9%9A%94%E7%A6%BB)  isolation.
