### ISSUE TITLE
Fail to setup row auth of user

### ISSUE THREAD

**Issue by DM-NUM** [edp963/davinci#1438]
你好，最近在使用davinci發現：根據官方描述文檔設置了角色，用管理员A账号创建了项目A, 并制作了一个仪表板，并添加了b账号成员， 并分配了角色：「test」;  然后将角色「test」关联了项目A, 并用权限变量限制了角色「test」的行级权限， but：it fail done~~報錯信息如下：
ERROR 6681 --- [127-8081-exec-3] e.d.core.config.RestExceptionHandler     : Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/sun/tools/javac/util/ListBuffer；

![图片](https://user-images.githubusercontent.com/41332648/72032816-791e4c00-32cb-11ea-92bc-6c3b145686c7.png)

—Could any guys  tell me how to slove this problem, thx very much!

**Comment by DM-NUM** [comment]
我尝试了在macbook 和 windows 分别安装了docker-davinci-0.3.0-beta.8 版本和 本地davinci-0.3.0-beta.8 版本， 但都無出現了這個問題，請問是產品目前的問題還是我配置上的問題呢？

**Comment by xxxllluuu** [comment]
请在本地开发环境将tools.jar加入classpath

**Comment by DM-NUM** [comment]
> 请在本地开发环境将tools.jar加入classpath

thx~  我已经将java的环境变量都设置了，但是还是起不到作用，还是一样的的错误～～
![image](https://user-images.githubusercontent.com/41332648/72140040-d0efac80-33ca-11ea-98ce-5baead3cca0b.png)

**Comment by DM-NUM** [comment]
> 请在本地开发环境将tools.jar加入classpath

后来从新配置了java的环境变量，成功了！！ 原因应该就是tool.jar读取不到的问题，感谢啦！
