### ISSUE TITLE
table rel_user_organization do not have column update_by

### ISSUE THREAD

**Issue by fasoal** [edp963/davinci#1448]
update member role
![image](https://user-images.githubusercontent.com/14243815/72400539-8ed8b900-3784-11ea-8831-6418db583fbb.png)
in davinci.sql do not have it at all
![image](https://user-images.githubusercontent.com/14243815/72400606-c9daec80-3784-11ea-9b8a-2d83eb0aa547.png)

**Comment by xxxllluuu** [comment]
it fixed on davinci-0.3.0-beta.9 release
