### ISSUE TITLE
Dashboard export excel something wrong

### ISSUE THREAD

**Issue by kingslyChen** [edp963/davinci#1452]
hi,Dashboard like this 
![image](https://user-images.githubusercontent.com/13058948/72582564-1e659f80-391e-11ea-91ac-1f69c6ff4ccf.png)
but excle like this
![image](https://user-images.githubusercontent.com/13058948/72582594-2f161580-391e-11ea-8fe9-b37a68aa691d.png)

**Comment by scottsut** [comment]
This is correct. We only export data details without visual encoding
