### ISSUE TITLE
after set content-path,can't found js file!

### ISSUE THREAD

**Issue by wengad82** [edp963/davinci#1454]
after i set content-path, for example to be "gg",and then access the davinci ,can't find js, 
the system found the js under /,but not /gg.

设置了content-path之后，比如gg，访问系统http:/xx/gg，找不到JS，还是到/下找JS，导致找不到

**Comment by AndyFong** [comment]
https://github.com/edp963/davinci/blob/dev-0.3/webapp/internals/webpack/webpack.prod.babel.js#L26

You may need to edit `output` value by add child property `publicPath: "/gg/"` (in your case), and `npm run build` to re-generate the files under build directory.
