### ISSUE TITLE
Please add the  features  Pivot table specify the dimension total

### ISSUE THREAD

**Issue by Qzhouwen** [edp963/davinci#1457]
![透视表](https://user-images.githubusercontent.com/11662046/72677185-ae4d4a00-3ad4-11ea-9bd3-99dbd47b7e38.png)

**Comment by zhaoyoum** [comment]
yes, we need this feature.

**Comment by scottsut** [comment]
Related to #1403

**Comment by liaoqiang321** [comment]
@Qzhouwen ,请问为什么我的透视驱动生成的表格表头不显示？

**Comment by liaoqiang321** [comment]
@Qzhouwen 
![微信图片_20200321151832](https://user-images.githubusercontent.com/37368151/77221770-c1899e00-6b87-11ea-8bde-bbce29839432.png)
