### ISSUE TITLE
Could davinci UI display in English?

### ISSUE THREAD

**Issue by DM-NUM** [edp963/davinci#1469]
I want to set all the information dispaly use English , but some UI information are Chinese , could I change to English? How to setup? thanks~

**Comment by DM-NUM** [comment]
是否我可以在源码中更改界面的语言呢？入口在哪里呢？如下图中文字的地方
![image](https://user-images.githubusercontent.com/41332648/74397278-39f59480-4e4f-11ea-9a95-dd22a8467d73.png)

**Comment by AndyFong** [comment]
#1253

**Comment by scottsut** [comment]
Related to #1743
