### ISSUE TITLE
edp.DavinciServerApplication 

### ISSUE THREAD

**Issue by TravelerZw** [edp963/davinci#1476]
最新master分支  遇到一个小问题   我在 server/ 目录下执行 mvn clean package 然后启动start-server.sh 出错     找不到或无法加载主类 edp.DavinciServerApplication   感觉是没有把spring包打包进去

**Comment by RichardShan** [comment]
You should run `mvn clean package` command in the root directory, it will generate a zip file in the `assembly/target`, which is a release package. if you run package command  in the 'server' directory, it will just generate a `.jar` file of server code. Deployment and start server reference [document](https://edp963.github.io/davinci/docs/zh/1.1-deployment), please don't directly in the source directory execute `start-server.sh`.
