### ISSUE TITLE
Can not add mysql source

### ISSUE THREAD

**Issue by GodZzxw** [edp963/davinci#1479]
I can pass the test connection program but can not successfully add source

![image](https://user-images.githubusercontent.com/44257934/74605657-03e13a80-5105-11ea-92c2-bc5c6d206160.png)
 
![image](https://user-images.githubusercontent.com/44257934/74605681-38ed8d00-5105-11ea-8d77-d4117053610b.png)

**Comment by scottsut** [comment]
![image](https://user-images.githubusercontent.com/4098913/74697427-a4367c80-5235-11ea-96d9-aaab34602753.png)

We provide `mysql-connector-java-5.1.46.jar` by default, you need to add driver jar manually If you use MySQL higher than 5.7.
