### ISSUE TITLE
Can't add SQL Server Datasource 

### ISSUE THREAD

**Issue by zhaoyoum** [edp963/davinci#1481]
<img width="677" alt="微信图片_20200219013157" src="https://user-images.githubusercontent.com/52742741/74762104-25ceee80-52b8-11ea-9bc8-aa19ccf0aa5b.png">

when I click the Test Button, After a few minutes，it say: " Request faild with http 504 status" ；
and there is not log in the server.

Davinci version: 0.3-beta 8;
MSSqlserver 2018

**Comment by xxxllluuu** [comment]
Which jdbc driver are you using?

**Comment by zhaoyoum** [comment]
lib/mssql-jdbc-7.4.1.jre8.jar    and lib/mssql-jdbc-6.4.0.jre8.jar   ; it doesn't work!
our sqlserver version: Microsoft SQL Server 2016(SP2-CU8)(kb4505830)-13.0.5426.0(X64)

**Comment by zhaoyoum** [comment]
this issue has been soloved after I change the parameter ' spring_datasource_test_on_borrow  ' from true to false.
because in the docker-compose.yml. this parameter has been set to true .
thank @xxxllluuu for help me to test this issue very much.
