### ISSUE TITLE
Please add the feature auth variable can be set the default value to get current login userid

### ISSUE THREAD

**Issue by zhaoyoum** [edp963/davinci#1502]
Hi  experters,

In our business system,   the permissions of which bu the login user can see are stored in the table 'dw_idp_RX_ORG_Hier'  。so when i create the view in davinci, I want join this talbe and the transaction table in my sql script ,and then create an auth variable named P_ID ，it means the logon userid .  

Whether the default value function of AUTH variable can be enhanced and the ID of current login user can be obtained

thank you very much！

**Comment by RichardShan** [comment]
`dev-0.3` branch already has the corresponding code. #1589
