### ISSUE TITLE
add background pictrue failed！

### ISSUE THREAD

**Issue by zhangjianpinghik** [edp963/davinci#1512]
{timestamp: "2020-03-04 18:57:01", status: 500, error: "Internal Server Error",…}
timestamp: "2020-03-04 18:57:01"
status: 500
error: "Internal Server Error"
message: "Failed to parse multipart servlet request; nested exception is java.io.IOException: The temporary upload location [/tmp/tomcat.619461149386485040.8097/work/Tomcat/localhost/ROOT] is not valid"
path: "/api/v3/displays/slide/2/upload/bgImage"

**Comment by AndyFong** [comment]
`java.io.IOException`  
Please make sure that java server have the right to write the image file in the directory of `/tmp`

**Comment by zhangjianpinghik** [comment]
@AndyFong the error is being where i add background pictrue for a display

**Comment by AndyFong** [comment]
It has been fixed in beta.9, please download the latest release package.
