### ISSUE TITLE
Bug: display editor is empty if we did not access details of related views before

### ISSUE THREAD

**Issue by chengjiexu** [edp963/davinci#1523]
console error: model is not defined
  const getWidgetViewModel = useCallback(
    (viewId: number) => {
      const viewModel = formedViews[viewId].model

**Comment by chengjiexu** [comment]
console error: model is not defined
webapp/app/containers/Display/Editor/SlideLayerList.tsx line:118
const getWidgetViewModel = useCallback(
(viewId: number) => {
const viewModel = formedViews[viewId].model

**Comment by AndyFong** [comment]
Please provide reproduction steps to check it as a bug or not.

**Comment by chengjiexu** [comment]
maybe some thing wrong with my dev env.
modify webpack to put index.html and share.html to build dir, and others to build/dist.
then use npm run the web ui and proxy /api to intellij which run the server.
in this way,  it report the error.

if i change nothing, it wont happen.

**Comment by AndyFong** [comment]
OK, I will close the PR. If you find new problem with it, please reopen this issue and leave your comment.
