### ISSUE TITLE
share dashboard lose Global control

### ISSUE THREAD

**Issue by oconnorendure** [edp963/davinci#1528]
I set a global parameter controller in the dashboard. When I share the dashboard, I open the shared page and find that the custom parameter drop-down box is missing, which makes it impossible to filter based on conditions. 
My Davinci version is  davinci-assembly_3.0.1-0.3.1-SNAPSHOT-dist-beta.9 
please help me
![image](https://user-images.githubusercontent.com/3263112/76059382-a597d100-5fb9-11ea-93aa-989de6c84de1.png)
![image](https://user-images.githubusercontent.com/3263112/76059397-b0526600-5fb9-11ea-98a6-9ed99867c3c3.png)
![image](https://user-images.githubusercontent.com/3263112/76059349-931d9780-5fb9-11ea-8695-e6bb5519d19d.png)

**Comment by scottsut** [comment]
We retested this feature and found no issues, please 
provide more information to help deep tracking.

**Comment by oconnorendure** [comment]
view:
![image](https://user-images.githubusercontent.com/3263112/76068084-7722f180-5fcb-11ea-9005-a12d11a10c00.png)
![image](https://user-images.githubusercontent.com/3263112/76068125-8a35c180-5fcb-11ea-9371-f70dd8d9f564.png)
Widget List:
![image](https://user-images.githubusercontent.com/3263112/76068295-dd0f7900-5fcb-11ea-98a7-0e8da049edc6.png)
![image](https://user-images.githubusercontent.com/3263112/76068368-0203ec00-5fcc-11ea-85a3-aad77ba69bf0.png)
dashboard:
![image](https://user-images.githubusercontent.com/3263112/76068434-19db7000-5fcc-11ea-8184-21e0e2af3500.png)
![image](https://user-images.githubusercontent.com/3263112/76068471-2e1f6d00-5fcc-11ea-8d1d-e6c08bb0733d.png)
![image](https://user-images.githubusercontent.com/3263112/76068520-3ecfe300-5fcc-11ea-9f6e-c37976f00dd8.png)

share.html:
![image](https://user-images.githubusercontent.com/3263112/76068566-560ed080-5fcc-11ea-849c-884fa65bae6f.png)

**Comment by oconnorendure** [comment]
@scottsut ,I see that the bug has been closed. I re-downloaded the package davinci-assembly_3.0.1-0.3.1-SNAPSHOT-dist-beta.9. Has the bug fixed the package? Thanks  a lot

**Comment by scottsut** [comment]
We'll update release package later, you can download it tomorrow.

**Comment by oconnorendure** [comment]
I re-download new package and deploy today,found this bug still exists -_-||  @scottsut

**Comment by scottsut** [comment]
I just downloaded and reinstalled the release package, and I'm pretty sure the problem has been fixed.
![image](https://user-images.githubusercontent.com/4098913/76188706-c8252680-6213-11ea-9dd7-5935f8ea03c5.png)
![image](https://user-images.githubusercontent.com/4098913/76188722-d1ae8e80-6213-11ea-8469-e6cde006ff11.png)
![image](https://user-images.githubusercontent.com/4098913/76188735-dbd08d00-6213-11ea-86e0-db2789899beb.png)

**Comment by oconnorendure** [comment]
could I have your wechat account? so that I can show you detail ,my wechat account is huang_15201783921   , thanks
