### ISSUE TITLE
下钻能全选吗？现在是一个个点，用户受不了

### ISSUE THREAD

**Issue by GoogleSmile** [edp963/davinci#1529]
您好，目前下钻能全选吗？我现在想选择柱状图所有省，下钻下面的市，但是我点，只能一个个点柱状图的每一个省，然后右键下钻到市。不能一下子全部选择每个柱，然后下钻吗？

![image](https://user-images.githubusercontent.com/43394770/76064629-04af1300-5fc5-11ea-980c-cff06807652c.png)

**Comment by scottsut** [comment]
Duplicate of #1530
