### ISSUE TITLE
Chart drill down has bugs

### ISSUE THREAD

**Issue by GoogleSmile** [edp963/davinci#1536]
There is a problem with the drill down of the chart. Clicking on the province to drill down to the city is OK at first, but after a few seconds, it automatically changes。【图表下钻有问题，点击省份下钻到城市，刚开始还可以，但是过了几秒，就自动变了】

![image](https://user-images.githubusercontent.com/43394770/76141034-91c49b80-609b-11ea-9716-ca9b35c9ee1b.png)
![image](https://user-images.githubusercontent.com/43394770/76141037-96894f80-609b-11ea-93ea-b95d420d88a9.png)

**Comment by scottsut** [comment]
1. Please provide reproduction steps.
2. Have you set polling time for this widget?
