### ISSUE TITLE
It's return 20 data when use the global controllers in Dashboard

### ISSUE THREAD

**Issue by songzhandong** [edp963/davinci#1593]
It's return 23 data from mysql is correct
![image](https://user-images.githubusercontent.com/6280632/77401379-c2206f80-6de7-11ea-9157-806448442c6c.png)
it's return 20 data when i use the global controllers in Dashboard
![image](https://user-images.githubusercontent.com/6280632/77401464-ebd99680-6de7-11ea-84f1-9396fec24cf7.png)
the sql append 'LIMIT 0, 20' in the log 
![image](https://user-images.githubusercontent.com/6280632/77402358-81295a80-6de9-11ea-95de-f3c8b8155715.png)
why?

**Comment by songzhandong** [comment]
version：davinci-assembly_3.0.1-0.3.1-SNAPSHOT-dist-beta.6.zip

**Comment by scottsut** [comment]
It is recommended that you upgrade the version.

**Comment by songzhandong** [comment]
beta9 is fixed this？I will try this ，thanks
