### ISSUE TITLE
富文本以及Display辅助矩形的功能太简单

### ISSUE THREAD

**Issue by mstaryi** [edp963/davinci#1599]
富文本以及Display辅助矩形的功能太简单，建议开放可以让用户自由编辑html。当前这2个功能的够配置都比较弱，如果可以自由编辑Html,很多场景下用户可以自己实现想要的特效

**Comment by scottsut** [comment]
Closed due to non-compliance with [community rules](https://github.com/edp963/davinci/issues/768)
