### ISSUE TITLE
The controller BUG

### ISSUE THREAD

**Issue by daniuEvan** [edp963/davinci#1614]
Hi,The filter field in the controller displays no data if it is in Chinese, only when it is in English.What should I do?

![image](https://user-images.githubusercontent.com/49090129/77824796-33da1f80-7140-11ea-87f4-f095d0130c7e.png)

![image](https://user-images.githubusercontent.com/49090129/77824813-4bb1a380-7140-11ea-87e9-72540da91a5f.png)

**Comment by scottsut** [comment]
Check if the related field of the control is correct.

**Comment by scottsut** [comment]
If it is not correct only in Chinese, you can check if Chinese conditional query is supported in this View.

**Comment by daniuEvan** [comment]
Yes, you are right, my view does not support Chinese queries

**Comment by daniuEvan** [comment]
However, it is normal for me to query in Chinese on the virtual machine
![image](https://user-images.githubusercontent.com/49090129/77838437-949c4300-71a6-11ea-8ca6-24d4fc0bd742.png)

**Comment by daniuEvan** [comment]
I solved this problem because it should be the coding problem of the database.
Solution: add "after" to the url connecting to the database?UseUnicode = true&characterEncoding = utf-8 & useSSL = false"

THANKS
