### ISSUE TITLE
图表排序问题

### ISSUE THREAD

**Issue by michelle-q** [edp963/davinci#1619]
使用图表驱动，添加颜色后，原本的排序会失效；
![image](https://user-images.githubusercontent.com/20435011/77982632-6605a000-733f-11ea-954d-0bc27f0ecf37.png)
去掉颜色就可以正常排序
![image](https://user-images.githubusercontent.com/20435011/77982676-79187000-733f-11ea-991f-d7fde02f505d.png)

**Comment by scottsut** [comment]
We don't think this is a problem with Davinci itself, looks like the data returned by the database is in the wrong order. You can try to simulate widget aggregation queries in View editor, group by date and color field and check the order of query results.

[Widget aggregation principle](https://edp963.github.io/davinci/docs/zh/2.3-widget#1-%E8%AE%BE%E8%AE%A1%E5%8E%9F%E7%90%86)
