### ISSUE TITLE
About Screenshot

### ISSUE THREAD

**Issue by lzymax** [edp963/davinci#1621]
In the Display, select the background and click to capture the cover. The captured picture is not full screen and has problems.

**Comment by scottsut** [comment]
Please post the problem

**Comment by lzymax** [comment]
![image](https://user-images.githubusercontent.com/48306335/78103078-835d6b80-741e-11ea-89e5-939c354f9075.png)
 for example

**Comment by AndyFong** [comment]
It will scale to 100% first in a animation, and then take the screenshot. It works properly in our env.   
You can post a gif screenshot to give a reproduction.
