### ISSUE TITLE
npm run build&npm start failed

### ISSUE THREAD

**Issue by wengshen** [edp963/davinci#1633]
![image](https://user-images.githubusercontent.com/49184564/78622834-c903b380-78b8-11ea-90e0-086297d1c2a2.png)
ERROR in ./share/app.tsx 111:12
Module parse failed: Unexpected token (111:12)
You may need an appropriate loader to handle this file type.
| if (!window.Intl) {
|   new Promise(function (resolve) {
>     resolve(import('intl'));
|   }).then(function () {
|     return Promise.all([import('intl/locale-data/jsonp/en.js')]);
 @ multi ./node_modules/react-app-polyfill/ie11.js ./share/app.tsx share[1]

ERROR in ./app/app.tsx 112:12
Module parse failed: Unexpected token (112:12)
You may need an appropriate loader to handle this file type.
| if (!window.Intl) {
|   new Promise(function (resolve) {
>     resolve(import('intl'));
|   }).then(function () {
|     return Promise.all([import('intl/locale-data/jsonp/en.js')]);
 @ multi ./node_modules/react-app-polyfill/ie11.js ./app/app.tsx app[1]
how to fix it?

**Comment by scottsut** [comment]
Looks like dependencies are not fully installed.

**Comment by wengshen** [comment]
> Looks like dependencies are not fully installed.

looks like missing some loader

**Comment by wengshen** [comment]
I got some hints about my question，It may be related to it@

> Looks like dependencies are not fully installed.

I got some hints about my question,It may be related to TypeScript **dynamic-import** 
[dynamic-import](https://github.com/tc39/proposal-dynamic-import)

**Comment by wengshen** [comment]
I resolve it,thany you

**Comment by scottsut** [comment]
You can write down your solution to help people with the same problem.

**Comment by luozejian** [comment]
> I resolve it,thanks

Please post the resolve method,I'm also trap in this problem.
Thanks!
