### ISSUE TITLE
表格自适应不太友好

### ISSUE THREAD

**Issue by qinqinnb** [edp963/davinci#1649]
![QQ截图20200422135838](https://user-images.githubusercontent.com/52516672/79946011-b20cb600-84a1-11ea-9eee-674ebe3147ff.png)
![Uploading QQ截图20200422135838.png…]()

![表格不自适应](https://user-images.githubusercontent.com/52516672/79945453-5e4d9d00-84a0-11ea-822f-5bda28a669f8.png)
1.dashboard中的表格经常出现滚动条，但下边界却出现很高一截空白，建议widget表格在数据列和行都比较少的情况下不应该有横向或者纵向滚动条，并且下边界不应该空出一截，

**Comment by qinqinnb** [comment]
如图

**Comment by scottsut** [comment]
We think the situation you listed is normal.
1. By default, the column width is automatically calculated based on the text content. If you do n’t want the horizontal scroll bar, you can set the column width manually.
2. It ’s best to show us what you think is the right way.
