### ISSUE TITLE
win10操作系统DAVINCI3_HOME环境变量不能有“-”

### ISSUE THREAD

**Issue by qinqinnb** [edp963/davinci#1651]
比如 C:\workspace-bi\davinci这种会导致启动不能正常运行，可以改为C:\workspace_bi\davinci

**Comment by xxxllluuu** [comment]
What is the error message? my DAVINCI3_HOME is D:\CE\UAVStackIDE\edpgitroot\davinci\assembly\target\davinci-assembly_3.0.1-0.3.1-SNAPSHOT-dist-beta.9 it works on my win10 pc
