### ISSUE TITLE
有没有业务系统集成davinci的方法或示例

### ISSUE THREAD

**Issue by zxhhappy** [edp963/davinci#1652]
davinci的伙伴们，请教一下 有没有 业务系统集成davinci的方法或示例？我有以下的需求看看如何是集成实现：
1. 单点登录
   用户登录业务系统，在某些页面中调用在davinci中制作好的Widget或Dashboard或Display，并进行与在davinci上相同的交互操作（不含制作过程的交互），调用时不需要再次输入用户名、密码
数据权限
2.  不同的业务用户，看相同的可视化对象（例如工资表），但是数据不同（仅可以看到自己的工资）
用户个性化
3.  用户除了可以访问与其他用户相同的可视化对象之外，还可以有自己独有或特制的可视化对象可以访问
4. 在业务系统，用户自己可以把可视化对象分享给该业务系统的其他人（需要登录后查看）或（不用登录就查看）

**Comment by AndyFong** [comment]
1. #791 or use LDAP integration(https://edp963.github.io/davinci/docs/zh/1.1-deployment LDAP configuration part)  

2. Role & View variables
  + [Davinci Role](https://edp963.github.io/davinci/docs/zh/3.3-role)
  + [Role in Project](https://edp963.github.io/davinci/docs/zh/3.4-project)
  + [View Auth variables config](https://edp963.github.io/davinci/docs/zh/2.2-view#3-%E8%A1%8C%E5%88%97%E6%9D%83%E9%99%90)  

3. Separate Vizs with multi Projects
4. Share 
  + [Dashboard Share](https://edp963.github.io/davinci/docs/zh/2.4-dashboard#23-%E5%88%86%E4%BA%AB)
  + [Display Share](https://edp963.github.io/davinci/docs/zh/2.5-display#215-%E9%A2%84%E8%A7%88%E4%B8%8E%E5%88%86%E4%BA%AB)

**Comment by zxhhappy** [comment]
Thank you very much!

**Comment by incubus-ohy** [comment]
请问一下现在这个功能你实现了吗，想请教一下你的处理思路
