### ISSUE TITLE
In the Dashboard or Display Download Widget throw a SqlException, Because I set color.

### ISSUE THREAD

**Issue by leexiangg** [edp963/davinci#1665]
If in Widget set the color , then you in the Dashboard or Display Download Widget , it throw a SqlException on the logfile. Because it have two same title in the Sql.

Tip：我的英语水平应该是说不清楚，所以这里再用中文说一遍。
如果在Widget设置了颜色，然后在Dashboard或者Display下载Widget，会在日志中抛出Sql异常。我看日志是因为Sql中出现了重复的字段。

今天伟大的墙不让上传图片了，哎。

**Comment by scottsut** [comment]
Duplicate of #1336
