### ISSUE TITLE
Invalid widgetid when adding auxiliary graphics on display

### ISSUE THREAD

**Issue by FatPP** [edp963/davinci#1676]
当我在大屏上添加辅助图形时，无效的widgetid出现。我debug源码时发现widgetid并没有传入，widgetid一直是null的，跟踪源码发现在DisplaySlideServiceImpl下面有一段
`List<Widget> widgets = widgetMapper.getByIds(ids);

			if (null == widgets || widgets.size() != ids.size()) {
				throw new ServerException("invalid widget id");
			}`
，事实上ids这个set里面的widgetid都是为null的，然后一直返回invalid widget id的错误，导致无法添加辅助图形。
我使用的源码版本是davinci-0.3.0-beta.9

**Comment by AndyFong** [comment]
It a front-end bug, has been fixed, please download the latest package.  
https://github.com/edp963/davinci/releases/download/v0.3.0-beta.9/davinci-assembly_3.0.1-0.3.1-SNAPSHOT-dist-beta.9.zip
