### ISSUE TITLE
npm start后前端代码改了没实时生效,要怎么解决?

### ISSUE THREAD

**Issue by gclsoft** [edp963/davinci#1680]
![image](https://user-images.githubusercontent.com/1269898/81536098-8f353980-939d-11ea-90e9-601e48965ca4.png)

**Comment by gclsoft** [comment]
前端改了代码每次都要重启才能生效吗?

**Comment by gclsoft** [comment]
谢谢,我暂时用域名解决了实时开发的问题, nginx解析专门的前端
![image](https://user-images.githubusercontent.com/1269898/81555912-fcf05e00-93bb-11ea-9150-c3b32d11869d.png)

**Comment by AndyFong** [comment]
```
cd webapp
npm run dev
```

**Comment by gclsoft** [comment]
> ```
> cd webapp
> npm run dev
> ```

master版本里没看到json里写有dev这个模式啊:
```
C:\work\reportBI\davinci\webapp>npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GZ000069\AppData\Roaming\npm-cache\_logs\2020-05-12T00_19_56_211Z-debug.log

```
