### ISSUE TITLE
Upload CSV problem

### ISSUE THREAD

**Issue by wxmcool** [edp963/davinci#1702]
When I upload a csv file,it is successful.But I upload a csv again,click the button (click to upload csv) fail,no error report. At this time,just  F5 refresh, then I can upload successfully.

**Comment by scottsut** [comment]
Fixed.

**Comment by wxmcool** [comment]
[capture.zip](https://github.com/edp963/davinci/files/4642642/capture.zip)
please see this video.

**Comment by scottsut** [comment]
Fixed in dev branch.

**Comment by wxmcool** [comment]
![image](https://user-images.githubusercontent.com/1018254/82276695-8b667000-99b8-11ea-937d-cfa7da73059c.png)
I update the code. there is new bug.

**Comment by scottsut** [comment]
This issue has been fixed does not mean that the dev branch is production ready. Ensure that an issue only solves the problems it describes.
