### ISSUE TITLE
Abnormal dashboard caused by widget configuration

### ISSUE THREAD

**Issue by hbzyb** [edp963/davinci#1763]
Setting the "color" label during widget editing will cause SQL exception of downloading excel file in the dashboard. It seems that the color field is also brought into the query statement.

As follows, there are multiple 'store_address' in the SQL:
`SELECT * FROM (SELECT
 `year4`,`store_address`,`store_address`
,
 sum(`sum_count`) AS 'sum(sum_count)'
FROM (SELECT `Dim Date`.`year4`,  `Dim Store`.`store_address`, sum(`fact_rental`.`count_rentals`) AS sum_count FROM `fact_rental` LEFT JOIN `dim_store` `Dim Store` ON `fact_rental`.`store_key` = `Dim Store`.`store_key` LEFT JOIN `dim_date` `Dim Date` ON `fact_rental`.`rental_date_key` = `Dim Date`.`date_key` WHERE 1=1  GROUP BY `Dim Date`.`year4`, `fact_rental`.`store_key` ORDER BY `Dim Date`.`year4` ASC, `fact_rental`.`store_key` ASC) T
GROUP BY `year4`,`store_address`,`store_address`
) MT WHERE 1=0`

**Comment by AndyFong** [comment]
Remove  'store_address' in dimension and keep it in color.
