### ISSUE TITLE
Support fuzzy query in dashboard controls 

### ISSUE THREAD

**Issue by LilyBlooper** [edp963/davinci#1767]
It's quite time-consuming when apply a control(filter) in dashboard while the target column has millions distinct values。
Please support a “fuzzy query" / "like %% query" in dashboard。
or support a max result size in control or filter 。

Thank you ~

**Comment by scottsut** [comment]
Related to #1703

**Comment by scottsut** [comment]
Fuzzy query is supported.

![image](https://user-images.githubusercontent.com/4098913/83092597-3b7e5c00-a0d0-11ea-86e6-adf3f1653a33.png)
