### ISSUE TITLE
how compile front-end code ? 

### ISSUE THREAD

**Issue by legend91325** [edp963/davinci#1770]
I am an backend development， I already run success backend code 。 but I don`t how to compile fornt code. Do anyone have some experience about it ?

我是一名后端工程师，后端代码已经成功运行了，请问前端如何编译打包部署呢？ 我现在把webapp代码单独拿出来，放在代码库里了。 后续考虑前后端开发分开。 但是我对前端经验很少，编译一直各种失败。 请问有谁有成功编译前端代码的经验吗？或者官方是否有关于前端代码的文档。 官方文档大多都是配置后端的。
谢谢。

**Comment by AndyFong** [comment]
*ref:*
    https://github.com/edp963/davinci/blob/master/CONTRIBUTING-CH.md#%E5%89%8D%E7%AB%AF

**Comment by legend91325** [comment]
> _ref:_
> https://github.com/edp963/davinci/blob/master/CONTRIBUTING-CH.md#%E5%89%8D%E7%AB%AF

the document about front code is too simple, when compile, always have some error information.

**Comment by legend91325** [comment]
> _ref:_
> https://github.com/edp963/davinci/blob/master/CONTRIBUTING-CH.md#%E5%89%8D%E7%AB%AF

run commond "npm run build ", after that ,the error info is :
No bundles were parsed. Analyzer will show only original module sizes from stats file.

![557AFA09-5377-4543-AA1C-642E8FCAA8E1](https://user-images.githubusercontent.com/7420287/83386505-c5565e00-a41d-11ea-9c5c-35149cb6298f.png)

**Comment by AndyFong** [comment]
the `image-webpack-loader` was not installed properly, may caused by the network blocking.  
Try to use `nrm` to switch the mirror address:

```
npm i nrm -g
nrm use taobao
cd webapp
rm -rf node_modules
npm i
npm run build
```

**Comment by legend91325** [comment]
@AndyFong 多谢，最后搞定了。我的问题是在windows环境无法成功安装依赖。
遇到问题如下：
https://github.com/imagemin/imagemin-pngquant/issues/46
解决方案：
1. 改为在unbunt 环境， 提前安装
`apt-get install libpng-dev`
2. 把项目名重命名为 webapp， 不理解为啥要改文件名，官方也没有人来释义下？
3. 使用淘宝的cnpm 安装
4. server/index.js 文件修改代码
`app.listen(port, host, async err => {
 if (err) {
   return logger.error(err.message)
 }

 logger.appStarted(port, prettyHost)
})`
改为
`app.listen(port, host)`  
懂的可以解释下

最后虽然也会有依赖包安装失败，但是把安装失败的手动安装下即可了。

之后
`npm start`
`npm build`
均可正常运行了。 
上面有些操作 ，我不太懂前端，也不知道具体原理。 如果有懂的可以解释下。 

问题我关闭了，因为我的问题已经解决。接下来我们尝试接入我们自己内部的部署服务，有问题再重新开issues 。
