### ISSUE TITLE
In the double Y-axis chart, the negative part of the line chart will disappear.

### ISSUE THREAD

**Issue by silegon** [edp963/davinci#1778]
In the double Y-axis chart, the negative part of the line chart will disappear.
双Y轴图中，折线图的负值部分会消失。
![双Y轴图](https://user-images.githubusercontent.com/635500/83385627-2b41e600-a41c-11ea-8517-cc3d4f03d65c.png)

**Comment by scottsut** [comment]
Related to #1704
