### ISSUE TITLE
how to deploy front code  Independent ? 

### ISSUE THREAD

**Issue by legend91325** [edp963/davinci#1784]
你好 ，我们现在想二次开发整个项目，前后端代码目前是分开的，但是后端配置了前端绝对访问地址，请问可以在生产环境上，独立部署 前后端代码吗？ 不需要放在同一个物理服务器上。

**Comment by AndyFong** [comment]
*ref:*  
https://github.com/edp963/davinci/blob/master/webapp/app/globalConfig.ts

**Comment by legend91325** [comment]
> _ref:_
> https://github.com/edp963/davinci/blob/master/webapp/app/globalConfig.ts

我看到这个文件了哈。
我现在主要的问题是 如何把前端单独部署 并且能够实现前后端 请求。 我本身是偏后端的，对前端这块不是很了解。 所以部署起来比较吃力，前两天刚搞好前端这个项目的编译，测试启动。

1. 我是否可以在前端通过配置前端的域名来访问后端服务。
2. 后端配置的依赖前端 配置 是否有必要。
3. 我直接把编译好的前端代码，放到nginx 上 。 这种思路是否可行？

**Comment by AndyFong** [comment]
在前后端分离的前提下，部署自然也是可以分离独立的。  
1. 上面贴的前端文件，配置的是开发环境和生产环境下服务接口的访问地址，解决了独立部署时前端访问后端服务问题；  
2. 在分开部署时，会有跨域访问的情况，这时，后端可以允许任意跨域访问或是指定地址访问，指定地址访问下后端需要配置前端地址白名单；  
3. 当然可以。
