### ISSUE TITLE
Support query variable in share dashboard url [enhancement]

### ISSUE THREAD

**Issue by LilyBlooper** [edp963/davinci#1796]
In real scenarios , the system which davinci share dashboard was embedded to usually has individual RBAC-based auth model . So we embed share dashboard only using query variables。

now (dev-0.3) ， one can only apply a dynamic query param using "global control " in dashboard .
We usually need the query params interchangable with query variable. 

![image](https://user-images.githubusercontent.com/7007552/84355738-b3cb3e00-abf5-11ea-87b7-77f271f0ecc6.png)

In query variable configuration during view settings . A query variable could be chosen as string with multiple default values , while in url param ， the value cound only be  “single” 。

For example : 
This is a mock project 。The project has multiple menus ， each menus was authorized to certain roles . The role and auth mode was provided in the project itself 。 So Davinci's organization and role model will not be used . 
![image](https://user-images.githubusercontent.com/7007552/84356206-74e9b800-abf6-11ea-9539-bbe90289fbe2.png)

![image](https://user-images.githubusercontent.com/7007552/84355895-f725ac80-abf5-11ea-9a9d-537b53565575.png)

Here we need to pass the query param with multiple values 。 
One menu will link http://davinci3/share.html#shareInfo=aaaaaaa&type=dashboard&var_domain_in=foo,bar,baz
Other menu will link 
http://davinci3/share.html#shareInfo=aaaaaaa&type=dashboard&var_domain_in=another,yetanother

we expect the params will overwrite the default values set in view .
This enhancement will really useful in many cases 。

**Comment by scottsut** [comment]
We now support multiple params format like `&var_domain_in[0]=foo&var_domain_in[1]=bar`. However, in some environments, nginx will treat the square brackets as illegal characters, so we gonna support the basic format like `&var_domain_in=foo&var_domain_in=bar` in the near future.

**Comment by ruanhan** [comment]
now support multiple params format like `&a=1&a=2&a=3` in origin/dev-0.3
