### ISSUE TITLE
Support area style in bar / line charts 

### ISSUE THREAD

**Issue by LilyBlooper** [edp963/davinci#1801]
Area style is a property / option in line / bar charts . 
Any chance to add on this property and configuration ? 
![image](https://user-images.githubusercontent.com/7007552/84622809-7c6bd280-af10-11ea-85aa-25b03cb3439b.png)

![image](https://user-images.githubusercontent.com/7007552/84622827-85f53a80-af10-11ea-8370-1d5dc6f5b3e6.png)

**Comment by scottsut** [comment]
Related to #1710
