### ISSUE TITLE
Support color theme or provide much more color in default theme

### ISSUE THREAD

**Issue by LilyBlooper** [edp963/davinci#1803]
In default theme , there're only 8 colors  and no color theme could be choosed .
If there are more than 8 colors in a wiget ( which always happens 😭 ) ，color will duplicate 。
We dont customize color value by value usually , so if there is another theme which has much more colors (a macaron theme in the source code) ， **color will duplicate less often , which helps a lot** 
![image](https://user-images.githubusercontent.com/7007552/84631366-d3c56f00-af1f-11ea-85f8-470cdfb6d806.png)

**Comment by scottsut** [comment]
Related to #1729
