### ISSUE TITLE
Can you merge “fix: global control custom options lost in share page #1532” into dev-0.3？

### ISSUE THREAD

**Issue by Zhongger** [edp963/davinci#1808]
Can you merge “fix: global control custom options lost in share page #1532” into dev-0.3？

**Comment by scottsut** [comment]
Merged.

**Comment by Zhongger** [comment]
> Merged.

Is the front-end code recompiled?

**Comment by Zhongger** [comment]
> Merged.

I'm a java programmer, and I don't understand the compilation of front-end code

**Comment by scottsut** [comment]
You can re-download the beta.9 release package, this problem has been fixed.

**Comment by Zhongger** [comment]
> You can re-download the beta.9 release package, this problem has been fixed.

Thank you！
