### ISSUE TITLE
How can I associate a drop-down list with another view rather than an existing diagram?

### ISSUE THREAD

**Issue by Zhongger** [edp963/davinci#1809]
For example, these drop-down lists are the global controllers of the business module diagram. The business module diagram is linked with the figure on the left:

![image](https://user-images.githubusercontent.com/50549484/84868326-16698180-b0af-11ea-84ea-d3854776d5c3.png)

They come from different SQL views.If I only need the values in the drop-down list to query the left figure as a condition and do not want the business module figure, what should I do?

Can youdevelop such a function?

**Comment by scottsut** [comment]
This feature is in progress and will be available in the next release.

**Comment by scottsut** [comment]
Related to #1703
