### ISSUE TITLE
No Access URL http://localhost:5002

### ISSUE THREAD

**Issue by yanborer** [edp963/davinci#1826]
Use idea to start back-end application, port 8080, start normally.

Using webstorm to open the front-end application, cnpm install and cnpm start have no problems.

But Google browser access localhost:5002 , unable to jump to the login page.

Nodejs version 10.15.3, NPM version 6.4.1

**Comment by yanborer** [comment]
谷歌访问http://localhost:5002，打开后是index.html的内容，背景一片空白，只有几个点在来回显示

**Comment by scottsut** [comment]
Please provide the error information.

**Comment by zhang382847657** [comment]
我也遇到这个问题了，控制台报错，es.array.index-of.js?ecb4:15 Uncaught TypeError: $ is not a function

**Comment by scottsut** [comment]
> 我也遇到这个问题了，控制台报错，es.array.index-of.js?ecb4:15 Uncaught TypeError: $ is not a function

This is a core-js dependency problem in `cnpm`, you can choose one of the following ways to solve it:
a. Just use `npm` to install dependencies.
b. First `npm install core-js`,  then `cnpm install` other dependencies.

**Comment by lly277365** [comment]
> > 我也遇到这个问题了，控制台报错，es.array.index-of.js?ecb4:15 Uncaught TypeError: $ is not a function
> 
> This is a core-js dependency problem in `cnpm`, you can choose one of the following ways to solve it:
> a. Just use `npm` to install dependencies.
> b. First `npm install core-js`, then `cnpm install` other dependencies.

Follow your guideline, npm install core-js and then cnpm install, but not work, still caught 'TypeError: $ is not a function' problem.

**Comment by scottsut** [comment]
> Follow your guideline, npm install core-js and then cnpm install, but not work, still caught 'TypeError: $ is not a function' problem.

We just found that this doesn't work on Windows. For quick fix, Windows users can remove `core-js` and add `babel-polyfill` back according [this commit](https://github.com/edp963/davinci/pull/1790/commits/27a9440aaca38c9c3b877dbce7af153e80b693a2), then re-install dependencies, it will work. And we'll give a solution later.

**Comment by lly277365** [comment]
> > Follow your guideline, npm install core-js and then cnpm install, but not work, still caught 'TypeError: $ is not a function' problem.
> 
> We just found that this doesn't work on Windows. For quick fix, Windows users can remove `core-js` and add `babel-polyfill` back according [this commit](https://github.com/edp963/davinci/pull/1790/commits/27a9440aaca38c9c3b877dbce7af153e80b693a2), then re-install dependencies, it will work. And we'll give a solution later.

According to your reply, it is running normally now. Thank you for your help.

**Comment by scottsut** [comment]
https://blog.hhking.cn/2020/08/21/babel-with-node-modules/
Thanks to the community for helping find the problem!

**Comment by scottsut** [comment]
Still can't fully use `cnpm` to install dependencies, it will cause `core-js` import circularly, please use npm to install dependencies.

墙内用户可以参考以下步骤安装前端依赖：
1. 删除 `package-lock.json`;
2. 去掉 `package.json` 中的 `image-webpack-loader`，使用 `npm` 安装依赖
3. 最后使用 `cnpm install image-webpack-loader`

参考文章：https://my.oschina.net/itlangz/blog/1921136

**Comment by sunxiongtong** [comment]
Using cnpm to download, there is still the problem of image webpack loader

**Comment by liuxsen** [comment]
是否考虑解决下呢，

> Still can't fully use `cnpm` to install dependencies, it will cause `core-js` import circularly, please use npm to install dependencies.
> 
> 墙内用户可以参考以下步骤安装前端依赖：
> 
> 1. 删除 `package-lock.json`;
> 2. 去掉 `package.json` 中的 `image-webpack-loader`，使用 `npm` 安装依赖
> 3. 最后使用 `cnpm install image-webpack-loader`
> 
> 参考文章：https://my.oschina.net/itlangz/blog/1921136

是否应该考虑其他的包呢，不用这个包了，现在一启动就报错；

**Comment by liuxsen** [comment]
> 是否考虑解决下呢，
> 
> > Still can't fully use `cnpm` to install dependencies, it will cause `core-js` import circularly, please use npm to install dependencies.
> > 墙内用户可以参考以下步骤安装前端依赖：
> > 
> > 1. 删除 `package-lock.json`;
> > 2. 去掉 `package.json` 中的 `image-webpack-loader`，使用 `npm` 安装依赖
> > 3. 最后使用 `cnpm install image-webpack-loader`
> > 
> > 参考文章：https://my.oschina.net/itlangz/blog/1921136

嗯~，楼上解决方式有时候可以，有时候不可以，建议直接使用yarn，亲测可用
