### ISSUE TITLE
How to set the style or theme of the widget in the display？

### ISSUE THREAD

**Issue by zxhhappy** [edp963/davinci#1835]
Is it possible to set the theme of large screen or dashboard to change the style  in Davinci conveniently?
![深色大屏2](https://user-images.githubusercontent.com/3803834/86503623-7caa1000-bde2-11ea-8c60-e83846967085.png)
![深色大屏3](https://user-images.githubusercontent.com/3803834/86503627-829ff100-bde2-11ea-9d02-7faafb63fed6.png)

**Comment by scottsut** [comment]
Just set it in widget edit page.

**Comment by ziveen** [comment]
> Just set it in widget edit page.

The only way to support dark theme is editing the theme json?
