### ISSUE TITLE
query variable in share dashboard url 

### ISSUE THREAD

**Issue by zxhhappy** [edp963/davinci#1842]
What is the query parameter format in the URL of the shared dashboard? Do you need to do some coding in advance?
Please help to see why the following doesn't work

**Comment by zxhhappy** [comment]
**The query parameter (string type) with the name "username" is configured in view, and the associated field is also called "username"**
![image](https://user-images.githubusercontent.com/3803834/87050665-23523e80-c231-11ea-926e-e2b08adadfa7.png)

I generate sharing links of "common share" mode , and add "& username = TDDD" at the end of the URL. There will be no data in the dashboard expected, but complete data still appears

http://localhost:5002/share.html#/share/dashboard?shareInfo=DA1C3E7DAF7EC46FDC39861F361C78B7517FC6CEF4F1ED425FFF75A2CB7527D3ABD4F0725AF12462EE9485E57D52340107FEFEB3511C3A6D5EF6C550BEFEFC5A368F8C3337A4A4695B695C320C338BDA37A6DCD28BA34B7E5B3CD279A38726D51456B5FBCAF282D3E95BEF815198FB0457D766BE0A014D7BA9FC7D09FBA3FD4299A61F03801710C5C8947648890D7B570B0327AE05BA929C204CFC5DA9816ED57BE7E16DF920ED19801182ED33581762E4C2A7333F4867D422ABF35EF9F395A25C635B6129E8FF18C8CFA6BD80E0896E1438B4D1BA9E222AF0F7B92F31F5CEAB97BB9BACDC5E7927ED7815FB74CEF214F417A9D41349B1515C610C12840C279C&type=dashboard&username=tddd

So I need to understand the syntax of query parameters in shared URLs，can you help me?

**Comment by scottsut** [comment]
Share page parameters interact with global controllers rather than directly with query variables, [see the documents](https://edp963.github.io/davinci/docs/zh/2.4-dashboard#263-%E5%88%86%E4%BA%AB%E9%A1%B5%E5%8F%82%E6%95%B0%E4%BC%A0%E9%80%92).

**Comment by zxhhappy** [comment]
Thank you so much for your timely and effective reply!

Your method can be realized by the controller. But there is a drawback: the controller can be seen by users themselves (I don't want to be seen by users).

I hope to get the goal: the business system can do self registration to add users, users submit their own information, and then in the report can only see their own information, can not see other people's information.

Is it possible to hide this controller (if developed, where the code is), or is there any other way?


In addition, I see the help document，does this work?
https://www.bookstack.cn/read/davinci/e40d6267e402f232.md
![image](https://user-images.githubusercontent.com/3803834/87103054-7efae700-c286-11ea-88e5-a2055b41add4.png)

**Comment by scottsut** [comment]
Control visibility feature is in progress #1703 .

The screenshot above is the document of 0.2 version, this feature has been replaced by global control parameters passing in the 0.3 version.

**Comment by zxhhappy** [comment]
Thanks！
In which release Control visibility feature  is available？ I can‘t find it in maste.

**Comment by scottsut** [comment]
In progress, hasn't been released yet.

**Comment by zxhhappy** [comment]
Thanks! I hope to use this feature as soon as possible.
