### ISSUE TITLE
We have too many items, we need to add a search box in the widget and view interface

### ISSUE THREAD

**Issue by silegon** [edp963/davinci#1861]
We have too many items, we need to add a search box in the widget and view interface, otherwise it will be too difficult to find.
![widget](https://user-images.githubusercontent.com/635500/88126263-c3ca3a80-cc03-11ea-9018-e3549384e5ef.png)

**Comment by scottsut** [comment]
![image](https://user-images.githubusercontent.com/4098913/88128725-23771480-cc09-11ea-9f36-63b3960629c3.png)

Already supported.

**Comment by silegon** [comment]
> ![image](https://user-images.githubusercontent.com/4098913/88128725-23771480-cc09-11ea-9f36-63b3960629c3.png)
> 
> Already supported.

Thanks！
