### ISSUE TITLE
In the current Version of Davinci Beta8, there is a problem that if only one refresh mode is timed refresh, all components will refresh.

### ISSUE THREAD

**Issue by chenweizhaoup** [edp963/davinci#1865]
In the current Version of Davinci Beta8, there is a problem that if only one refresh mode is timed refresh, all components will refresh.
A video was recorded to illustrate this.
[illustrateVideo.zip](https://github.com/edp963/davinci/files/4963670/illustrateVideo.zip)

**Comment by scottsut** [comment]
Doesn't appear in beta.9 release, please upgrade.

**Comment by chenweizhaoup** [comment]
Beta9 works. Thanks
