### ISSUE TITLE
Will Davinci consider encrypting database passwords stored in the Source table in the future ? 

### ISSUE THREAD

**Issue by chenweizhaoup** [edp963/davinci#1866]
Will Davinci consider encrypting database passwords stored in the Source table in the future ?
Since my usage scenario has a requirement to prohibit the storage of passwords in database tables, we think this is a reasonable requirement.
If Davinci does not have a plan, whether we can set up branch development and then merge to master through pull Request.
The reference picture is as follows?
![pic](https://user-images.githubusercontent.com/17274752/88251782-7cfd4300-ccde-11ea-883e-418969d6b66b.png)

**Comment by chenweizhaoup** [comment]
We have optimized this function and submitted a pull request, please check
#1899
https://github.com/edp963/davinci/pull/1899
@scottsut

**Comment by chenweizhaoup** [comment]
Pull requests have been merged #1916 
Thanks @scottsut @xxxllluuu

**Comment by scottsut** [comment]
Thanks for your contribution! @chenweizhaoup
