### ISSUE TITLE
I clone  dev-0.3 branch's code and use cnpm to complie webapp directories, but get an older version front-end files

### ISSUE THREAD

**Issue by xiaodin1** [edp963/davinci#1873]
cnpm run build
cnpm run start
访问的是旧版本 http://localhost:5002/#/projects
![image](https://user-images.githubusercontent.com/5487977/88583891-6ca0eb80-d083-11ea-8994-4cda704440bf.png)
，是不是我的分支不对呢？我把你们发版编译好的davinci-ui代码拷过来就是对的了http://127.0.0.1:8080/#/projects 
![image](https://user-images.githubusercontent.com/5487977/88584396-213b0d00-d084-11ea-8e8b-c38641cb2576.png)

，请问下release的dev-0.3的前端是哪个版本的代码呢？

**Comment by scottsut** [comment]
Nothing seems wrong. Check out the [branch structure](https://github.com/edp963/davinci/blob/dev-0.3/CONTRIBUTING-CH.md#%E5%88%86%E6%94%AF%E7%BB%93%E6%9E%84).

**Comment by xiaodin1** [comment]
![image](https://user-images.githubusercontent.com/5487977/88612108-0638bf00-d0bd-11ea-8723-c5dfba481e80.png)
我的分支是这个dev-0.3，但是从这个分支编译出来的前端代码版本比下载就编译好的（davinci-ui目录）低呢？是不是这个分支下的前端代码版本低了呢？有什么办法校验吗？

**Comment by xiaodin1** [comment]
> Nothing seems wrong. Check out the [branch structure](https://github.com/edp963/davinci/blob/dev-0.3/CONTRIBUTING-CH.md#%E5%88%86%E6%94%AF%E7%BB%93%E6%9E%84).

![image](https://user-images.githubusercontent.com/5487977/88612368-a55db680-d0bd-11ea-904d-f4b7722c36bf.png)

我的分支是这个dev-0.3，但是从这个分支编译出来的前端代码版本比下载就编译好的（davinci-ui目录）低呢？是不是这个分支下的前端代码版本低了呢？有什么办法校验吗？

**Comment by xiaodin1** [comment]
i pull the master branch's webapp code overwrite the branch-0.3's webapp directory, it works. could you Update the code of the dev-0.3 branch's webapp code to make it consistent with the master branch's webapp code @scottsut

**Comment by scottsut** [comment]
Why do you think the front-end file compiled by `dev-0.3` branch should lag behind the `davinci-ui` folder? Your screenshots don’t seem to have any problems, `dev-0.3` branch really doesn't look the same because it's newer.

**Comment by xiaodin1** [comment]
i need to confirm with you again, I directly git clone down the code, the direct build generated code (webapp/build directory) 
![image](https://user-images.githubusercontent.com/5487977/88753886-f8a03980-d18f-11ea-9032-25ddafdb08e7.png)
and their own davinci-ui's 
![image](https://user-images.githubusercontent.com/5487977/88753903-048bfb80-d190-11ea-94cf-437089a9f28f.png)
code is different, which of these two is the latest? What I feel is that the davinci-ui and master branches are the same.Does that mean that the webapp code in the davinci-ui's code directory is not up-to-date. If you say that the dev-0.3 branch is new, I'll switch back to the 0.3 version.It's mainly because of the dev-0.3 code and the davinci-ui  (which you compiled in advance) is different

**Comment by xiaodin1** [comment]
According to what you said ![image](https://user-images.githubusercontent.com/5487977/88754563-9a745600-d191-11ea-9b9e-c7b79393aa33.png), this is the latest, so the code in the davinci-ui directory of dev-0.3 should also be compiled with the latest version, or delete it and let the user compile it by himself. Otherwise, the version problem will be tangled like me

**Comment by scottsut** [comment]
OK, we'll consider deleting it.

**Comment by xiaodin1** [comment]
OK~I close this issue
