### ISSUE TITLE
定时邮件截图堵塞在 wait.until(ExpectedConditions.or(ConditionOfSign, ConditionOfWidth, ConditionOfHeight));

### ISSUE THREAD

**Issue by wonderpan** [edp963/davinci#1879]
下载dev分支最新代码运行后验证定时邮件截图功能，使用的是PHANTOMJS。

发现线程阻塞在 wait.until(ExpectedConditions.or(ConditionOfSign, ConditionOfWidth, ConditionOfHeight));

通过打印访问的页面发现所获取到的页面并不是正确的分享页面，而是访问到了前端app目录下的index.html页面。

后面尝试在新版达芬奇上访问我部署的老版达芬奇的分享链接进行截图（该版达芬奇大概是5月初的版本），截图成功。两者的区别是前端路由的位置，老版的路由是放在shareToken前面，新版的路由是放在最末端，因此我将新版的路由调整到和老版一致，但在打开分享链接时，跳转到了用户登录页面，并且后端接收到的shareToken参数为null。

**Comment by wonderpan** [comment]
抱歉，这个场景有点复杂，英语有点差，所以用中文了

**Comment by scottsut** [comment]
The dev-0.3 branch currently doesn't support Phantomjs screenshots due to syntax problems, please use Chrome instead.

**Comment by wonderpan** [comment]
> The dev-0.3 branch currently doesn't support Phantomjs screenshots due to syntax problems, please use Chrome instead.

好的，谢谢
