### ISSUE TITLE
widget中，加入指标和维度，sql语法翻译错误

### ISSUE THREAD

**Issue by freedomme** [edp963/davinci#1881]
StatementCallback; bad SQL grammar [SELECT sum(`rvalue`) AS 'sum(rvalue)' FROM (select rname ,rvalue from sisanalyse5) T ]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "'sum(rvalue)'" 位置：26
在widget中，拖拽加入指标和维度 出现上面错误。因为做的view是正常查询出数据，是框架翻译问题？ 数据库是postgresql 11, davinci 是0.3版本，哪位能帮忙？

**Comment by scottsut** [comment]
Please refer to #688

**Comment by freedomme** [comment]
> Please refer to #688

ths

**Comment by freedomme** [comment]
已经解决

**Comment by JING0917** [comment]
> 已经解决
请问楼主，是通过什么方式解决了呢？我也遇到了这个问题
