### ISSUE TITLE
I am sorry, but I don't know How to Use Davinci?

### ISSUE THREAD

**Issue by yuanbwhub** [edp963/davinci#1884]
I could't browse The User manual that its url is https://edp963.github.io/davinci/,  I am sorry But How to use it ? I need your help ,thanks

**Comment by scottsut** [comment]
Looks like the documents site won't be able to access it since this week, you can access the markdown file in folder `/docs/_docs/zh/` directly instead.

**Comment by yuanbwhub** [comment]
> Looks like the documents site won't be able to access it since this week, you can access the markdown file in folder `/docs/_docs/zh/` directly instead.

thanks, I got it
