### ISSUE TITLE
Can't open the web of handbook:"https://edp963.github.io/davinci/"

### ISSUE THREAD

**Issue by DM-NUM** [edp963/davinci#1885]
Did it have any problem of web : "https://edp963.github.io/davinci/", get the error message of picture:
![image](https://user-images.githubusercontent.com/41332648/89748483-0e015600-daf6-11ea-9231-789e1ea5979c.png)

**Comment by scottsut** [comment]
Please refer to #1884

**Comment by DM-NUM** [comment]
> Please refer to #1884

Thank you very much!
