### ISSUE TITLE
In webapp, how can i set devServer headers ?

### ISSUE THREAD

**Issue by weishaodaren** [edp963/davinci#1890]
addDevMiddleware and webpack.dev both failed, want to fix Access-Control-Allow-Origin

**Comment by scottsut** [comment]
`webapp/server/config.json`

**Comment by weishaodaren** [comment]
`{
  "proxies": [{
    "target": "http://192.168.88.168:8080/",
    "enabled": true,
    "headers": {
      "Access-Control-Allow-Origin": "*"
    }
  }]
}
`
it doesn't work , also ' No 'Access-Control-Allow-Origin' header is present on the requested resource'

**Comment by scottsut** [comment]
No need to set `Access-Control-Allow-Origin` header when using http-proxy-middleware.

**Comment by weishaodaren** [comment]
Still failed, ....Sorry, if I wanna set Access-Control-Allow-Origin headers,  how to do it ?
Cause I need to put them in micro-frontend framwork, and they all need set `Access-Control-Allow-Origin": "*"`.
At present, webapp still thorw `' No 'Access-Control-Allow-Origin' header is present on the requested resource'`,

**Comment by ziveen** [comment]
> Still failed, ....Sorry, if I wanna set Access-Control-Allow-Origin headers, how to do it ?
> Cause I need to put them in micro-frontend framwork, and they all need set `Access-Control-Allow-Origin": "*"`.
> At present, webapp still thorw `' No 'Access-Control-Allow-Origin' header is present on the requested resource'`,

do you still remember how to resolve it?i got the same problem

**Comment by weishaodaren** [comment]
> > Still failed, ....Sorry, if I wanna set Access-Control-Allow-Origin headers, how to do it ?
> > Cause I need to put them in micro-frontend framwork, and they all need set `Access-Control-Allow-Origin": "*"`.
> > At present, webapp still thorw `' No 'Access-Control-Allow-Origin' header is present on the requested resource'`,
> 
> do you still remember how to resolve it?i got the same problem

本地你可以试试 Chrome Allow CORS 插件先解决
