### ISSUE TITLE
ListBuffer

### ISSUE THREAD

**Issue by suwensen** [edp963/davinci#1893]
![listBuffer7-93f9-c6a8cb9053a5](https://user-images.githubusercontent.com/15205366/90532395-c6d82c80-e1a9-11ea-84d7-b5f54d931623.png)

---- import com.sun.tools.javac.util.ListBuffer
SqlOperatorEnum/...
ListBuffer is scala function, i think.

**Comment by scottsut** [comment]
Refer to #1438

**Comment by suwensen** [comment]
must not use com.sun package.
