### ISSUE TITLE
热力图 Widget

### ISSUE THREAD

**Issue by giscafer** [edp963/davinci#1894]
有没有考虑新增widget支持 热力图 https://g2.antv.vision/zh/examples/heatmap/basic

**Comment by scottsut** [comment]
Maybe not, but we have a plan to allow users to easily add #1748.

**Comment by giscafer** [comment]
done by  myself
![image](https://user-images.githubusercontent.com/8676711/91028884-ac320780-e630-11ea-9910-35d6b9483783.png)
