### ISSUE TITLE
Fail to set dynamic columns name

### ISSUE THREAD

**Issue by DM-NUM** [edp963/davinci#1897]
dears, I had set a dynamic column name , e.g. column name "Default"  in the picture , it gets the values from the variable $dim$.... when I display in Dashboard , I input a value like "Hour" of variable $dim$, but the columns name "Default" didn't change , could anyone tell me what's the problem about it ?

![image](https://user-images.githubusercontent.com/41332648/90761618-3e2acf00-e316-11ea-9296-0f60b498461b.png)

![image](https://user-images.githubusercontent.com/41332648/90761938-c01af800-e316-11ea-9418-b324a2a8afe5.png)

**Comment by scottsut** [comment]
Please post your view sql and variable declaration screenshot.

**Comment by DM-NUM** [comment]
> Please post your view sql and variable declaration screenshot.

thanks for reply. I had solved this problem . By the way , I got this error because I use variable like "$columns1$" as columns name in SQL. When I change the column name , it could work.
