### ISSUE TITLE
One Issue on Global Controller

### ISSUE THREAD

**Issue by Mint6** [edp963/davinci#1908]
### Question Description:
At first, I selected some values in global controllers. The chart changed as below.
And then I clicked Full Screen button, the selected filters are cleared as the following picture 2.
### Hope to fix:
I think it should preserve the previous screening conditions when the chart is in full-screen view.
The users can select other screening conditions if they need.

Looking forward to your reply. Thanks a lot.

_picture 1_
![图片](https://user-images.githubusercontent.com/62235017/91112191-feb50780-e6b4-11ea-948c-f5d5012dc932.png)
_picture 2_
![图片](https://user-images.githubusercontent.com/62235017/91115028-d8df3100-e6bb-11ea-8fcc-2c4a564d318c.png)

**Comment by scottsut** [comment]
Already fixed in dev branch, will available in next release.
