### ISSUE TITLE
小细节优化改造

### ISSUE THREAD

**Issue by dongjunwen** [edp963/davinci#1918]
1.导出列表太多，没必要全部展示，是不是可以只展示一天或者定时删除都行 
2.报表全屏后，数据列表没有全屏展示，还是全屏前的尺寸，看看是不是能调整一下

**Comment by dongjunwen** [comment]
![问题1](https://user-images.githubusercontent.com/10876145/91923451-fc7d2980-ed02-11ea-85b2-ed5e1629e8c3.png)


![问题2](https://user-images.githubusercontent.com/10876145/91923448-fa1acf80-ed02-11ea-8ef0-a6a0bd02f973.png)

**Comment by scottsut** [comment]
1、目前展示近7天的下载数据；
2、开发版已修复，下个版本发布。
