### ISSUE TITLE
- Asynchronous Sessions clean-up phase starting NOW

### ISSUE THREAD

**Issue by Huwei1993** [edp963/davinci#1923]
SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
my programe is error ,how can i do ?
phantomjs log:
 {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"mac-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}

**Comment by scottsut** [comment]
We don't think this problem is caused by Davinci, the following link are for your infomation
https://github.com/ariya/phantomjs/issues/11526
