### ISSUE TITLE
get the error: "Exception in thread "Thread-35" java.lang.NullPointerException" in davinci-docker

### ISSUE THREAD

**Issue by DM-NUM** [edp963/davinci#1953]
I start davinci by docker, it can run successfully . But a few days, it got some error and I have to restart the docker . I don't know what the problem about it , can anyone help me ?  
ps: this is the error log, thanks!
![image](https://user-images.githubusercontent.com/41332648/93840265-6a918c80-fcc2-11ea-981f-e0c0b060e5c1.png)
[c1f00a1d4eaad4b6789e13778196cf451-rc-hk-davinci-logs (1).txt](https://github.com/edp963/davinci/files/5258982/c1f00a1d4eaad4b6789e13778196cf451-rc-hk-davinci-logs.1.txt)

**Comment by scottsut** [comment]
Please move this issue to [davinci-docker](https://github.com/edp963/davinci-docker) repo.

**Comment by DM-NUM** [comment]
> Please move this issue to [davinci-docker](https://github.com/edp963/davinci-docker) repo.

ok, thanks~
