### ISSUE TITLE
docker 本地编译运行，无法访问web

### ISSUE THREAD

**Issue by chaozhangpower** [edp963/davinci#1957]
![image](https://user-images.githubusercontent.com/21254276/94131405-73d05400-fe90-11ea-9a4e-3b953b0b597a.png)

**Comment by chaozhangpower** [comment]
编译命令mvn clean package

**Comment by chaozhangpower** [comment]
![image](https://user-images.githubusercontent.com/21254276/94131489-919db900-fe90-11ea-9a32-383193e65674.png)

**Comment by chaozhangpower** [comment]
FROM  alpine:3.9.5 AS build

ARG DAVINCI_ZIP

ADD $DAVINCI_ZIP /

ARG PHANTOMJS_BZ2=phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2

RUN mkdir -p /opt/phantomjs-2.1.1/phantomjs

ADD $PHANTOMJS_BZ2 /opt/phantomjs-2.1.1/phantomjs

RUN mkdir -p /opt/davinci && unzip $DAVINCI_ZIP -d /opt/davinci \
&& rm -rf $DAVINCI_ZIP \
&& cp -v /opt/davinci/config/application.yml.example /opt/davinci/config/application.yml

# 此dockerfile 用于在本地构建，提前把程序包及phantomjs下载到本地
ADD phantomjs /opt/phantomjs-2.1.1

ADD bin/docker-entrypoint.sh /opt/davinci/bin/docker-entrypoint.sh

ADD bin/docker-entrypoint.sh /opt/davinci/bin/docker-entrypoint.sh

ADD mssql-jdbc-6.4.0.jre8.jar /opt/davinci/lib/

ADD postgresql-42.2.16.jar /opt/davinci/lib/

RUN chmod +x /opt/davinci/bin/docker-entrypoint.sh \
&&  chmod +x /opt/phantomjs-2.1.1/phantomjs

#FROM  openjdk:8u242-jdk AS base
FROM selenium/standalone-chrome

LABEL MAINTAINER="edp_support@groups.163.com"

WORKDIR /opt/davinci

COPY --from=build /opt /opt

ENV OPENSSL_CONF=/etc/ssl/
ENV DAVINCI3_HOME  /opt/davinci
ENV PHANTOMJS_HOME /opt/phantomjs-2.1.1
ENV SCREENSHOT_PHANTOMJS_PATH=/opt/phantomjs-2.1.1/phantomjs
ENV SCREENSHOT_DEFAULT_BROWSER=CHROME
ENV SCREENSHOT_TIMEOUT_SECOND=30

ENV JAVA_OPTS "-agentlib:jdwp=transport=dt_socket,server=y,address=53733,suspend=y"

CMD ["./bin/start-server.sh"]

EXPOSE 8080

**Comment by chaozhangpower** [comment]
FROM  alpine:3.9.5 AS build

ARG DAVINCI_ZIP

ADD $DAVINCI_ZIP /

ARG PHANTOMJS_BZ2=phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2

RUN mkdir -p /opt/phantomjs-2.1.1/phantomjs

ADD $PHANTOMJS_BZ2 /opt/phantomjs-2.1.1/phantomjs

RUN mkdir -p /opt/davinci && unzip $DAVINCI_ZIP -d /opt/davinci \
&& rm -rf $DAVINCI_ZIP \
&& cp -v /opt/davinci/config/application.yml.example /opt/davinci/config/application.yml

ADD phantomjs /opt/phantomjs-2.1.1

ADD bin/docker-entrypoint.sh /opt/davinci/bin/docker-entrypoint.sh

ADD bin/docker-entrypoint.sh /opt/davinci/bin/docker-entrypoint.sh

ADD mssql-jdbc-6.4.0.jre8.jar /opt/davinci/lib/

ADD postgresql-42.2.16.jar /opt/davinci/lib/

RUN chmod +x /opt/davinci/bin/docker-entrypoint.sh \
&&  chmod +x /opt/phantomjs-2.1.1/phantomjs

FROM selenium/standalone-chrome

LABEL MAINTAINER="edp_support@groups.163.com"

WORKDIR /opt/davinci

COPY --from=build /opt /opt

ENV OPENSSL_CONF=/etc/ssl/
ENV DAVINCI3_HOME  /opt/davinci
ENV PHANTOMJS_HOME /opt/phantomjs-2.1.1
ENV SCREENSHOT_PHANTOMJS_PATH=/opt/phantomjs-2.1.1/phantomjs
ENV SCREENSHOT_DEFAULT_BROWSER=CHROME
ENV SCREENSHOT_TIMEOUT_SECOND=30

ENV JAVA_OPTS "-agentlib:jdwp=transport=dt_socket,server=y,address=53733,suspend=y"

CMD ["./bin/start-server.sh"]

EXPOSE 8080

**Comment by chaozhangpower** [comment]
端口映射也没有问题。
启动命令参照如下：
```
docker run -p 58081:8080 -e SPRING_DATASOURCE_URL="jdbc:mysql://yourmysqlserver:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true" \
-e SPRING_DATASOURCE_USERNAME="root" -e SPRING_DATASOURCE_PASSWORD="pwd" \
-e SPRING_MAIL_HOST="smtp.163.com"  -e SPRING_MAIL_PORT="465" -e SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE="true" \
-e SPRING_MAIL_USERNAME="xxxxxx@163.com"  -e SPRING_MAIL_PASSWORD="xxxxxxx" \
-e SPRING_MAIL_NICKNAME="davinci_sys" \
edp963/davinci:v0.3.0-beta.9
```

**Comment by scottsut** [comment]
Please move this issue to [davinci-docker](https://github.com/edp963/davinci-docker) repo.

**Comment by chaozhangpower** [comment]
close
