### ISSUE TITLE
如何配置取前十条数据的效果

### ISSUE THREAD

**Issue by zhang382847657** [edp963/davinci#1964]
我有一个表格，只想展示点击量排名前10的网站，如何在Widget List中配置这样的情况？

**Comment by xxxllluuu** [comment]
You can use SQL limits and order by

**Comment by zhang382847657** [comment]
如果不用SQL来配置，而是直接在widget list中配置可以吗？
举个例子，我想显示某类型下电影排名前十的影片有哪些，电影类型是在仪表盘中配的全局控制器，如果用户选择了科幻类，则表单显示科幻类下评分排名前十的电影，如果用户什么都不选择，则显示所有电影评分排名前十的电影。
因为你不知道用户是按照什么类型来选择的，所以无法在SQL中直接写limit

**Comment by scottsut** [comment]
Will be supported in next release.
