### ISSUE TITLE
Display能否像Dashboard一样支持Widget之间的联动关系和全局控制器设置

### ISSUE THREAD

**Issue by wolfwood1983** [edp963/davinci#1967]
目前项目中的需求针对大屏（Display）界面中的图表组件要有交互功能，而看板（Dashboard）中的样式又相对单一，比如不能调整背景颜色或背景图片，以及不能随意添加标签文字等等，所以提出大屏（Display）能否像看板（Dashboard）一样支持Widget之间的联动关系和全局控制器设置？

另外还有一个需求，就是在Display和Dashboard中，能否考虑增加tab分页组件，将多个Widget添加进去，通过tab分页进行查看？

**Comment by scottsut** [comment]
Related to #1734 #1745
