### ISSUE TITLE
display slide widget is not found

### ISSUE THREAD

**Issue by ghostman-git** [edp963/davinci#1968]
docker  
v0.3.0-beta.9

![image](https://user-images.githubusercontent.com/13376074/95534287-f8d27600-0a17-11eb-8ec0-a659b9146e88.png)

**Comment by oooooobtf** [comment]
![image](https://user-images.githubusercontent.com/38756055/96950875-e2e7a980-151d-11eb-9ac6-3348426204d9.png)
my branch is master，when I add background images to auxiliary graphics，it's will report an error as ‘dispaly slide widget is not sub widget‘’

**Comment by oooooobtf** [comment]
@scottsut please！！thx！

**Comment by scottsut** [comment]
Which repo are you using? davinci-docker or davinci?

**Comment by oooooobtf** [comment]
> Which repo are you using? davinci-docker or davinci?

davinci

**Comment by ghostman-git** [comment]
> davinci-docker

**Comment by ghostman-git** [comment]
> Which repo are you using? davinci-docker or davinci?

davinci-docker

**Comment by scottsut** [comment]
Please upgrade to 0.3.0-rc version, problem will be solved.
