### ISSUE TITLE
分享页面的钻取功能不好使

### ISSUE THREAD

**Issue by 18332908201** [edp963/davinci#1971]
在分享页面使用钻取功能，F12查看出现Cannot read property '23' of undefined

**Comment by scottsut** [comment]
麻烦贴出具体图表和错误信息截图

**Comment by 18332908201** [comment]
![ab1861a469ec3073b06349bc0c9939a](https://user-images.githubusercontent.com/48019036/96091684-7dcbfc80-0efc-11eb-9a14-27a79b674dcb.png)
![08063fb6650a1ae8f82acce185a4bf1](https://user-images.githubusercontent.com/48019036/96091687-7efd2980-0efc-11eb-9be6-da59dc8400ee.png)
柱状图和饼状图都不行，其他的应该也不行 没有试，这次截图的是不一样的组件，所以出现的错误的数值不一样

**Comment by 18332908201** [comment]
> 麻烦贴出具体图表和错误信息截图

柱状图和饼状图都不行，其他的应该也不行没有试，这次截图的是不一样的组件，所以出现的错误的数值不一样
![08063fb6650a1ae8f82acce185a4bf1](https://user-images.githubusercontent.com/48019036/96106627-ff785600-0f0d-11eb-9cf2-46d53656f637.png)
![ab1861a469ec3073b06349bc0c9939a](https://user-images.githubusercontent.com/48019036/96106630-00a98300-0f0e-11eb-80eb-f5fed20573d0.png)

**Comment by ruanhan** [comment]
It has been fixed in the dev-0.3 branch.

**Comment by 18332908201** [comment]
> It has been fixed in the dev-0.3 branch.

我用的就是dev-0.3 branch，还是不行啊

**Comment by 18332908201** [comment]
> > It has been fixed in the dev-0.3 branch.
> 
> 我用的就是dev-0.3 branch，还是不行啊

这个是在下个dev-0.3 branch更新，还是已经在dev-0.3 branch里了，我现在是dev-0.3 branch的最新代码还是出现这个问题
