### ISSUE TITLE
分享页面，组件全屏展示错乱

### ISSUE THREAD

**Issue by 18332908201** [edp963/davinci#1972]
打开分享页面，第一次点击组件全屏是正常的，后边在全屏页面切换其他的组件，会出现柱状图累加错乱，点击到最后一个的时候，就全乱套了
![4](https://user-images.githubusercontent.com/48019036/96092688-ccc66180-0efd-11eb-8474-4d2aca4ff157.png)
![3](https://user-images.githubusercontent.com/48019036/96092693-cdf78e80-0efd-11eb-8f4a-da44437d8fbc.png)
![2](https://user-images.githubusercontent.com/48019036/96092697-cf28bb80-0efd-11eb-8e74-a5960566faf7.png)
![1](https://user-images.githubusercontent.com/48019036/96092699-cfc15200-0efd-11eb-81f5-2ab40f21c1d5.png)

**Comment by 18332908201** [comment]
有时候出现，有时候不出现

**Comment by scottsut** [comment]
开发版已修复，下个版本会发布.
