### ISSUE TITLE
Why always get errors “Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory”

### ISSUE THREAD

**Issue by guoLucky** [edp963/davinci#1976]

**Comment by scottsut** [comment]
Not a issue about Davinci.

**Comment by scottsut** [comment]
https://segmentfault.com/a/1190000010437948
https://www.cnblogs.com/ybixian/p/11470659.html
https://blog.csdn.net/u012149969/article/details/104808488
FYI.
