### ISSUE TITLE
dev0.3，$ is not a function from core.js

### ISSUE THREAD

**Issue by oooooobtf** [edp963/davinci#1980]
![image](https://user-images.githubusercontent.com/38756055/96951348-da43a300-151e-11eb-9a62-16c62fdeb81d.png)
![image](https://user-images.githubusercontent.com/38756055/96951604-6bb31500-151f-11eb-9a42-1c6ee3b393dc.png)
cnpm install finished， there is an error on web application，maybe it's a compilation problem，please help me！ @scottsut

**Comment by oooooobtf** [comment]
使用master版本装完启动没有这个问题， 我克隆的dev0.3分支前端成功装完依赖启动会报错"$ is not a function"！！感觉是哪里编译出了问题

**Comment by scottsut** [comment]
Related to #1826
