### ISSUE TITLE
The problem about filtering out SQL comments in hive and impala. Hive和impala数据库，SQL注释部分被过滤的问题

### ISSUE THREAD

**Issue by ken-alx** [edp963/davinci#1983]
使用平台连接hive或impala数据库时，在SQL中加入注释命令，执行时会被过滤掉。 但是目前连接的平台神策，是需要该注释的，就会导致找不到对应的表数据
![image](https://user-images.githubusercontent.com/19256972/97138488-49c1c880-1793-11eb-81d9-97eef2e5acbe.png)

**Comment by xxxllluuu** [comment]
0.4 will be enhanced
