### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by jinjilynn** [edp963/davinci#1985]
![image](https://user-images.githubusercontent.com/12596042/97248524-f2783280-183c-11eb-8240-89e619df7119.png)

**Comment by jinjilynn** [comment]
In addition, there are a bunch of ts errors

**Comment by scottsut** [comment]
`image-webpack-loader` was not successfully installed. Consider the last comment in #1826

**Comment by jinjilynn** [comment]
image-webpack-loader was  installed particularly successfully!!I solved this issue
