### ISSUE TITLE
[server+ui]上传csv支持 == sen,han

### ISSUE THREAD

**Issue by fumiwork** [edp963/davinci#2]

**Comment by sunsence** [comment]
暂时不支持cache。选择用H2加载csv，删除表策略调研h2的配置

**Comment by fumiwork** [comment]
。用户在上传页面指定conn url，db，table，key，index，user，pwd，和mode（replace／append）

**Comment by fumiwork** [comment]
。上传csv会根据用户指定的conn url写入库

**Comment by fumiwork** [comment]
。下载csv时，type放在第二行
