### ISSUE TITLE
US004 Display 基础功能开发

### ISSUE THREAD

**Issue by scottsut** [edp963/davinci#201]
#### 基础功能
 - 新建、删除 Display
 - 编辑 Display
    - 画布配置
      - 当没有画布元素被选中时，右侧默认为画布配置表单，可对画布属性进行配置
    - 画布 zoom-in zoom-out
      - 通过底部栏 slider 对画布进行 zoom 操作
    - 画布元素新增
      - 点击顶部栏的 widgets 按钮弹出 widget列表， 从列表中选择 widget 到画布中
      - 点击顶部栏的“辅助图形”按钮弹出辅助图形列表， 从列表中选择辅助图形到画布中
    - 画布元素选择
      - 使用鼠标点选画布元素为单选
      - 按住 command(control) 键使用鼠标点选画布元素为多选
      - 可以通过左侧画布元素列表来选择画布元素，同样可以按住 command(control) 键多选
    - 画布元素配置
      - 选中单个画布元素后，右侧表单项为被选中元素的配置项，可以手动修改配置项
      - 可以通过在画布中自由拖拽元素来改变配置项里的 x、y、width、height 值
      - 选择多个画布元素时，右侧表单项暂时置空
    - 画布元素删除
      - 选中画布里的 widget，点击顶部栏的“删除”按钮，或是键盘的 delete(backspance) 键进行删除
    - 画布元素复制、粘贴
      - 选中需要复制的画布元素后，点击顶部栏的“复制”按钮，或是按 command(control) + c 键进行复制操作；点击顶部栏的“粘贴”按钮，或是按 command(control) + v 键进行粘贴操作
    - 画布元素层级控制
      - 通过左侧画布元素列表上方的按钮组来调节单个或一组元素的层级

#### 配置项说明
  - 配置项修改后立即生效
  - 画布配置项
    - 尺寸
    - 缩放方式
    - 栅格间距
    - 背景颜色
    - 背景图
    - 截取封面
  - 画布元素通用配置项
    - x
    - y
    - width
    - height
    - 边框色
    - 边框样式
    - 边框宽度
    - 边框圆角宽度
  - 辅助元素 文字 配置项
    - 字体
    - 字色
    - 文字大小
    - 对齐方式
    - 加粗/斜体/下划线
    - 背景色
    - 文字行高
    - 上边距
    - 下边距
    - 左边距
    - 右边距
  - 辅助元素 自定义背景块 配置项
    - 背景色
    - 背景图
    - 自动调节/拉伸
    - 重复/不重复

**Comment by scottsut** [comment]
设计草图
![display](https://user-images.githubusercontent.com/4098913/39742086-c5977e5a-52ce-11e8-93c4-3ee9c08d5a0c.png)

**Comment by AndyFong** [comment]
@fumiwork
