### ISSUE TITLE
点击大屏预览，出现死循环

### ISSUE THREAD

**Issue by guoLucky** [edp963/davinci#2032]
下载的dev-0.3版本，点击大屏预览报错
![JL1MZB_V38D PD6D`J`AGYL](https://user-images.githubusercontent.com/48083162/98528059-be7a2400-22b6-11eb-8826-a68ddeb6e082.png)

**Comment by old-zsh** [comment]
@guoLucky sorry, no reproduce locally, can you provide detailed steps to reproduce ?

**Comment by guoLucky** [comment]
就是编辑display,
![B}UEVLLQQP{Q12AA@AJSY 3](https://user-images.githubusercontent.com/48083162/98659993-bb973600-237f-11eb-9c24-abecd0413700.png) 
点击预览，跳转到预览页面就出现这个报错了。reveal.js 关于这个js的使用注释掉，可以正常打开页面，加上就会出现上面的报错。还有这里
![$E_IYGC59I_~$ZGH)ZKQ T4](https://user-images.githubusercontent.com/48083162/98660690-8c34f900-2380-11eb-9f58-1b8de6ea4dd4.png)
![TO 389}2S}XD5M03B)JWU7F](https://user-images.githubusercontent.com/48083162/98660742-9d7e0580-2380-11eb-800c-91055a621527.png)
似乎没有引入到这个zoom.js   不太明白这里是为什么，求助
