### ISSUE TITLE
Dashboard download fail

### ISSUE THREAD

**Issue by xiaoxiao-ass** [edp963/davinci#2084]
![image](https://user-images.githubusercontent.com/47917178/101328021-7137a500-38aa-11eb-9fe5-c213992ee1ea.png)
![image](https://user-images.githubusercontent.com/47917178/101329279-24ed6480-38ac-11eb-972f-996282f86272.png)
![image](https://user-images.githubusercontent.com/47917178/101329307-2f0f6300-38ac-11eb-938b-bd966f744ca1.png)

**Comment by scottsut** [comment]
Check out the system logs.

**Comment by xiaoxiao-ass** [comment]
Thank you. It's settled

**Comment by xiaoxiao-ass** [comment]
Stringtemplate Splicing SQL error
