### ISSUE TITLE
功能需求：图表的权限问题

### ISSUE THREAD

**Issue by yuhao001** [edp963/davinci#2088]
对每个图表可以进行权限设置，使得当前登录的角色在对看板或大屏添
加图表时只展示该角色有权限看到的图表而不是全部的图表信息。
![图表权限](https://user-images.githubusercontent.com/50822655/102063548-229d8400-3e31-11eb-887f-b2d3ffd565d4.png)

**Comment by scottsut** [comment]
暂无计划实现 widget 粒度展示权限。
