### ISSUE TITLE
Keyboard shortcut Bug

### ISSUE THREAD

**Issue by llf007** [edp963/davinci#2100]
Display editing
Cmd + z or Shift + Cmd + z、 Ctrl + z
Cmd + y、Ctrl + y
Keyboard shortcut can not be used

But Ctrl+C, Ctrl+V are normal

**Comment by scottsut** [comment]
`Cmd + z` `Shift + Cmd + z` `Ctrl + z` `Cmd + y` `Ctrl + y` are not available yet.

https://edp963.github.io/davinci/docs/zh/2.5-display#224-%E6%93%8D%E4%BD%9C%E9%94%AE
