### ISSUE TITLE
透视驱动中日期筛选配置中，视图数据更新错误

### ISSUE THREAD

**Issue by yuhao001** [edp963/davinci#2102]
图表驱动--数据----筛选（时间-----最近7天）在看板会默认生成8条数据。新增数据后，会自动把新一天的数据叠加到8条数据后面，而不是从当前日期开始的最近7天的数据显示。
![时间筛选错误截图](https://user-images.githubusercontent.com/50822655/103271616-ae004300-49f5-11eb-89e4-969b13f1e016.png)

**Comment by scottsut** [comment]
Duplicate of #2103
