### ISSUE TITLE
透视驱动中日期筛选（本周起）配置中，视图数据更新错误

### ISSUE THREAD

**Issue by yuhao001** [edp963/davinci#2103]
图表驱动---->数据---->筛选（时间----->本周起）新增超过一周的数据后，会自动把新一天的数据叠加到旧数据后面，而不是按照从当前日期所在的周的数据显示。
![时间筛选（本周起）错误截图](https://user-images.githubusercontent.com/50822655/103279915-fde90500-4a09-11eb-8505-fefda85b3e16.png)

**Comment by scottsut** [comment]
Related to #1478
