### ISSUE TITLE
Davinci有单点登陆案例吗

### ISSUE THREAD

**Issue by ThounderStruck** [edp963/davinci#2134]
目前Davinci报表共享权限校验都是通过手动输入这种被动式的校验，在集成到第三方系统上时，不太方便，是否可以通过 jwt 的 token 验证实现主动式权限校验，能提供相关案例吗

**Comment by scottsut** [comment]
目前没有案例，如果有开发能力可以二次开发支持，通过调用登录接口获取 jwt token 写入到 localStorage 中。

**Comment by ThounderStruck** [comment]
> 目前没有案例，如果有开发能力可以二次开发支持，通过调用登录接口获取 jwt token 写入到 localStorage 中。

可否提供详细的开发文档及代码入口，谢谢！！！

**Comment by dyhyao6** [comment]
顶一下

**Comment by cabbage89** [comment]
CAS+davinci+ 企业微信扫码  已经用了三年 ,没有一点问题
