### ISSUE TITLE
impala数据源报表分页有问题

### ISSUE THREAD

**Issue by ThounderStruck** [edp963/davinci#2141]
![image](https://user-images.githubusercontent.com/33996112/106689029-421f8480-660a-11eb-8c1c-72e3706357ae.png)
impala数据源报表驱动中的表格分页报错，希望尽快解决

**Comment by ThounderStruck** [comment]
通过impala查kudu数仓，分页显示异常

**Comment by scottsut** [comment]
这个0-20是你们自己做的限制吧？

**Comment by ThounderStruck** [comment]
> 这个0-20是你们自己做的限制吧？

不是，系统自带分页，默认每页20

**Comment by scottsut** [comment]
1. 编辑器左下方的 `500` 改为 `20` 来适应你们的使用需求；
2. 我不认为这是 Davinci 的问题，我们无法预计到各类用户数据源做出的种种限制。

**Comment by ThounderStruck** [comment]
> 1. 编辑器左下方的 `500` 改为 `20` 来适应你们的使用需求；
> 2. 我不认为这是 Davinci 的问题，我们无法预计到各类用户数据源做出的种种限制。

截图中的sql我在数据视图中是正常执行的，没有问题，在制作可视化组件（图标驱动：表格）显示异常，impala的分页与其他数据源不同，不知是否兼容过
