### ISSUE TITLE
请问davinci可以通过源码启动吗？（就是直接在idea里运行DavinciServerApplication)

### ISSUE THREAD

**Issue by jevislee** [edp963/davinci#2146]
我看文档里的安装说明是通过Release包部署启动，通过源码启动有教程文档吗？

**Comment by xxxllluuu** [comment]
抱歉，这块没有文档。你可以参考我的run/debug配置。
![截屏2021-02-09 下午4 25 50](https://user-images.githubusercontent.com/11717369/107336504-23caf480-6af4-11eb-83ba-7612846274f0.png)。
Working Dirctory：davinci打包后的部署目录，你可以自己打包，或者直接使用release包。
ENVironment variables：配置一个DAVINCI3_HOME环境变量，值与“Working Dirctory”保持一致
davinci使用的配置文件，比如config/application.yml，正常配置即可
