### ISSUE TITLE
kylin  union all 两个cube的sql top10

### ISSUE THREAD

**Issue by san-lj** [edp963/davinci#2147]
我的目的是取top10的数据

没写显示数量的情况下：![1612778504(1)](https://user-images.githubusercontent.com/33336632/107204705-f1f45800-6a37-11eb-8d63-06652e631f8d.jpg)
写显示数量的情况下：
![1612778549(1)](https://user-images.githubusercontent.com/33336632/107204706-f3258500-6a37-11eb-9c14-028eace245bc.jpg)

写显示数量的情况只会展示一个cube的结果，另一个cube的交易量没有算进来，

而且我试了好几种方式：
如在view直接sum两个cube的count,结果查询结果里显示的就不对，那widget不填显示数量情况下值又是对的。
![image](https://user-images.githubusercontent.com/33336632/107205053-60391a80-6a38-11eb-9755-62c2ee8fb8cc.png)
kylin里执行同样的sql:
![image](https://user-images.githubusercontent.com/33336632/107301472-89988b80-6ab6-11eb-8d12-4c94cb926c46.png)

**Comment by scottsut** [comment]
你开启一下sql日志吧，把这几种情况下最终执行的sql语句发出来看看

**Comment by san-lj** [comment]
> 你开启一下sql日志吧，把这几种情况下最终执行的sql语句发出来看看
![image](https://user-images.githubusercontent.com/33336632/107339398-9d181680-6af7-11eb-9fd5-b4dacd8ba1e0.png)
日志文件都是空的，我接触davinci就两天，官方文档，没看到还有其他地方能开启日志

**Comment by scottsut** [comment]
在 `application.yml` 中

```yaml
source:
  enable-query-log: true
```

改完后重启服务，日志会存储到 `logs/user/sql` 路径下

**Comment by san-lj** [comment]
我今天有空，看了一下其他的issue ,看了2142，然后尝试了一下，就是展示数据量的问题：
![image](https://user-images.githubusercontent.com/33336632/107453062-39d4c580-6b85-11eb-88a2-e553da7cd7c3.png)
![image](https://user-images.githubusercontent.com/33336632/107455017-0b58e980-6b89-11eb-8fe2-6377d1f5af6a.png)
![image](https://user-images.githubusercontent.com/33336632/107455369-b10c5880-6b89-11eb-8f24-19a78c61f9a8.png)

   我想问一下你们的展示数据量到底是控制什么的数据量，我最初的理解是最终查询结果的，但是现在看起来视乎只要加了小于某个值(个人尝试后觉得是两个cube union all后的总数据量：3894+3878)的展示数量，显示的就会不对（会缺少部分数据量的值，导致值减小）。
   我没使用源码，所有你如果想复现，可以产生复制一个表结构和内容，然后union all原表和复制的,然后展示数据量取小于总union 两头的查询结果集总量的值，应该就能发现部分结果集的某些值没有加进了。
下图是我放到了一定展示数量，但没放到最大。博物馆的值确实也增加了一点，但不是全部。当然也有可能某些维度对应的数量正确，但这种情况只有这个维度的的再union all所有结果集刚好再你的展示数量范围内
![image](https://user-images.githubusercontent.com/33336632/107456756-bcf91a00-6b8b-11eb-9f7f-34a9e5b52839.png)
![image](https://user-images.githubusercontent.com/33336632/107458697-8d4c1100-6b8f-11eb-8192-639168adfb19.png)

**Comment by san-lj** [comment]
你的sql:
![image](https://user-images.githubusercontent.com/33336632/107459037-3e52ab80-6b90-11eb-83c9-58f6a06f89e5.png)
![image](https://user-images.githubusercontent.com/33336632/107459119-75c15800-6b90-11eb-8f3a-11052432ee0d.png)
![image](https://user-images.githubusercontent.com/33336632/107459325-e7010b00-6b90-11eb-8295-57d71625e260.png)
sql看起来没有问题，到kylin这部也是没问题的，下图是无展示数量的kylin的日志，
![image](https://user-images.githubusercontent.com/33336632/107459390-0d26ab00-6b91-11eb-8d61-0d8d5eda7a3e.png)
有展示数量的kylin日志
![image](https://user-images.githubusercontent.com/33336632/107460098-735ffd80-6b92-11eb-89ab-157771325798.png)

**Comment by scottsut** [comment]
我开始以为是由于生成的sql语句不同导致的查询结果差异，后来看你截图发现不是这样。我确认了下这个事，首先“展示数据量”是控制的最终查询结果，通过 `jdbcTemplate.setMaxRows`来进行控制

![image](https://user-images.githubusercontent.com/4098913/107462166-765ced00-6b96-11eb-9399-b8dcc2118cad.png)

然后我简单测试了一下 mysql 中的 union 情况，在设或不设展示数据量的情况下，结果并没有差异：

<img width="758" alt="c" src="https://user-images.githubusercontent.com/4098913/107462270-b623d480-6b96-11eb-92f1-9e05414fcc53.png">
<img width="807" alt="b" src="https://user-images.githubusercontent.com/4098913/107462287-bd4ae280-6b96-11eb-8775-4bce898178b7.png">
<img width="802" alt="a" src="https://user-images.githubusercontent.com/4098913/107462288-bf14a600-6b96-11eb-8404-64033c9fba4a.png">

所以我认为这或许是 kylin 的 jdbc 驱动实现在 setMaxRows 这个问题上比较独特？毕竟我们没有对所有的 jdbc 数据源做特殊适配。

另外在 kylin 官网找到一些信息供你参考 http://kylin.apache.org/docs/release_notes.html

![image](https://user-images.githubusercontent.com/4098913/107462581-5d087080-6b97-11eb-9657-d5ea5a16a175.png)

**Comment by san-lj** [comment]
行吧，这个问题我提供其他方式解决。
功能建议，1、是否可加个union不同的widget的的结果
2、是否可以在现在的基础上，加一个limit的功能（如加个输入框，值是执行sql时自动添加limit的具体值），这样对所有的 jdbc 数据源跟容易适配。
