### ISSUE TITLE
npm install / yarn 报错

### ISSUE THREAD

**Issue by longyongsheng** [edp963/davinci#2151]
error E:\Project\davinci-dev-0.3\webapp\node_modules\gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: E:\Project\davinci-dev-0.3\webapp\node_modules\gifsicle
Output:
‼ read ECONNRESET
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by scottsut** [comment]
`image-webpack-loader` was not successfully installed. Consider the last comment in #1826
