### ISSUE TITLE
where条件中带 中文字符 结果无法正常匹配

### ISSUE THREAD

**Issue by wanyang-dev** [edp963/davinci#2167]
where  qual.register_province_name!='1'
-- and qual.register_province_name='云南省'
库中存在 云南省 数据行，但是加上此条件之后结果为空

**Comment by scottsut** [comment]
开启sql日志，把日志中的sql拿到客户端执行，追溯一下原因

**Comment by wanyang-dev** [comment]
已解决，数据库 character_set_server=latin1与url中是utf8，不一致造成的
