### ISSUE TITLE
最新的版本，启动不起来啊，大佬帮忙看看吧，最新版本代码：dev-0.3

### ISSUE THREAD

**Issue by zhanglinthree** [edp963/davinci#2196]
![image](https://user-images.githubusercontent.com/13774878/116353313-1f77c300-a829-11eb-8438-4c900cce6368.png)
npm start 之后，访问前端项目报这个错。
![image](https://user-images.githubusercontent.com/13774878/116353382-3cac9180-a829-11eb-9f30-f727c588b7dc.png)
前端页面报这个错误，希望帮忙解决下，谢谢

**Comment by scottsut** [comment]
Related to #1826
