### ISSUE TITLE
表格数据居中，字体大小

### ISSUE THREAD

**Issue by YuanZhencai** [edp963/davinci#2206]
表格数据没办法居中，并且字体设大表格的行高不能岁字体变大

其实我一开始的需求是类似做一个数值的Card，发现没有组件，所有用了表格组件

![image](https://user-images.githubusercontent.com/4961592/119959386-89c18600-bfd6-11eb-9c4b-3676a0c49917.png)

**Comment by scottsut** [comment]
用翻牌器组件试试
