### ISSUE TITLE
透视表格错位

### ISSUE THREAD

**Issue by 190311831** [edp963/davinci#2213]
![image](https://user-images.githubusercontent.com/22760405/121161712-daab6700-c87f-11eb-818f-36ad72392d65.png)
透视驱动，表格错位比较严重，是否已经在规划修改？

**Comment by wujianbin-sh** [comment]
好像只是在 Chrome V91及以上版本才有这个问题。
简单的改法就是 row header 的 DIV 的 样式加个 display: block 即可。
文件:  app/containers/Widget/components/Pivot/RowHeader.tsx 
把
    return (
      <div className={containerClass}> ....
改为 
    return (
      <div className={containerClass} style={{display: "block"}}> ....

**Comment by 190311831** [comment]
添加上了这个属性&nbsp; 目前已经好多了&nbsp; &nbsp;
感谢支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "edp963/davinci"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [edp963/davinci] 透视表格错位 (#2213)





 
好像只是在 Chrome V91及以上版本才有这个问题。
 简单的改法就是 row header 的 DIV 的 样式加个 display: block 即可。
 文件:  app/containers/Widget/components/Pivot/RowHeader.tsx
 把
 return (
 
 ....
 改为
 return (
 <div className={containerClass} style={{display: "block"}}&gt; ....

**Comment by hotbird3** [comment]
@190311831 请问怎么改。要重新编译源码？

**Comment by hotbird3** [comment]
能否辛苦发一份修改过的编译版？

**Comment by wujianbin-sh** [comment]
需要重新编译。
你需要的是基于官方的，2020-10-29 日的发布版： https://github.com/edp963/davinci/releases/tag/v0.3.0-rc 的重新编译版本，
还是基于最新的 0.3 分支代码的编译版本？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "edp963/davinci"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月15日(星期二) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [edp963/davinci] 透视表格错位 (#2213)





 
能否辛苦发一份修改过的编译版？

**Comment by hotbird3** [comment]
> 需要重新编译。 你需要的是基于官方的，2020-10-29 日的发布版： https://github.com/edp963/davinci/releases/tag/v0.3.0-rc 的重新编译版本， 还是基于最新的 0.3 分支代码的编译版本？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "edp963/davinci" ***@***.***&gt;; 发送时间:&nbsp;2021年6月15日(星期二) 下午4:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [edp963/davinci] 透视表格错位 (#2213) 能否辛苦发一份修改过的编译版？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是  v0.3.0-rc  版本。Thanks！
