### ISSUE TITLE
how use control cascade（两个表级联怎么使用）

### ISSUE THREAD

**Issue by qq443672581** [edp963/davinci#2236]
抱歉啊，实在英文水平不好，翻译软件又怕不准确

假设场景： 我们是多租户埋点统计，每个租户都有自己命名的事件名，所以可以大致有三张表
tenant:  id name
event:   id name  tenant_id(这个事件属于哪个租户)
event_record: id tenant_id event_id date

比如我要查询a租户登陆事件的总数
那我先要下拉 tenant选项选择 a(text:a,value:1)，然后event下拉应该级联出 a租户的event事件，而不是包涵a、b、c。。。

不知道现在是否可以实现，我使用的是 0.3.1-rc 版本，谢谢~

**Comment by qq443672581** [comment]
在线等~

**Comment by scottsut** [comment]
可以参考全局控制器级联配置 https://edp963.github.io/davinci/docs/zh/2.4-dashboard#263-%E7%BA%A7%E8%81%94

**Comment by qq443672581** [comment]
🙆‍♂️
