### ISSUE TITLE
multiple datasets??

### ISSUE THREAD

**Issue by chinobing** [edp963/davinci#2270]
Is that possible to merge or join mutiple datasets by a keyword from different databases(mysql)?

**Comment by scottsut** [comment]
https://github.com/edp963/moonbox is used for that.

**Comment by chinobing** [comment]
> https://github.com/edp963/moonbox is used for that.

can i achieve the same purpose without using extra tool like moonbox cuz my davinci is runing under docker

im coming from metabase. what i really want is using "join" function with two datasets as metabase does

**Comment by scottsut** [comment]
Metabase does not seem to support joining tables across multiple databases.

https://www.metabase.com/docs/latest/faq/using-metabase/how-do-i-answer-questions-when-data-is-in-multiple-databases.html

If you mean join tables in one database, SQL can do anything.

**Comment by scottsut** [comment]
For MySQL, you can create a source to connect to an instance instead of a specific database. Then you can use `database_name.table_name` in SQL to join another database tables.

**Comment by chinobing** [comment]
thx

**Comment by chinobing** [comment]
yoyo, just realized you are working on datart too. i want to deploy datart under docker-compose . but the docker-compose.yml of datart doesnt detail the email setup and chrome. can i just copy the one from davinci to datart?

**Comment by scottsut** [comment]
> yoyo, just realized you are working on datart too. i want to deploy datart under docker-compose . but the docker-compose.yml of datart doesnt detail the email setup and chrome. can i just copy the one from davinci to datart?

Thank for the interest!

davinci and datart are two completely different projects, `docker-compose.yml` cannot be mixed. datart does not need to configure server details in `docker-compose.yml`, just edit it directly in `config` folder, and docker can work synchronously.

**Comment by chinobing** [comment]
Thanks for the useful info. Have a nice day bro

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
