### ISSUE TITLE
一点优化建议

### ISSUE THREAD

**Issue by taotao365s** [edp963/davinci#2274]
先说下背景，我们这大约是一个系统几百个项目运行，完全独立的

- 报表是否可以增加克隆配置？现在只有组件级克隆，能否提升到报表级别？将所有配置导出？
- view、widget列表是否可以分下目录，一层不够呀，加个排序？
- 是否出一期视频教程，可以让更多的参与进来？
- 邮箱那个配置能不能优化一下，从开箱即用来说不够友好

**Comment by scottsut** [comment]
你好，davinci 项目已经不再维护，我们主创团队现目前在做新的数据可视化产品 https://github.com/running-elephant/datart 欢迎关注

**Comment by taotao365s** [comment]
@scottsut 好的
