### ISSUE TITLE
云端部署无法正常访问

### ISSUE THREAD

**Issue by stitchLau** [edp963/davinci#2281]
1. 在云服务器中配置`server.port`及`server.address`，不启用`server.access.port`及`server.address`，地址配置为127.0.0.1外部无法访问；
2. 配置`server.address`为云服务器公网地址，报错`Cannot assign requested address: bind`；
3. 配置`servere.address`为`127.0.0.1`，`server.access.address`为公网地址，启动失败`Cannot assign requested address`

**Comment by bjchenshuijun** [comment]
您好！您的邮件已经收到， 感谢您的来信。这是自动回复的邮件，我将在看到邮件内容后的第一时间内进行接下来的处理，谢谢！祝：工作顺利！---------------------------------------------陈水军手机：137-7747-3861

**Comment by fumiwork** [comment]
> 您好！您的邮件已经收到， 感谢您的来信。这是自动回复的邮件，我将在看到邮件内容后的第一时间内进行接下来的处理，谢谢！祝：工作顺利！---------------------------------------------陈水军手机：137-7747-3861

这是谁？是骗子吗？这位不是项目组成员

**Comment by yuluochengxin** [comment]
有没有可能你的端口，在防火墙里面规则没有打开？所以127.0.0.1的时候走内部是没问题，但是换成公网ip端口没开呢？？？

**Comment by stitchLau** [comment]
> 有没有可能你的端口，在防火墙里面规则没有打开？所以127.0.0.1的时候走内部是没问题，但是换成公网ip端口没开呢？？？

服务器出站规则有设置，服务器控制台也打开了相应端口，目前通过Nginx进行代理已可进行正常访问，但类似于注册等需要生成链接的功能无法正常使用。

**Comment by 57592856** [comment]
I am suffering this same problem, any helps are great welcome!

**Comment by 57592856** [comment]
A goods news i solved this problem yesterday，the reason is Tencent cloud server has a inside IP and a outside IP，you could try modify the application.yml as below：
`server:
  protocol: http
  address: 10.0.12.4 #Tencent inside IP，get this IP from Tencent cloud wordspace。
  port: 80

  access:
    address: 101.35.54.18 #Tencent inside IP，get this IP from Tencent cloud wordspace。
    port: 80`

**Comment by 57592856** [comment]
A goods news i solved this problem yesterday，the reason is Tencent cloud server has a inside IP and a outside IP，you could try modify the application.yml as below：
```
`server:
protocol: http
address: 10.0.12.4 #Tencent inside IP，get this IP from Tencent cloud wordspace。
port: 80

access:
address: 101.35.54.18 #Tencent outside IP，get this IP from Tencent cloud wordspace。
port: 80`
```
