### ISSUE TITLE
前端模块部署起来很多报错，能否指定node和npm版本？

### ISSUE THREAD

**Issue by github512** [edp963/davinci#2285]
前端模块部署起来很多报错，能否指定node和npm版本？
package.json文件里面说
    "npm": ">=5",
    "node": ">=8.15.1"
但是下载最新的node和npm版本还是无法启动前端，能否明确表明是用哪个版本号成功启动前端的？

**Comment by Luooojunnn** [comment]
请问单独的webapp，也就是前端项目怎么启动啊，我这边 npm i 之后，npm start 无法启动

**Comment by scottsut** [comment]
package.json 描述没有问题。具体错误具体分析。
