### ISSUE TITLE
Dashboard查询时提交的sql日志在哪个目录下

### ISSUE THREAD

**Issue by mpmiles** [edp963/davinci#2293]
请问Dashboard查询时提交的sql日志在哪个目录下？
我有一张可视化组件加了一个日期范围的控制器传入sql里，sql里已经设置了in $参数$，但是在Dashboard查询的时候还只是显示一天的数据
想知道这个数据查询时提交的sql在哪里看，或者上述问题如何解决，谢谢。

**Comment by scottsut** [comment]
在 `config/logback.xml` 中，把 `SQL_LEVEL` 改为 `DEBUG` 就行

**Comment by scottsut** [comment]
在 `application.yml` 中，将 `source.enable-query-log` 改为 `true` 就行

**Comment by mpmiles** [comment]
@scottsut 已解决，感谢

**Comment by mpmiles** [comment]
> 在 `application.yml` 中，将 `source.enable-query-log` 改为 `true` 就行

感谢感谢
