### ISSUE TITLE
[server+ui]支持在source list页面查看或修改table某列某行值

### ISSUE THREAD

**Issue by fumiwork** [edp963/davinci#23]

**Comment by fumiwork** [comment]
。在source页面的操作里，加一个“table管理”按钮
。当点击“table管理”按钮，弹出页面，左侧显示所有tables
。当点击某table，右侧可以查看分页显示的若干行，可以单击某cell修改值并update回数据库
。用户只需回到widget刷新即可看到更新后的数据

**Comment by fumiwork** [comment]
。考虑是否需要支持insert和delete

**Comment by scottsut** [comment]
重新规划
