### ISSUE TITLE
部署到生产控制台窗口闪退

### ISSUE THREAD

**Issue by jasonwish** [edp963/davinci#2311]
你好 我部署到生产环境后控制台窗口闪退，且找不到有用的错误日志
<img width="808" alt="1663249829272" src="https://user-images.githubusercontent.com/20253248/190421373-0d0bce9f-d0fd-4cac-a12d-ffdeefe636fa.png">
我非常想深入使用davinci 但是找不到人交流请教，有这样的QQ 或者微信群吗

**Comment by China-biao** [comment]
闪退可以考虑一下你的环境变量配对没有

**Comment by jasonwish** [comment]
感谢你的回复，闪退问题我已经解决，是因为端口问题，但是我现在想去除地址栏上的#好 尝试了各种方式都不行

**Comment by China-biao** [comment]
> 

react的路由问题吧
