### ISSUE TITLE
在配置数据源时报错，提示找不到数据库驱动

### ISSUE THREAD

**Issue by darkotaku** [edp963/davinci#247]
ERROR com.zaxxer.hikari.HikariConfig[508] - Failed to load driver class com.microsoft.sqlserver.jdbc.SQLServerDriver from HikariConfig class classloader sun.misc.Launcher$AppClassLoader@53d8d10a
ERROR edp.davinci.rest.source.SourceRoutes[208] - test connection exception
java.lang.RuntimeException: Failed to load driver class com.microsoft.sqlserver.jdbc.SQLServerDriver in either of HikariConfig class loader or Thread context classloader
咋整啊，我看JAR包都是有的啊！！！

**Comment by darkotaku** [comment]
系统是CENTOS7 ，JDK版本1.8

**Comment by sunsence** [comment]
你把sqlserver的相关jar放到lib下

**Comment by sunsence** [comment]
@darkotaku 可以加入github页面的微信交流群，在那里交流会更方便和及时
