### ISSUE TITLE
前端项目我想二次开发咋整啊？

### ISSUE THREAD

**Issue by zfowed** [edp963/davinci#260]
我拉取项目下来后：
```
npm install
npm run start
```
访问 http://localhost:5002/ 好像不行。

**Comment by scottsut** [comment]
你需要部署服务端，下载0.2.1的release包部署完成后，再去前端项目npm start

**Comment by zfowed** [comment]
emmm......我觉得应该不关服务端的事情

就是 npm run start 好像都有一些问题的感jio [伤心]

![image](https://user-images.githubusercontent.com/23629388/43046686-19d3812e-8dff-11e8-9772-27f0531fa2d2.png)
![image](https://user-images.githubusercontent.com/23629388/43046689-23031fe8-8dff-11e8-803d-238b3e7ed130.png)
![image](https://user-images.githubusercontent.com/23629388/43046693-2990a0e2-8dff-11e8-9b0d-b07b9c0e066e.png)

**Comment by scottsut** [comment]
你的情况看样子像是项目依赖没有安装完整，css-loader没有起作用，建议你把项目依赖重新安装一下。

**Comment by scottsut** [comment]
前端项目依赖中确实有一些问题，但不是你上面贴出来的这些错误；
会有以下两个问题需要手动调整：

1. antd依赖下可能会有moment的嵌套依赖，会导致一些错误，需要到node_modules/antd下面手动删除moment依赖；
1. three.js中有一些内部模块冲突，需要到node_modules/three/build/three.module.js中删除最后一行的 CanvasRenderer 和 Projector 两个导出对象；

操作完成后，npm run build:dll 重新生成dll文件，然后 npm start 即可运行前端项目

**Comment by a447987428** [comment]
![da](https://user-images.githubusercontent.com/16891124/43121729-586a6eae-8f51-11e8-85c3-642ec1932414.png)
![db](https://user-images.githubusercontent.com/16891124/43121820-9df93770-8f51-11e8-8eb0-cdcf692e5c4f.png)
_#___

**Comment by a447987428** [comment]
用什么node版本？

**Comment by scottsut** [comment]
我们目前是使用8，也就是LTS版本。
你发的贴图第二张，moment嵌套依赖貌似在rc-calender和rc-time-picker里都有，你到node_modules的这个两个文件夹下删除嵌套的moment依赖，然后重新npm run build:dll一下。
第三张图里的css-loader为什么不生效这个原因估计只有你自己排查一下了，建议你npm cache verify一下，如果是用的yarn就yarn cache clean一下，然后重新安装一下依赖试试。
操作步骤如下：重新安装依赖 -> 删除嵌套moment依赖并修改three.module.js里的模块冲突 -> npm run build:dll -> npm start

**Comment by scottsut** [comment]
@zfowed @a447987428 我们测试了一下在windows系统下的项目依赖安装，发现webpack配置项里确实有兼容问题导致css-loader失效，现在已经修复好提交到master，你们可以拉取一下最新的代码。

**Comment by zfowed** [comment]
@scottsut 感谢大佬关怀护佑~

**Comment by gzocs** [comment]
![2018-09-21 15-45-56](https://user-images.githubusercontent.com/40254500/45867207-7ab1c100-bdb5-11e8-8e49-7819e8336650.png)

@scottsut 按照你提供的方法好像是启动了，但是访问首页显示NOT FOUND，同时报错。

**Comment by scottsut** [comment]
@gzocs 你这个看上去像是依赖没有安装完整，你把node_modules目录删除然后重新安装一下依赖试试。
0.3.0-beta安装依赖请使用npm，yarn可能会有嵌套依赖版本错误的问题。

**Comment by chqbyq** [comment]
@scottsut 你好，想请教一下前端pngquant failed to build, make sure that libpng-dev is installed这个报错遇到过吗？
![image](https://user-images.githubusercontent.com/34851435/78214903-e74c6680-74e8-11ea-9dd9-d706093d63e1.png)

**Comment by scottsut** [comment]
Looks like dependencies are not fully installed.

**Comment by jackieveev** [comment]
感谢各位的努力和付出，但不得不说一句，这个项目的二次开发支持太糟糕了，文档也没有，想要做一点更改弄了半天都不得其法，让人莫名其妙。
