### ISSUE TITLE
请问后续会考虑对Hbase和Redis的支持吗？

### ISSUE THREAD

**Issue by DevotedTangLiu** [edp963/davinci#292]
请问后续会考虑对Hbase和Redis的支持吗？
考虑到如果做一个看板，数据源全是jdbc类型不太现实，我们目前数据主要使用hbase和redis做存储。

**Comment by scottsut** [comment]
@DevotedTangLiu 你好，我们后续没有直接对接Hbase和Redis数据源的计划，不过你的问题可以通过这些方式来解决：
1. 使用我们团队的另一个开源产品moonbox，moonbox会支持众多异构数据混算；
1. davinci除了jdbc之外，未来还计划支持rest方式的数据来源，这个功能开发估计要等到0.3版以后了。

**Comment by DevotedTangLiu** [comment]
好的，谢谢
