### ISSUE TITLE
请问我下载了代码，并打包成功了，运行start-server.sh时报错？

### ISSUE THREAD

**Issue by shanleiyang** [edp963/davinci#304]
请问报一下错误是什么原因？
bin/start-server.sh: line 2: $'\r': command not found
bin/start-server.sh: line 4: $'\r': command not found
: No such file or directory: cd: /home/davinci/davinci/bin
bin/start-server.sh: line 8: $'\r': command not found
Error: Could not find or load main class edp.davinci.DavinciStarter

**Comment by scottsut** [comment]
你好，你提供的信息比较少，可以访问 https://edp963.github.io/davinci/ 扫描下面的二维码进用户群，提供更多信息供我们参考。

**Comment by reoverflow** [comment]
路径不对，如果执行官方的文档，需要切换到bin的上级目录，另外官方提供的下载内容中（0.3beta版）目前未包含lib内容，需要自行打包，这块还辛苦团队完善一下。

**Comment by owls0** [comment]
这个问题我也遇到了，我是这么解决的：将从github上下载Release 包中的bin目录中的start-server.sh文件复制到服务器中的davinci解压后的bin目录下替换原来的start-server.sh文件，当然你也可以把bin目录下的所有文件都替换了；可能是在自己的电脑上打包后编码格式改变导致的。
