### ISSUE TITLE
怎么连接kylin？

### ISSUE THREAD

**Issue by JIAWEIBeh** [edp963/davinci#313]
我把驱动放进lib目录  配置是对的   测试连接时报了一个 2018-08-23 11:46:02 [davinciActorSystem-akka.actor.default-dispatcher-9] ERROR com.zaxxer.hikari.HikariConfig[508] - Failed to load driver class org.apache.kylin.jdbc.Driver from HikariConfig class classloader sun.misc.Launcher$AppClassLoad
er@55f96302

**Comment by zzm9201989** [comment]
遇到同样的问题，请问解决没？
