### ISSUE TITLE
前端0.2版本进入Dashboard分享页面失败！

### ISSUE THREAD

**Issue by congtaoa** [edp963/davinci#371]
前端0.2版本通过Dashboard普通分享的链接进入，没有进入到share文件夹下的app.js,而进入了app文件夹下的app.js，导致进入失败，请问如何修改？？

**Comment by scottsut** [comment]
你好，你是在二次开发过程中遇到这个问题吗？开发中链接地址需要自己手动修改一下，localhost:5002/share/#/share/xxx 需要手动修改成 localhost:5002/share.html#/share/xxx
部署的正式版不会遇到这个问题

**Comment by congtaoa** [comment]
@scottsut  是的，感谢！

**Comment by congtaoa** [comment]
ERROR in ./share/reducers.js
Module parse failed: /Users/taocong/Desktop/WebWeChat/davinci_web/node_modules/babel-loader/lib/index.js!/Users/taocong/Desktop/WebWeChat/davinci_web/share/reducers.js Unexpected token (73:4)
You may need an appropriate loader to handle this file type.
|     share: shareReducer,
|     widget: widgetReducer,
|     ...asyncReducers
|   })
| }
 @ ./share/store.js 29:0-38
 @ ./share/app.js
 @ multi share

ERROR in ./share/containers/Share/index.js
Module parse failed: /Users/taocong/Desktop/WebWeChat/davinci_web/node_modules/babel-loader/lib/index.js!/Users/taocong/Desktop/WebWeChat/davinci_web/share/containers/Share/index.js Unexpected token (115:19)
You may need an appropriate loader to handle this file type.
|    * @param qs
|    */
|   loadShareContent = (qs) => {
|     const {
|       onLoadDashboard,
 @ ./share/routes.js 23:0-38
 @ ./share/app.js
 @ multi share

ERROR in share.5dc10758b272a08c0984.js from UglifyJs
SyntaxError: Unexpected token punc «,», expected punc «:» [share.5dc10758b272a08c0984.js:123159,11]
打包是报错， 请问这个怎么解决呢
