### ISSUE TITLE
server 运行出错

### ISSUE THREAD

**Issue by yehui514** [edp963/davinci#436]
Could not resolve placeholder 'spring.datasource.url' in value "${spring.datasource.url}"

![image](https://user-images.githubusercontent.com/31580784/45604384-5dec5500-ba66-11e8-9f26-b2a272e7a3aa.png)

这是配置文件的路径错了吗，应该怎么配置

**Comment by shanmengm** [comment]
1.  确认已经配置了环境变量（DAVINCI3_HOME）
2. 请确保application.yml中每个配置项与值之间至少有一个空格
3. 如果是windows环境，请确保启动脚本或命令引入了配置文件，即`--spring.config.additional-location=file:%DAVINCI3_HOME%\config\application.yml`

**Comment by yehui514** [comment]
加上 --spring.config.additional-location=file:%DAVINCI3_HOME%\config\application.yml 之后确实可以，
但是这样的话在 server 目录下的 application.yml 文件中配置 spring.config.location 还有什么意义，而且只在这里配好像没起作用

**Comment by shanmengm** [comment]
单独新建了工程测试了一下，windows系统下springboot以jar包的方式运行，通过配置加载外部配置文件不会生效，目前只能按照这种方式去加载外部配置了

**Comment by yehui514** [comment]
好的，谢谢
