### ISSUE TITLE
提几个bug

### ISSUE THREAD

**Issue by qiujy** [edp963/davinci#467]
### 本人调研过最好用的国产开源BI展示系统，真心感谢宜信团队的努力。
我在本地部署运行测试davinci-0.3.0-beta.1 release版本时，发现几个问题：

1. 注册时：输入正确信息，console报错。
2. 登录时：没有内置账号，在数据库脚本里也没找着，有几个字段不知道填什么？
3. 后台：上传CSV时总是报错...
4. pdf手册：配置环境变量写错了，应该是“export DAVINCI3_HOME=...”

另外，还有几点建议：
1. 后台UI：功能菜单能否在后台首页直接显示？现在都需要进入 用户设置，在点不方便。
2. 后台功能：增加用户管理的功能。个人感觉：大部分需求是后台添加可登录的用户，注册激活使用率低。
3. 图表：目前就4种，类型实在太少。建议参看[Airbnb的Superset](https://github.com/apache/incubator-superset)，增加些比较炫的图表，这个客户会大大加分。
4. 性能方面：不知道咱们这个是否有做好 非并发加载Dashboard中的所有图表。我在调研[Airbnb的Superset](https://github.com/apache/incubator-superset)时发现，在一个Dashboard中有n个图表展示时浏览器会卡死了。。
5. 示例方面：建议搭建一套在线演示环境，这些更能吸引使用者。同时内置好一些示例，更直观的引导用户。。。特别是刚上手时都不知道怎么操作，也没有啥炫酷的Dashboard可以看。。。

**Comment by scottsut** [comment]
@qiujy 非常感谢支持！
当前davinci正在加紧完善0.3版本的功能，以达到可以无缝替换0.2版的目标。pdf手册上的说明是对应0.2版本的，新版本的文档我们会在10月份逐步完善起来。
关于图表的种类，0.2版本支持大约20种图表，我们目前正在做迁移工作，预计10月中旬可以完全迁移完毕。
性能方面我们目前准备实行的方案是让用户可以自主配置查询数据量的阈值，可能不是完美的解决方案，但是暂时可以解决一下这个问题。
在功能的设计和交互方面，我们会听取用户的意见然后逐步迭代。目前不是很有时间完善用户体验度，因为主要功能还在加紧开发中，后续我们会慢慢完善起来。
另外，我们的公网示例服务器已经在搭建和测试中了，预计很快就会开放，届时会将地址更新到 readme 中。
