### ISSUE TITLE
davinci配置email后无法启动

### ISSUE THREAD

**Issue by xfg0218** [edp963/davinci#518]
当配置完以下配置时，启动任务一直停留在
*****************
19:49:54.077 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.

邮箱配置
 ## mail is one of the important configuration of the application
  ## mail config cannot be null or empty
  ## some mailboxes need to be set separately password for the SMTP service)
  mail: xufugui@chinadaas.com
    host: smtp.exmail.qq.com
    port: 465
    username: xiaoxu
    password: ******
    nickname: xiaoxu

    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: true

有配置email的模板吗？谢谢

**Comment by shanmengm** [comment]
首先，以上异常是yaml缩进问题导致的，yaml规定，key后的冒号和value之间至少需要一个空格
其次，邮箱的配置需要注意，这里的password是独立服务密码（或邮箱独立密码，各邮箱服务商叫法不同）而不是邮箱登录密码
还有，ssl开启后需要有证书才能连接

**Comment by reoverflow** [comment]
@xfg0218 
我是用的163的邮箱服务器，只用其发送邮箱功能，实测是好用的，配置如下：
  mail:
    host: smtp.163.com
    port: 25
    username: xxxxxxxxx@163.com
    password: **************
    nickname: davinci

**Comment by gaoqingzhi** [comment]
楼主问题解决了么？》
我也卡在这不动了
12:52:33.874 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.

**Comment by xfg0218** [comment]
@gaoqingzhi 正确的配置如下,详细的配置请查看:https://edp963.github.io/davinci/deployment.html
![image](https://user-images.githubusercontent.com/17243203/51361146-93cf4200-1b09-11e9-9670-8aec0e2da660.png)
