### ISSUE TITLE
0.3版本绕过邮箱注册

### ISSUE THREAD

**Issue by jiangling581** [edp963/davinci#526]
您好，由于我们服务器在本地并且跟互联网是不通的，想知道怎么绕过邮箱注册，直接在user表写数据提示salt版本不对，希望能够给个初始化可以直接用的user表数据，或者 能够绕过 邮箱注册的方法

**Comment by shanmengm** [comment]
您好，目前release版本不支持这样直接创建用户，如果您是定制化开发的话可以使用我们的源码，修改用户注册这部分逻辑，然后自行打包使用

**Comment by reoverflow** [comment]
需要三张表，user、rel_user_organization、organization，  其中其他的关联上即可，密码范例（123456）：

`$2a$10$k61V3U4QPdEZdPm.MJJIAehH3qpRQaCR4I8NkOlzXbL.zWnA5ihyq`

**Comment by dingluoneu** [comment]
@jiangling581 后端的改动如下：
1、User类，属性active默认值true;
      `private Boolean active = true;`
2、UserServiceImpl.java 类中，regist方法，注释掉或者去掉发送激活邮件的部分；
