### ISSUE TITLE
关于 地图 widget 纬度数据格式

### ISSUE THREAD

**Issue by reoverflow** [edp963/davinci#574]
想要生成地图的数据统计，纬度的数据格式应该是什么样的，能否举个例子，非常感谢。

**Comment by scottsut** [comment]
地图需要先在 View 里指定数据模型的可视化类型：
![image](https://user-images.githubusercontent.com/4098913/48704545-d66fbd80-ec31-11e8-832e-868d74e86bfe.png)
然后在 Widget 编辑界面将字段拖拽到维度栏里即可：
![image](https://user-images.githubusercontent.com/4098913/48704614-05862f00-ec32-11e8-9464-86bda1e1e262.png)
地图数据目前支持中国省份、城市以及区县：
![image](https://user-images.githubusercontent.com/4098913/48704762-5b5ad700-ec32-11e8-875e-0f33b86e23f3.png)

**Comment by reoverflow** [comment]
哦   明白，感谢感谢，我试试。
