### ISSUE TITLE
jdbc问题

### ISSUE THREAD

**Issue by lxorc** [edp963/davinci#585]
1. 配置好mongoDB的jdbc 后, 创建view 的时候会报null exception
2. 配置hive 的jdbc 后, 会提示Failed load class....

**Comment by lxorc** [comment]
细节已发送到readme邮箱内

**Comment by reoverflow** [comment]
Davinci 内部只提供了 MySql 的驱动包，也就是说，如果你要使用其他数据源，还需将对应驱动jar 包手动拷贝到lib目录并重新启动 Davinci 服务

**Comment by shanmengm** [comment]
目前dev-0.3分支已修复，如果使用release包的话我们会在近期发新包
