### ISSUE TITLE
0.3版本 透视表自由钻取 

### ISSUE THREAD

**Issue by reoverflow** [edp963/davinci#591]
@scottsut hi， 0.3版本的钻取功能开放了吗？

**Comment by scottsut** [comment]
@reoverflow 你好，当前最新beta版本支持透视驱动下的图表自由钻取，透视表自由钻取正在开发中。钻取功能目前还是实验性的，功能设计和交互方式在之后都有可能会发生变化。

**Comment by reoverflow** [comment]
收到，感谢回复。

**Comment by GoogleSmile** [comment]
> @reoverflow 你好，当前最新beta版本支持透视驱动下的图表自由钻取，透视表自由钻取正在开发中。钻取功能目前还是实验性的，功能设计和交互方式在之后都有可能会发生变化。

您好，目前下钻能全选吗？我现在想选择柱状图所有省，下钻下面的市，但是我点，只能一个个点柱状图的每一个省，然后右键下钻到市。不能一下子全部选择每个柱，然后下钻吗？
