### ISSUE TITLE
使用自定义数据源postgresql，出现错误

### ISSUE THREAD

**Issue by superguopeng** [edp963/davinci#592]
![image](https://user-images.githubusercontent.com/41366948/48990995-e1fc4080-f16b-11e8-9f79-14b312a1ee00.png)
出现如图的错误，如果不使用自定义的postgresql数据源，不会出错，使用自定义数据源后出现错误，配置：postgresql:
   name: postgresql
   desc: postgresql
   driver: org.postgresql.Driver
   keyword_prefix:
   keyword_suffix:
   alias_prefix: '"'
   alias_suffix: '"'

**Comment by shanmengm** [comment]
dev-0.3分支已修复，release我们会在近期发布新的版本修复
