### ISSUE TITLE
[建议] 为什么要使用存储过程？

### ISSUE THREAD

**Issue by qiutiaoming** [edp963/davinci#635]
目前公司的mysql命令禁止使用存储过程，据了解百度，阿里的规范也都是禁用存储过程，请问davinci的存储过程能改成其他的方式实现吗？为什么一定要使用存储过程。
谢谢。

**Comment by shanmengm** [comment]
你好，我们在开发过程中没有遇到不让用存储过程的问题。
由于目前存储过程用的比较多，短期内不会改的，不过我们会考虑的，谢谢！
