### ISSUE TITLE
Invalid DAVINCI3_HOME 

### ISSUE THREAD

**Issue by iexe** [edp963/davinci#647]
Invalid DAVINCI3_HOME 
已经按照要求 编辑 profile 文件 添加内容还是这样！
并没有在=号边加空格！我能得到你们的帮助吗！
info@iiexe.com

**Comment by shanmengm** [comment]
“Invalid DAVINCI3_HOME”是因为没有配置环境变量，请参考用户手册配置: https://edp963.github.io/davinci/deployment.html

**Comment by iexe** [comment]
谢谢
