### ISSUE TITLE
为什么创建viewlist保存不了

### ISSUE THREAD

**Issue by hiswwj123** [edp963/davinci#664]
创建 viewList，点击保存按钮，保存不了，希望技术人员给出解答。

**Comment by scottsut** [comment]
请参考davinci用户手册里“数据视图管理”部分，确认一下操作是否正确。
https://edp963.github.io/davinci/view_guide.html

如果确认操作无误的话，请打开浏览器控制台，将控制台输出和网络请求响应内容截图，帮助我们定位问题

**Comment by hiswwj123** [comment]
> 请参考davinci用户手册里“数据视图管理”部分，确认一下操作是否正确。
> https://edp963.github.io/davinci/view_guide.html
> 
> 如果确认操作无误的话，请打开浏览器控制台，将控制台输出和网络请求响应内容截图，帮助我们定位问题

你好操作没什么问题
![image](https://user-images.githubusercontent.com/46470505/50810487-ddb76b80-1344-11e9-84d8-d757e3a94bd4.png)

**Comment by scottsut** [comment]
你的release包是从哪来的？

**Comment by scottsut** [comment]
如果是从开发分支自己编译的，我们不确保开发分支代码的稳健性，请自己解决或是使用release中的稳定版本。

**Comment by hiswwj123** [comment]
> 请参考davinci用户手册里“数据视图管理”部分，确认一下操作是否正确。
> https://edp963.github.io/davinci/view_guide.html
> 
> 如果确认操作无误的话，请打开浏览器控制台，将控制台输出和网络请求响应内容截图，帮助我们定位问题

你好我看了一下，操作是没有问题的
![Uploading image.png…]()


> 如果是从开发分支自己编译的，我们不确保开发分支代码的稳健性，请自己解决或是使用release中的稳定版本。

我用的就是是稳定版本，版本是3.0.1

**Comment by scottsut** [comment]
你的 release 包是在 https://github.com/edp963/davinci/releases 下载的最新版吗？还是我们这边开发人员私底下给你打包的版本？

**Comment by scottsut** [comment]
我们在干净的虚拟机里测试了当前最新版release，也就是 davinci-0.3.0-beta.4 release，没有复现你的问题。
按照你截图的错误来看，sourceOrg这个字段来自于开发分支的新功能，beta.4 release 里是没有的，我们也很奇怪为什么会出现这个错误

**Comment by scottsut** [comment]
还有，从你的截图界面来看，里面使用的前端基础组件库是 ant design 3，我们在 beta.4 版本发布之后才将 ant design 从 2 升级到 3，也就是说，你使用的肯定是开发版的 release

**Comment by scottsut** [comment]
如果你是宜信员工在内部使用davinci，请蜜蜂联系我们解决问题，内部和开源社区使用版本不一样
