### ISSUE TITLE
在创建View时，需要等数据库结构加载出来之后才能查询问题

### ISSUE THREAD

**Issue by qiulin** [edp963/davinci#689]
目前，创建View时，需要等数据库结构完全加载出来后才能进行查询，但如果遇到比较大的库（如我们的库有2k+表），加载就会变得很慢，甚至一直加载不出来，然后就一直不能查询了，会提示数据源ID为空。

建议：

1. 查询时，不强制数据库结构必须加载
2. 数据库结构添加缓存

**Comment by scottsut** [comment]
多谢建议及描述使用场景！这个问题我们正在优化，下个版本会进行改进
