### ISSUE TITLE
透视驱动怎么理解，感觉配置跟图表驱动没啥区别

### ISSUE THREAD

**Issue by yuboon** [edp963/davinci#706]
![image](https://user-images.githubusercontent.com/45093416/51595310-616e7c00-1f31-11e9-971e-cc83ce32dce0.png)

**Comment by AndyFong** [comment]
可通过了解 Excel 中数据透视的概念理解此图表模式

**Comment by 506764932** [comment]
如果能在详细说明下就更好了
