### ISSUE TITLE
图表自由定制问题

### ISSUE THREAD

**Issue by robinloop** [edp963/davinci#714]
请问一下，有没有图表定制化这方面的考虑
现有的图表不能满足需求，需要定制化一些其他的图表
阅读代码，发现这块定制起来不是很方便，有对OperationPanel这块代码的重构计划吗？

**Comment by AndyFong** [comment]
图表定制化的需求可以较为详细地描述下吗？  
在重构，可查看 react16 分支进行比较。

**Comment by robinloop** [comment]
比如说：
1.柱图和线图合并展示，serials1使用bar，serials2使用line
2.仪表盘图、stack图等图表

**Comment by scottsut** [comment]
第一个需求是双轴图，下个版本会上；
第二个需求我理解为可以自由补充我们当前还支持不了的图表，这个在我们中长期计划中。
如果对图表种类有需求可以提到issue中，我们会视开发情况补充缺失的图表种类。
