### ISSUE TITLE
master分支-0.3.0-SNAPSHOT编译问题 

### ISSUE THREAD

**Issue by kelo2014** [edp963/davinci#727]
执行 **npm run build** 

**出现如下错误提示**

```
ERROR in [at-loader] ./app/containers/Widget/components/Pivot/Chart.tsx:647:30
    TS2345: Argument of type '{ grid: any[]; xAxis: any[]; yAxis: any[]; series: any[]; brush: { toolbox: string[]; throttleTyp...' is not assignable to parameter of type 'EChartOption'.
  Object literal may only specify known properties, and 'brush' does not exist in type 'EChartOption'.

ERROR in [at-loader] ./app/containers/Widget/render/chart/sankey.ts:101:18
    TS2702: 'EChartOption' only refers to a type, but is being used as a namespace here.
Child html-webpack-plugin for "index.html":
     1 asset
Child html-webpack-plugin for "share.html":
     1 asset
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! davinci-webapp@0.3.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the davinci-webapp@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by AndyFong** [comment]
1. `npm cache clean --force`
2. `npm install`
重新 `npm run build` 再试一下，上面 ts 类型的两处错误不影响最后 build 的生成

**Comment by WilkinWendy** [comment]
+1，我也遇到这个问题

**Comment by kelo2014** [comment]
多谢，按照你的方法，重试了2次，还是报同样的错，但是build是能正常生成，这个实际使用不知是否有问题

**Comment by WilkinWendy** [comment]
@kelo2014  你好，我的也能正常打包了，但是部署了无法正常访问，因为打包过程报了很多错，报js丢失

**Comment by AndyFong** [comment]
@kelo2014 @WilkinWendy 可以贴下截图看看

**Comment by WilkinWendy** [comment]
##build时控制台报错，但是文件生成成功
![image](https://user-images.githubusercontent.com/24538691/52762041-cc066980-3050-11e9-994b-48f2fb59aa6a.png)
##浏览器运行时，报文件丢失
![image](https://user-images.githubusercontent.com/24538691/52762088-05d77000-3051-11e9-92a9-b34ad28d2c36.png)
注：我把前端项目抽出来了，用nginx部署的

**Comment by AndyFong** [comment]
@WilkinWendy 看样子应该是 `typescript-loader` npm 包的问题，改用 cnpm 安装包试试

**Comment by WilkinWendy** [comment]
@AndyFong  cnpm我也试了，就是用的master 分支最新代码，您那边试了是没问题的吗？

**Comment by kelo2014** [comment]
详细错误如下，与第一次出现的好像一样
WARNING in ./node_modules/antd/lib/Form/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* E:\views\davinci\webapp\node_modules\antd\lib\Form\index.js
    Used by 3 module(s), i. e.
    E:\views\davinci\webapp\node_modules\awesome-typescript-loader\dist\entry.js!E:\views\davinci\webapp\app\containers\Profile\index.tsx
* E:\views\davinci\webapp\node_modules\antd\lib\form\index.js
    Used by 30 module(s), i. e.
    E:\views\davinci\webapp\node_modules\awesome-typescript-loader\dist\entry.js!E:\views\davinci\webapp\app\components\Filters\FilterPanel.tsx

**ERROR in [at-loader] ./app/containers/Widget/components/Pivot/Chart.tsx:647:30
    TS2345: Argument of type '{ grid: any[]; xAxis: any[]; yAxis: any[]; series: any[]; brush: { toolbox: string[]; throttleTyp...' is not assignable to parameter of type 'EChartOption'.
  Object literal may only specify known properties, and 'brush' does not exist in type 'EChartOption'.

ERROR in [at-loader] ./app/containers/Widget/render/chart/sankey.ts:101:18
    TS2702: 'EChartOption' only refers to a type, but is being used as a namesChild html-webpack-plugin for "index.html":**
     1 asset
Child html-webpack-plugin for "share.html":
     1 asset
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! davinci-webapp@0.3.0 build: `cross-env NODE_ENV=production webpack --npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the davinci-webapp@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional l
npm ERR! A complete log of this run can be found in:

**Comment by AndyFong** [comment]
![image](https://user-images.githubusercontent.com/6837655/52784438-1d821900-3090-11e9-875e-26c812a1c099.png)
@kelo2014 @WilkinWendy   
这边可以

**Comment by WilkinWendy** [comment]
真是奇怪了，我这里为啥就是不行
![image](https://user-images.githubusercontent.com/24538691/52788688-adc65b00-309c-11e9-8154-24fe0dd91535.png)

**Comment by AndyFong** [comment]
@WilkinWendy 以管理员身份打开 cmd，然后重新 `cnpm i` 试一下

**Comment by WilkinWendy** [comment]
还是不行，能不能把您的代码打个包过来，我看看。
我的操作是
git clone 
npm install
npm audit fix(这一步做不做都有问题)
npm run build

另外贴一个最新报错图。。
![image](https://user-images.githubusercontent.com/24538691/52792156-a6577f80-30a5-11e9-999a-139681b22e4e.png)

**Comment by AndyFong** [comment]
还是 `typescript-loader` 的问题，升级一下 node 至 10 版本再试一下

**Comment by WilkinWendy** [comment]
@AndyFong  我的node版本就是 10.7.0 .您那边typescript-loader 的安装版本是多少啊

**Comment by kelo2014** [comment]
我的版本如下，不知道版本会不会低，另外
E:\views\davinci\webapp>node -v
v11.7.0

E:\views\davinci\webapp>npm -v
6.5.0

**Comment by WilkinWendy** [comment]
@scottsut 目前遇到的问题就是 master分支的代码
1.npm install 会报一个 .locale 找不到但是整体提示成功
2.npm run build 报 lib下的几个tsx 无法被 awesome-typescript-loader正确解析，导致打包失败，但是文件能生成，运行起来报错（https://github.com/edp963/davinci/issues/727#issuecomment-463641266）
3.我试了view 分支打包正常

**Comment by WilkinWendy** [comment]
最近，问题有了新的进展@AndyFong @scottsut 
经测试，发现打包失败问题，只会发生在把前端代码单独push到一个新仓库后拉取下来时发生。
可是如果把新仓库的代码复制到davinci/webapp 下就又会成功
代码是一模一样的，换到davinci目录下就成功，很奇怪

**Comment by dcxy0** [comment]
我也遇到这个问题了，上面的解决办法都用过了，还是报错.

[at-loader] Checking finished with 2 errors
Hash: bcc8cff1b19c20d7114b
Version: webpack 3.5.5
Time: 203141ms
                                Asset       Size  Chunks                    Chunk Names
 edcdc8c88ddb2471a19d78705d0c9bf1.png    6.43 kB          [emitted]
 9ec5e40edddff9ff300e6791941fe869.eot    70.5 kB          [emitted]
 3a2ba31570920eeb9b1d217cabe58315.ttf    70.3 kB          [emitted]
de3f28fdd0af647ec0d2b1c22d845064.woff    37.3 kB          [emitted]
 5355ed90147de28ececc28a5376172ee.eot    26.4 kB          [emitted]
 0a9c32c5065b1a59d723766ccc6eb0b4.svg     127 kB          [emitted]
 88d025404e857f79062f2d95122a9108.ttf    26.2 kB          [emitted]
 c6a72062dbbd6836f64c361099e023dc.png    9.38 kB          [emitted]
 e6488e0deef4243bfca39c0cca5c73d5.png    10.2 kB          [emitted]
 036ed0f1aefe05c1da412d61336f0c74.png    14.4 kB          [emitted]
 f0ec6d587973aa88c2e29b0b1c65c808.png    16.4 kB          [emitted]
 d2b08fa3933fc618ca070eaf28345e87.png    16.1 kB          [emitted]
 f653b5d0e9eb955bf923492e28c5d661.png    7.95 kB          [emitted]
 4634e042683621456707c7414609db06.png    9.12 kB          [emitted]
 b955335f4f34391cef70c82e6149517c.png    11.1 kB          [emitted]
 0aa728803d97983f1ae1f7c6cc45e54a.png    12.6 kB          [emitted]
 3941a2931ff7a7890ab3f2a9b8f9353e.png    11.1 kB          [emitted]
 1ef9dd5efa26f427e345e6fe8f0f44ab.png    8.18 kB          [emitted]
 076cb037164072430388ae25f0dcacc3.png    5.96 kB          [emitted]
 45550d3d69c8b0d67fb13be4c12dda92.png    5.72 kB          [emitted]
 ca5d4588dad9c32f49e895e7f19479df.svg     266 kB          [emitted]  [big]
 eca5185dce4a9ef9c63676d54c5078e2.png    9.32 kB          [emitted]
 57bff8887f24eaa28fb34254c65d90e8.png    6.53 kB          [emitted]
 fd4cb43ebd00f4b629d9d48860f1f8fe.png    8.37 kB          [emitted]
 75873f6cbdd6bd2f758ef087a0c773df.png    25.8 kB          [emitted]
 4cc4900c2d9be838f7d9d5b6b087c600.png    5.55 kB          [emitted]
 288a6b2bf4dbd288124b27f9be8cf30c.png    8.53 kB          [emitted]
 90cd9a7a53eb8f6f78b2ebbd10f9c20c.png  104 bytes          [emitted]
 1c8e2633766f2fb8bda742b37e16169e.svg    2.69 kB          [emitted]
 e92352b7d5694fd944eaa9e69ada160a.svg    2.86 kB          [emitted]
 6b49995ae3ae7870597e6843415551a0.svg    1.45 kB          [emitted]
 c74f2afb0c9b2607c300a64420474865.png    1.18 kB          [emitted]
 947c3f17f9767ffbd1e40441036df0d5.png    1.21 kB          [emitted]
                        .htaccess.bin    1.52 kB          [emitted]
                          favicon.ico    4.29 kB          [emitted]
                        manifest.json  625 bytes          [emitted]
          app.3214ed5a00d17439e64a.js    6.22 MB       0  [emitted]  [big]  app
        share.cf719df218a73caef935.js     3.9 MB       1  [emitted]  [big]  share
                           index.html    1.75 kB          [emitted]
                           share.html    1.75 kB          [emitted]

WARNING in ./node_modules/_moment@2.24.0@moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '\davinci\webapp\node_modules\_moment@2.24.0@moment\src\lib\locale'
 @ ./node_modules/_moment@2.24.0@moment/src/lib/locale/locales.js 56:12-46
 @ ./node_modules/_moment@2.24.0@moment/src/lib/locale/locale.js
 @ ./node_modules/_moment@2.24.0@moment/src/moment.js
 @ ./app/components/Filters/FilterPanel.tsx
 @ ./app/containers/Dashboard/components/DashboardFilterPanel.tsx
 @ ./share/containers/Dashboard/index.tsx
 @ ./share/routes.ts
 @ ./share/app.tsx
 @ multi ./share/app.tsx

WARNING in ./node_modules/_antd@2.13.14@antd/lib/Button/button-group.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Button\button-group.js
    Used by 1 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Button\index.js
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\button\button-group.js
    Used by 1 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\button\index.js

WARNING in ./node_modules/_antd@2.13.14@antd/lib/Button/button.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Button\button.js
    Used by 1 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Button\index.js
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\button\button.js
    Used by 1 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\button\index.js

WARNING in ./node_modules/_antd@2.13.14@antd/lib/Button/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Button\index.js
    Used by 2 module(s), i. e.
    \davinci\webapp\node_modules\_awesome-typescript-loader@3.5.0@awesome-typescript-loader\dist\entry.js!\davinci\webapp\app\containers\Organizations\component\Setting.tsx
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\button\index.js
    Used by 50 module(s), i. e.
    \davinci\webapp\node_modules\_babel-loader@7.1.0@babel-loader\lib\index.js!\davinci\webapp\app\containers\NoAuthorization\index.js

WARNING in ./node_modules/_antd@2.13.14@antd/lib/Form/Form.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Form\Form.js
    Used by 1 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Form\index.js
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\form\Form.js
    Used by 1 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\form\index.js

WARNING in ./node_modules/_antd@2.13.14@antd/lib/Form/FormItem.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Form\FormItem.js
    Used by 1 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Form\Form.js
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\form\FormItem.js
    Used by 1 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\form\Form.js

WARNING in ./node_modules/_antd@2.13.14@antd/lib/Form/constants.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Form\constants.js
    Used by 2 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Form\Form.js
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\form\constants.js
    Used by 2 module(s), i. e.
    \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\form\Form.js

WARNING in ./node_modules/_antd@2.13.14@antd/lib/Form/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\Form\index.js
    Used by 3 module(s), i. e.
    \davinci\webapp\node_modules\_awesome-typescript-loader@3.5.0@awesome-typescript-loader\dist\entry.js!\davinci\webapp\app\containers\Profile\index.tsx
* \davinci\webapp\node_modules\_antd@2.13.14@antd\lib\form\index.js
    Used by 30 module(s), i. e.
    \davinci\webapp\node_modules\_awesome-typescript-loader@3.5.0@awesome-typescript-loader\dist\entry.js!\davinci\webapp\app\components\Filters\FilterPanel.tsx

ERROR in [at-loader] ./app/containers/Widget/components/Pivot/Chart.tsx:647:30
    TS2345: Argument of type '{ grid: any[]; xAxis: any[]; yAxis: any[]; series: any[]; brush: { toolbox: string[]; throttleTyp...' is not assignable to parameter of type 'EChartOption'.
  Object literal may only specify known properties, and 'brush' does not exist in type 'EChartOption'.

ERROR in [at-loader] ./app/containers/Widget/render/chart/sankey.ts:101:18
    TS2702: 'EChartOption' only refers to a type, but is being used as a namespace here.
Child html-webpack-plugin for "index.html":
     1 asset
Child html-webpack-plugin for "share.html":
     1 asset
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! davinci-webapp@0.3.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the davinci-webapp@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2019-03-27T16_58_25_594Z-debug.log

**Comment by AndyFong** [comment]
Try to use `cnpm` instead of `npm`.

**Comment by WilkinWendy** [comment]
> 我也遇到这个问题了，上面的解决办法都用过了，还是报错.
> 
> [at-loader] Checking finished with 2 errors
> Hash: bcc8cff1b19c20d7114b
> Version: webpack 3.5.5
> Time: 203141ms
> Asset Size Chunks Chunk Names
> edcdc8c88ddb2471a19d78705d0c9bf1.png 6.43 kB [emitted]
> 9ec5e40edddff9ff300e6791941fe869.eot 70.5 kB [emitted]
> 3a2ba31570920eeb9b1d217cabe58315.ttf 70.3 kB [emitted]
> de3f28fdd0af647ec0d2b1c22d845064.woff 37.3 kB [emitted]
> 5355ed90147de28ececc28a5376172ee.eot 26.4 kB [emitted]
> 0a9c32c5065b1a59d723766ccc6eb0b4.svg 127 kB [emitted]
> 88d025404e857f79062f2d95122a9108.ttf 26.2 kB [emitted]
> c6a72062dbbd6836f64c361099e023dc.png 9.38 kB [emitted]
> e6488e0deef4243bfca39c0cca5c73d5.png 10.2 kB [emitted]
> 036ed0f1aefe05c1da412d61336f0c74.png 14.4 kB [emitted]
> f0ec6d587973aa88c2e29b0b1c65c808.png 16.4 kB [emitted]
> d2b08fa3933fc618ca070eaf28345e87.png 16.1 kB [emitted]
> f653b5d0e9eb955bf923492e28c5d661.png 7.95 kB [emitted]
> 4634e042683621456707c7414609db06.png 9.12 kB [emitted]
> b955335f4f34391cef70c82e6149517c.png 11.1 kB [emitted]
> 0aa728803d97983f1ae1f7c6cc45e54a.png 12.6 kB [emitted]
> 3941a2931ff7a7890ab3f2a9b8f9353e.png 11.1 kB [emitted]
> 1ef9dd5efa26f427e345e6fe8f0f44ab.png 8.18 kB [emitted]
> 076cb037164072430388ae25f0dcacc3.png 5.96 kB [emitted]
> 45550d3d69c8b0d67fb13be4c12dda92.png 5.72 kB [emitted]
> ca5d4588dad9c32f49e895e7f19479df.svg 266 kB [emitted] [big]
> eca5185dce4a9ef9c63676d54c5078e2.png 9.32 kB [emitted]
> 57bff8887f24eaa28fb34254c65d90e8.png 6.53 kB [emitted]
> fd4cb43ebd00f4b629d9d48860f1f8fe.png 8.37 kB [emitted]
> 75873f6cbdd6bd2f758ef087a0c773df.png 25.8 kB [emitted]
> 4cc4900c2d9be838f7d9d5b6b087c600.png 5.55 kB [emitted]
> 288a6b2bf4dbd288124b27f9be8cf30c.png 8.53 kB [emitted]
> 90cd9a7a53eb8f6f78b2ebbd10f9c20c.png 104 bytes [emitted]
> 1c8e2633766f2fb8bda742b37e16169e.svg 2.69 kB [emitted]
> e92352b7d5694fd944eaa9e69ada160a.svg 2.86 kB [emitted]
> 6b49995ae3ae7870597e6843415551a0.svg 1.45 kB [emitted]
> c74f2afb0c9b2607c300a64420474865.png 1.18 kB [emitted]
> 947c3f17f9767ffbd1e40441036df0d5.png 1.21 kB [emitted]
> .htaccess.bin 1.52 kB [emitted]
> favicon.ico 4.29 kB [emitted]
> manifest.json 625 bytes [emitted]
> app.3214ed5a00d17439e64a.js 6.22 MB 0 [emitted] [big] app
> share.cf719df218a73caef935.js 3.9 MB 1 [emitted] [big] share
> index.html 1.75 kB [emitted]
> share.html 1.75 kB [emitted]
> 
> WARNING in ./node_modules/_moment@2.24.0@moment/src/lib/locale/locales.js
> Module not found: Error: Can't resolve './locale' in '\davinci\webapp\node_modules_moment@2.24.0@moment\src\lib\locale'
> @ ./node_modules/_moment@2.24.0@moment/src/lib/locale/locales.js 56:12-46
> @ ./node_modules/_moment@2.24.0@moment/src/lib/locale/locale.js
> @ ./node_modules/_moment@2.24.0@moment/src/moment.js
> @ ./app/components/Filters/FilterPanel.tsx
> @ ./app/containers/Dashboard/components/DashboardFilterPanel.tsx
> @ ./share/containers/Dashboard/index.tsx
> @ ./share/routes.ts
> @ ./share/app.tsx
> @ multi ./share/app.tsx
> 
> WARNING in ./node_modules/_antd@2.13.14@antd/lib/Button/button-group.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing. Compare these module identifiers:
> 
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Button\button-group.js
>   Used by 1 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Button\index.js
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\button\button-group.js
>   Used by 1 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\button\index.js
> 
> WARNING in ./node_modules/_antd@2.13.14@antd/lib/Button/button.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing. Compare these module identifiers:
> 
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Button\button.js
>   Used by 1 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Button\index.js
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\button\button.js
>   Used by 1 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\button\index.js
> 
> WARNING in ./node_modules/_antd@2.13.14@antd/lib/Button/index.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing. Compare these module identifiers:
> 
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Button\index.js
>   Used by 2 module(s), i. e.
>   \davinci\webapp\node_modules_awesome-typescript-loader@3.5.0@awesome-typescript-loader\dist\entry.js!\davinci\webapp\app\containers\Organizations\component\Setting.tsx
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\button\index.js
>   Used by 50 module(s), i. e.
>   \davinci\webapp\node_modules_babel-loader@7.1.0@babel-loader\lib\index.js!\davinci\webapp\app\containers\NoAuthorization\index.js
> 
> WARNING in ./node_modules/_antd@2.13.14@antd/lib/Form/Form.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing. Compare these module identifiers:
> 
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Form\Form.js
>   Used by 1 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Form\index.js
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\form\Form.js
>   Used by 1 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\form\index.js
> 
> WARNING in ./node_modules/_antd@2.13.14@antd/lib/Form/FormItem.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing. Compare these module identifiers:
> 
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Form\FormItem.js
>   Used by 1 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Form\Form.js
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\form\FormItem.js
>   Used by 1 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\form\Form.js
> 
> WARNING in ./node_modules/_antd@2.13.14@antd/lib/Form/constants.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing. Compare these module identifiers:
> 
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Form\constants.js
>   Used by 2 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Form\Form.js
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\form\constants.js
>   Used by 2 module(s), i. e.
>   \davinci\webapp\node_modules_antd@2.13.14@antd\lib\form\Form.js
> 
> WARNING in ./node_modules/_antd@2.13.14@antd/lib/Form/index.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing. Compare these module identifiers:
> 
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\Form\index.js
>   Used by 3 module(s), i. e.
>   \davinci\webapp\node_modules_awesome-typescript-loader@3.5.0@awesome-typescript-loader\dist\entry.js!\davinci\webapp\app\containers\Profile\index.tsx
> * \davinci\webapp\node_modules_antd@2.13.14@antd\lib\form\index.js
>   Used by 30 module(s), i. e.
>   \davinci\webapp\node_modules_awesome-typescript-loader@3.5.0@awesome-typescript-loader\dist\entry.js!\davinci\webapp\app\components\Filters\FilterPanel.tsx
> 
> ERROR in [at-loader] ./app/containers/Widget/components/Pivot/Chart.tsx:647:30
> TS2345: Argument of type '{ grid: any[]; xAxis: any[]; yAxis: any[]; series: any[]; brush: { toolbox: string[]; throttleTyp...' is not assignable to parameter of type 'EChartOption'.
> Object literal may only specify known properties, and 'brush' does not exist in type 'EChartOption'.
> 
> ERROR in [at-loader] ./app/containers/Widget/render/chart/sankey.ts:101:18
> TS2702: 'EChartOption' only refers to a type, but is being used as a namespace here.
> Child html-webpack-plugin for "index.html":
> 1 asset
> Child html-webpack-plugin for "share.html":
> 1 asset
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! davinci-webapp@0.3.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress --hide-modules --display-optimization-bailout`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the davinci-webapp@0.3.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\xxx\AppData\Roaming\npm-cache_logs\2019-03-27T16_58_25_594Z-debug.log

一直会报错的，但是按照上面我说的最后的做法，报错后依然可以生成打包代码，并且可以正常访问的

**Comment by PLDaily** [comment]
webapp 下编译会出错，但是能正常访问，换个名字比如aaa什么的编译就出错了，报错与https://github.com/edp963/davinci/issues/727#issuecomment-463481320  相同，也不能正常访问了。很神奇。。

```
node -v
v10.15.3

npm -v
6.4.1

yarn -v
1.6.0
```

**Comment by PLDaily** [comment]
webapp 下编译会出错，但是能正常访问，换个名字比如aaa什么的编译就出错了，报错与https://github.com/edp963/davinci/issues/727#issuecomment-463481320  相同，也不能正常访问了。很神奇。。

## 版本信息
```
node -v
v10.15.3

npm -v
6.4.1

yarn -v
1.6.0
```

## 执行步骤

```
yarn

yarn build

yarn start:prod
```

cnpm 与 npm 试了包都装不起来，用了yarn

**Comment by WilkinWendy** [comment]
@PLDaily  哈哈，我突然理解了为什么我把前端代码单独抽离到本地仓库再拉取，会不能正常访问了

**Comment by PLDaily** [comment]
@WilkinWendy  目录名一定要是webapp，其他的都不行，全局查看也找不到webapp哪里定义了，很神奇。你本地仓库名改成webapp 就可以build 了

**Comment by WilkinWendy** [comment]
@PLDaily  是的感谢大神找出了奇葩的原因，这个问题终于有close了

**Comment by legend91325** [comment]
没有人解释下为啥本地仓库名一定要webapp吗？

**Comment by WilkinWendy** [comment]
> 没有人解释下为啥本地仓库名一定要webapp吗？

2.0 版本没这问题了

**Comment by legend91325** [comment]
> Try to use `cnpm` instead of `npm`.

能解释下问什么仓库名一定是webapp 吗？我也遇到相同问题。

**Comment by AndyFong** [comment]
> > Try to use `cnpm` instead of `npm`.
> 
> 能解释下问什么仓库名一定是webapp 吗？我也遇到相同问题。
`webapp` is the sub directory of the repository, not the repository name.
