### ISSUE TITLE
求解master项目中 ico 是怎么引入的，我看到html里没有link呀。。

### ISSUE THREAD

**Issue by WilkinWendy** [edp963/davinci#733]

**Comment by AndyFong** [comment]
位于 `manifest.json` 文件中的配置

**Comment by WilkinWendy** [comment]
不知道是不是姿势不对，我测试manifest.json 特定条件下会发起文件请求，但是icon仍然没有，经调查想要不写icon的link就引入，也可以直接把favicon.ico配在网站根目录下(这个不同浏览器的兼容性也不同)

**Comment by AndyFong** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/Manifest  
FYI
