### ISSUE TITLE
bizlogics

### ISSUE THREAD

**Issue by Red12345678** [edp963/davinci#754]
bizlogics编辑页面左侧表没有下拉框，全部展示出来了

**Comment by AndyFong** [comment]
还请贴图详细说明下

**Comment by Red12345678** [comment]
> 还请贴图详细说明下
![default](https://user-images.githubusercontent.com/46362541/53624100-061f6000-3c3a-11e9-9131-89dba88dcc2a.png)

**Comment by AndyFong** [comment]
看界面是二次开发的吧，还请排查下 CSS 样式是否有问题
