### ISSUE TITLE
webpack设置代理不生效

### ISSUE THREAD

**Issue by dingluoneu** [edp963/davinci#759]
可以看到，addDevMiddlewares.js中设置了代理，但为什么npm start启服务以后不生效呢？
(https://github.com/edp963/davinci/blob/3c3111d752dfbb2ad34798dfc55f9a929663022a/webapp/server/middlewares/addDevMiddlewares.js#L21)

**Comment by AndyFong** [comment]
请确认本地是否有 8080 端口的接口服务
