### ISSUE TITLE
Cannot fetch shcema of datasource(DB) when creating "View"

### ISSUE THREAD

**Issue by youblade** [edp963/davinci#760]
react16 分支
功能 View List 页面创建 View 时，选择 Source 无法获取其 schema ，前端报错找不到对应的后端接口（如下图）
![image](https://user-images.githubusercontent.com/4941967/53854553-db9c2100-4004-11e9-9ab1-e40f30b88b5c.png)

查找后端代码，找到该接口URL对应的 Controller 为SourceController（如下图）
![image](https://user-images.githubusercontent.com/4941967/53854581-fe2e3a00-4004-11e9-8450-539c56a9f817.png)

但是 SourceController 代码中找不到该 URL mapping对应的接口
![image](https://user-images.githubusercontent.com/4941967/53854704-7a288200-4005-11e9-88db-1a01f0e536f7.png)

PS：Github 上源代码搜索也找不到该接口
![image](https://user-images.githubusercontent.com/4941967/53854669-58c79600-4005-11e9-8e80-a0c4f562a6bd.png)

实际上该接口在 ViewController中
![image](https://user-images.githubusercontent.com/4941967/53854757-af34d480-4005-11e9-83cb-bea0515d6623.png)

**Comment by AndyFong** [comment]
@shanmengm @yuhouchuhe1 
FYI

**Comment by AndyFong** [comment]
Please use latest code in branch `dev-0.3`
