### ISSUE TITLE
打包成功，启动时卡住不动了。

### ISSUE THREAD

**Issue by finoblack** [edp963/davinci#762]
![image](https://user-images.githubusercontent.com/48195870/53860676-bc10f280-401c-11e9-86a7-1a8a17d9210e.png)
如图卡住不动了

**Comment by youblade** [comment]
正常启动最后一条日志就是这样吧，你浏览器访问下应用是否正常额

**Comment by finoblack** [comment]
http://192.168.199.6:8080/我用这个地址访问不了哦，前面的ip就是我部署davinci的服务器。而且防火墙让我关了。
