### ISSUE TITLE
刷新时显示“加载中...”略显生硬

### ISSUE THREAD

**Issue by noodles-dumplings** [edp963/davinci#766]
Dashboard中Widget刷新时背景显示“加载中...”感觉略突兀，效果如下：

![issue](https://user-images.githubusercontent.com/23393385/53965794-ce7a5180-412c-11e9-9828-8d6f4140fbfe.gif)

**Comment by scottsut** [comment]
目前还在努力做功能开发与迭代，功能优先，体验上的问题后续会集中优化

**Comment by noodles-dumplings** [comment]
> 目前还在努力做功能开发与迭代，功能优先，体验上的问题后续会集中优化

ok，辛苦
