### ISSUE TITLE
npm start 后报错 咋整？

### ISSUE THREAD

**Issue by owls0** [edp963/davinci#767]
![image](https://user-images.githubusercontent.com/37429155/54097290-6062b280-43ea-11e9-92ae-4dec7d4ae993.png)

**Comment by scottsut** [comment]
还没来得及处理的TS语法检查报错，不影响开发。

**Comment by LingLiYuki** [comment]
Please use English for issues.
From now on, we close the issue in Chinese as soon as we see it.
Thanks for cooperating.
