### ISSUE TITLE
Bar、Pie and Line can not show

### ISSUE THREAD

**Issue by LiYanGang** [edp963/davinci#770]
when I create a new widget like Pie ,It can not show anything, but no errors in the console
![图片](https://user-images.githubusercontent.com/20022163/54105349-b5fc8680-440d-11e9-92cc-8be3840876cf.png)

**Comment by scottsut** [comment]
Can you give us more detail about this view？
Just like this:
![image](https://user-images.githubusercontent.com/4098913/54108613-602cdc00-4417-11e9-9045-cad2bd4a27c3.png)

**Comment by LiYanGang** [comment]
I have fixed this bug.Unable to render due to a value field error。thanks
