### ISSUE TITLE
can't init mysql database

### ISSUE THREAD

**Issue by dawsongzhao** [edp963/davinci#771]
`[root@xxxx01-dev bin]# sh initdb.sh
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1418 (HY000) at line 332: This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)`

**Comment by shanmengm** [comment]
The current version uses the MYSQL Stored Procedure. You need to set `log_bin_trust_function_creators = 1` in the my.cnf or my.ini.
We will not use MYSQL Stored Procedure in the next version.

**Comment by dawsongzhao** [comment]
@shanmengm 3Q; i fixed it by closing mysql binlog function.
