### ISSUE TITLE
Can't get hive database by presto jdbc

### ISSUE THREAD

**Issue by dawsongzhao** [edp963/davinci#782]
## Steps
- add presto-jdbc-0.217.jar to "lib" dir;
- restart davinci;
- add datasource and test connect ok;
- add view and select 'presto datasource', there is no schema list .

![image](https://user-images.githubusercontent.com/7078308/54340461-5f43b680-4672-11e9-9ec9-761c22268fc9.jpeg)

**Comment by phillip2019** [comment]
How can I solve this problem
