### ISSUE TITLE
can't refresh schema list when last datasource has error[BUG]

### ISSUE THREAD

**Issue by dawsongzhao** [edp963/davinci#783]
## Setps
- open chrome browse
- add presto datasource, test connecting is ok;
- add mysql datasource, test connecting is ok;
- add view by selecting mysql-datasource, it is listing schemas in mysql database;
- but switch presto datasource, it get error, and can't get schemas.so it shows schemas in mysql database;
![image](https://user-images.githubusercontent.com/7078308/54340968-9797c480-4673-11e9-9eda-f878fd2d8d66.jpeg)
![image](https://user-images.githubusercontent.com/7078308/54341596-26f1a780-4675-11e9-8087-7d4032c1741d.jpeg)
![image](https://user-images.githubusercontent.com/7078308/54341616-33760000-4675-11e9-9e64-d5d62e9e99cf.jpeg)

**Comment by AndyFong** [comment]
Confirm this bug still exists whether or not in beta 6 version. @dawsongzhao

**Comment by phillip2019** [comment]
The problem still exists
