### ISSUE TITLE
how to configure the ldap with using Microsoft AD Server ?

### ISSUE THREAD

**Issue by yiliangsangeren** [edp963/davinci#786]
ldap:
urls: 192.168..16.152:389  ----- My AD server Address
username: admin....
password: Dfg#7....
base: CN=ldap,CN=Users,DC=eok,DC=com
domainName: @eok.com

**Comment by yiliangsangeren** [comment]
error message when startup server: ==========================================
Starting..., press `CRTL + C` to exit log
==========================================
18:42:18.042 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
18:42:18.044 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
18:42:18.044 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
18:42:18.044 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
18:42:18.236 [background-preinit] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
18:42:18.243 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
18:42:18.244 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.JPATraversableResolver as ValidatorFactory-scoped traversable resolver.
18:42:18.244 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
18:42:18.244 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
18:42:18.244 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.

**Comment by shanmengm** [comment]
1. The ERROR LOG has nothing to do with the configuration of LDAP. Your configuration file was not filled in according to the specified format. YMAL file format requires at least one space between the colon after key and value.

2. The current version of the LDAP service only provides interfaces, we will fix and improve it in future versions.
