### ISSUE TITLE
Does Davinci support single sign-on ( SSO)?

### ISSUE THREAD

**Issue by hotbird3** [edp963/davinci#791]
希望通过另一个系统跳转至Davinci，请问是否支持单点登录？

**Comment by AndyFong** [comment]
Davinci 是基于 jwt 的 token 验证，原理上如果外部系统根据其登录用户能提供合法的 token 则就可以使用 Davinci 服务。  
Davinci 登录后在浏览器 localStorage 中赋值 token 作为后续每次接口请求的身份验证使用，若外部系统与 Davinci 部署于同一域下，则外部系统可以操作 localStorage 中的 token，使 Davinci 前端获取到而使 Davinci 免登，整体上实现单点登录。

**Comment by fumiwork** [comment]
English please...

**Comment by mathilda2** [comment]
> English please...

你让别人用英语提问吗

**Comment by mathilda2** [comment]
> 希望通过另一个系统跳转至Davinci，请问是否支持单点登录？

你现在弄好了吗

**Comment by redfeng** [comment]
分享能授权到角色吗？

**Comment by redfeng** [comment]
集成的方式有点奇怪，分享不安全吧
