### ISSUE TITLE
throw Error when npm install 

### ISSUE THREAD

**Issue by ZJane** [edp963/davinci#797]
![image](https://user-images.githubusercontent.com/22131320/54968591-38607b00-4fb6-11e9-9aec-8dddda51fa18.png)

**Comment by ZJane** [comment]
拉取项目，执行npm install 到一半，突然报错说无系统权限？？

**Comment by AndyFong** [comment]
Try to reopen the cmd window in administrator mode.

**Comment by scottsut** [comment]
Not a Davinci problem. Check your system user permissions.
