### ISSUE TITLE
【Widget】 charts  can not show 

### ISSUE THREAD

**Issue by ZJane** [edp963/davinci#800]
![image](https://user-images.githubusercontent.com/22131320/55047476-e2580a00-507f-11e9-9054-1f8243449bd4.png)
在Widget页面选择view后，设置维度和指标后，无法展示图表（表格），前端终端报错如上图。

**Comment by AndyFong** [comment]
You should check the error info in the console panel of Chrome (press `F12`), not in the cmd window.

**Comment by ZJane** [comment]
![1049783701](https://user-images.githubusercontent.com/22131320/55125257-1694fe80-5144-11e9-8926-f28f171b04d2.jpg)
![2109494460](https://user-images.githubusercontent.com/22131320/55125294-33313680-5144-11e9-9a58-3a270dfddad5.jpg)
![17952799](https://user-images.githubusercontent.com/22131320/55125299-3af0db00-5144-11e9-895e-28d6f5f339d6.jpg)
I am sorry that I can give a shot. I get the error info  like the photos.

**Comment by AndyFong** [comment]
It must be the problem from old version widget data, try to recreate the widget.

**Comment by ZJane** [comment]
It happened when I add a new widget.

**Comment by kingpeixin** [comment]
to recreate the widget tabke data ,where is this sql?

**Comment by feiyuxy** [comment]
不能起字段名为指标名称
