### ISSUE TITLE
Can query statements be assembled automatically by drag-and-drop metrics instead of writing SQL

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#802]
Can query statements be assembled automatically by drag-and-drop metrics instead of writing SQL

**Comment by AndyFong** [comment]
We have no plan to support this currently.   
The way of create view by writing SQL has its pros, cause you can manipulate the edit more free  and have less limits by using all the features that SQL offers to us, SQL is really a powerful language, which can not be replaced well by the drag-and-drop operations.  
But it also brings the requirement to user that they must be familiar with SQL (the basic usage at least), which might be unfriendly to those who do not have the background of coding.  
However, `Davinci` is a cooperating platform, it can have multiple roles in a project, so we can distribute the right permission, including edit or just looking up of `Source`, `View`, `Viz`, `Schedule`,  to the corresponding user in a project.
