### ISSUE TITLE
data of table “mem_dashboard_widget” is empty

### ISSUE THREAD

**Issue by kingpeixin** [edp963/davinci#805]
hello,team,
    I import the davinci.sql into mysql sucess,but the data of table "mem_dashboard_widget" is empty,so i cannot add the widget for next step in the dashboard,please tell me where is  the init data “mem_dashboard_widget” sql ?

**Comment by AndyFong** [comment]
The data of table `mem_dashboard_widget` comes from the creating operation in Davinci Dashboard page by click the `Add` button in the top left corner and then add widget to the Dashboard.  
It is user generated data so the table in database does not have any data from the start of system deployment.

**Comment by kingpeixin** [comment]
got it ,it does work ,thank u very much
