### ISSUE TITLE
How to pack this project?

### ISSUE THREAD

**Issue by xungegeblue** [edp963/davinci#806]
This project uses assembly, which I don't understand, so ask how to pack it.

**Comment by xungegeblue** [comment]
[INFO] --- maven-assembly-plugin:3.0.0:single (dist) @ davinci-assembly_3.0.1 ---
[INFO] Reading assembly descriptor: src/main/assembly/assembly.xml
[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /

**Comment by shanmengm** [comment]
Package it in the root directory

**Comment by xungegeblue** [comment]
The problem has been solved. Thank you very much.

**Comment by 9527zk** [comment]
> [INFO] --- maven-assembly-plugin:3.0.0:single (dist) @ davinci-assembly_3.0.1 ---
> [INFO] Reading assembly descriptor: src/main/assembly/assembly.xml
> [ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash)
can you des how to resolve;i meet this problem too ,but donot know how to fix it
