### ISSUE TITLE
Davinci dose not support the json functions of Mysql,like json_extract() etc.

### ISSUE THREAD

**Issue by EasonZhouV5** [edp963/davinci#807]
![image](https://user-images.githubusercontent.com/20152808/55287851-17968c00-53e1-11e9-89b6-accb934f95d0.png)
it same that stringtemplate-4.0 doesn't support these json functions, is there any idea to solve this issue?

**Comment by shanmengm** [comment]
Davinci defaults to `$` as delimiter and you can escape it， for example, you can change your SQL like this：
```
select json_extract('{"name": "Zhaim"}', "\$.name")
```

**Comment by EasonZhouV5** [comment]
Got it. Thanks.
