### ISSUE TITLE
webapp package error

### ISSUE THREAD

**Issue by xungegeblue** [edp963/davinci#809]
ERROR in ./node_modules/react/lib/ReactComponentTreeHook.js
Module not found: Error: Can't resolve './ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react\lib'
 @ ./node_modules/react/lib/ReactComponentTreeHook.js 16:24-54
 @ ./node_modules/react-dom/lib/flattenChildren.js
 @ ./node_modules/react-dom/lib/ReactMultiChild.js
 @ ./node_modules/react-dom/lib/ReactDOMComponent.js
 @ ./node_modules/react-dom/lib/ReactDefaultInjection.js
 @ ./node_modules/react-dom/lib/ReactDOM.js
 @ ./node_modules/react-dom/index.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react/lib/ReactElement.js
Module not found: Error: Can't resolve './ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react\lib'
 @ ./node_modules/react/lib/ReactElement.js 15:24-54
 @ ./node_modules/react/lib/onlyChild.js
 @ ./node_modules/react/lib/React.js
 @ ./node_modules/react/react.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react/lib/traverseAllChildren.js
Module not found: Error: Can't resolve './ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react\lib'
 @ ./node_modules/react/lib/traverseAllChildren.js 15:24-54
 @ ./node_modules/react/lib/ReactChildren.js
 @ ./node_modules/react/lib/React.js
 @ ./node_modules/react/react.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react/lib/ReactElement.js
Module not found: Error: Can't resolve './ReactElementSymbol' in 'D:\code\bi\davinci\webapp\node_modules\react\lib'
 @ ./node_modules/react/lib/ReactElement.js 21:25-56
 @ ./node_modules/react/lib/onlyChild.js
 @ ./node_modules/react/lib/React.js
 @ ./node_modules/react/react.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react/lib/traverseAllChildren.js
Module not found: Error: Can't resolve './ReactElementSymbol' in 'D:\code\bi\davinci\webapp\node_modules\react\lib'
 @ ./node_modules/react/lib/traverseAllChildren.js 16:25-56
 @ ./node_modules/react/lib/ReactChildren.js
 @ ./node_modules/react/lib/React.js
 @ ./node_modules/react/react.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react/lib/ReactBaseClasses.js
Module not found: Error: Can't resolve './canDefineProperty' in 'D:\code\bi\davinci\webapp\node_modules\react\lib'
 @ ./node_modules/react/lib/ReactBaseClasses.js 18:24-54
 @ ./node_modules/react/lib/React.js
 @ ./node_modules/react/react.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react/lib/ReactElement.js
Module not found: Error: Can't resolve './canDefineProperty' in 'D:\code\bi\davinci\webapp\node_modules\react\lib'
 @ ./node_modules/react/lib/ReactElement.js 18:24-54
 @ ./node_modules/react/lib/onlyChild.js
 @ ./node_modules/react/lib/React.js
 @ ./node_modules/react/react.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react-dom/lib/findDOMNode.js
Module not found: Error: Can't resolve 'react/lib/ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react-dom\lib'
 @ ./node_modules/react-dom/lib/findDOMNode.js 13:24-62
 @ ./node_modules/react-dom/lib/ReactDOM.js
 @ ./node_modules/react-dom/index.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react-dom/lib/ReactUpdateQueue.js
Module not found: Error: Can't resolve 'react/lib/ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react-dom\lib'
 @ ./node_modules/react-dom/lib/ReactUpdateQueue.js 13:24-62
 @ ./node_modules/react-dom/lib/ReactReconcileTransaction.js
 @ ./node_modules/react-dom/lib/ReactDefaultInjection.js
 @ ./node_modules/react-dom/lib/ReactDOM.js
 @ ./node_modules/react-dom/index.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react-dom/lib/ReactMultiChild.js
Module not found: Error: Can't resolve 'react/lib/ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react-dom\lib'
 @ ./node_modules/react-dom/lib/ReactMultiChild.js 17:24-62
 @ ./node_modules/react-dom/lib/ReactDOMComponent.js
 @ ./node_modules/react-dom/lib/ReactDefaultInjection.js
 @ ./node_modules/react-dom/lib/ReactDOM.js
 @ ./node_modules/react-dom/index.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react-dom/lib/ReactCompositeComponent.js
Module not found: Error: Can't resolve 'react/lib/ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react-dom\lib'
 @ ./node_modules/react-dom/lib/ReactCompositeComponent.js 16:24-62
 @ ./node_modules/react-dom/lib/instantiateReactComponent.js
 @ ./node_modules/react-dom/lib/ReactMount.js
 @ ./node_modules/react-dom/lib/ReactDOM.js
 @ ./node_modules/react-dom/index.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react-dom/lib/traverseAllChildren.js
Module not found: Error: Can't resolve 'react/lib/ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react-dom\lib'
 @ ./node_modules/react-dom/lib/traverseAllChildren.js 13:24-62
 @ ./node_modules/react-dom/lib/ReactChildReconciler.js
 @ ./node_modules/react-dom/lib/ReactMultiChild.js
 @ ./node_modules/react-dom/lib/ReactDOMComponent.js
 @ ./node_modules/react-dom/lib/ReactDefaultInjection.js
 @ ./node_modules/react-dom/lib/ReactDOM.js
 @ ./node_modules/react-dom/index.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in ./node_modules/react-dom/lib/ReactMount.js
Module not found: Error: Can't resolve 'react/lib/ReactCurrentOwner' in 'D:\code\bi\davinci\webapp\node_modules\react-dom\lib'
 @ ./node_modules/react-dom/lib/ReactMount.js 17:24-62
 @ ./node_modules/react-dom/lib/ReactDOM.js
 @ ./node_modules/react-dom/index.js
 @ ./app/app.tsx
 @ multi ./app/app.tsx

ERROR in [at-loader] ./app/app.tsx:106:5 
    TS2605: JSX element type 'Provider' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/app.tsx:106:5 
    TS2605: JSX element type 'Provider' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): false | Element; (): ReactNode; (): ReactNode; (): ReactNode; (): ReactNode; }'.
      Type 'ReactNode' is not assignable to type 'false | Element'.
        Type 'string' is not assignable to type 'false | Element'.

ERROR in [at-loader] ./app/app.tsx:107:7 
    TS2605: JSX element type 'Component<Pick<ILanguageProviderProps, "children" | "locale" | "messages" | "key"> & ILanguagePro...' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/app.tsx:107:7 
    TS2605: JSX element type 'Component<Pick<ILanguageProviderProps, "children" | "locale" | "messages" | "key"> & ILanguagePro...' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): false | Element; (): ReactNode; (): ReactNode; (): ReactNode; (): ReactNode; }'.
      Type 'ReactNode' is not assignable to type 'false | Element'.
        Type 'string' is not assignable to type 'false | Element'.

ERROR in [at-loader] ./app/app.tsx:108:9 
    TS2605: JSX element type 'Component<RouterProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/app.tsx:108:9 
    TS2605: JSX element type 'Component<RouterProps, ComponentState, never>' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): false | Element; (): ReactNode; (): ReactNode; (): ReactNode; (): ReactNode; }'.
      Type 'ReactNode' is not assignable to type 'false | Element'.
        Type 'string' is not assignable to type 'false | Element'.

ERROR in [at-loader] ./app/components/SidebarOption/index.tsx:46:9 
    TS2605: JSX element type 'Component<LinkProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Account/components/Menus.tsx:21:9 
    TS2605: JSX element type 'Component<LinkProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/App/index.tsx:37:7 
    TS2605: JSX element type 'Helmet' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Bizlogic/index.tsx:229:9 
    TS2605: JSX element type 'Helmet' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Bizlogic/index.tsx:235:19 
    TS2605: JSX element type 'Component<LinkProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Dashboard/Grid.tsx:1203:9 
    TS2605: JSX element type 'Helmet' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Dashboard/Grid.tsx:1212:25 
    TS2605: JSX element type 'Component<LinkProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Dashboard/Grid.tsx:1224:25 
    TS2605: JSX element type 'Component<LinkProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Dashboard/index.tsx:688:9 
    TS2605: JSX element type 'Helmet' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Display/Editor.tsx:932:9 
    TS2605: JSX element type 'Helmet' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Display/Editor.tsx:933:9 
    TS2605: JSX element type 'Component<Pick<any, never> & IDisplayHeaderProps, ComponentState, never>' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): false | Element; (): ReactNode; (): ReactNode; (): ReactNode; (): ReactNode; }'.
      Type 'ReactNode' is not assignable to type 'false | Element'.
        Type 'string' is not assignable to type 'false | Element'.

ERROR in [at-loader] ./app/containers/Display/components/DisplayHeader.tsx:265:17 
    TS2605: JSX element type 'Component<LinkProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Display/index.tsx:213:9 
    TS2605: JSX element type 'Helmet' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Display/index.tsx:219:19 
    TS2605: JSX element type 'Component<LinkProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Group/index.tsx:284:9 
    TS2605: JSX element type 'Helmet' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Login/index.tsx:113:9 
    TS2605: JSX element type 'Helmet' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): false | Element; (): ReactNode; (): ReactNode; (): ReactNode; (): ReactNode; }'.
      Type 'ReactNode' is not assignable to type 'false | Element'.
        Type 'string' is not assignable to type 'false | Element'.

ERROR in [at-loader] ./app/containers/Organizations/Organization.tsx:246:17 
    TS2605: JSX element type 'Component<LinkProps, ComponentState, never>' is not a constructor function for JSX elements.

ERROR in [at-loader] ./app/containers/Organizations/Organization.tsx:296:15

**Comment by AndyFong** [comment]
retry to npm install  
`rm -rf ./node_modules`  
`npm i set registry=https://registry.npm.taobao.org/`

**Comment by xungegeblue** [comment]
Thank you very much. I'll try.

**Comment by xungegeblue** [comment]
I use yarn.
Use your method.
Build folder can be generated normally
Thanks very much
