### ISSUE TITLE
sh start-server.sh error

### ISSUE THREAD

**Issue by netesheng** [edp963/davinci#810]
sh start-server.sh
start-server.sh：23：start-server.sh：[[: not found

use davinci-assembly_3.0.1-0.3.0-SNAPSHOT-dist Release and no logs folder or log file

![QQ截图20190403182915](https://user-images.githubusercontent.com/9253891/55472435-aa803200-563e-11e9-82c7-1ef0687d5f61.jpg)

**Comment by AndyFong** [comment]
try `./start-server.sh` directly.
