### ISSUE TITLE
Whether to support drilling down

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#814]
Whether to support drilling down？how to use? thank you

**Comment by AndyFong** [comment]
`Davinci` does support drill-down analysis with charts, but only in `Pivot` mode currently.  
In our roadmap,  `Davinci` will fully support drill-down feature in both `Pivot` and `Chart` mode, and also with specific path (will be set by users themselves in advance) and free drill-down support.

**Comment by tjthink** [comment]
Where do I need to set it? I can't find it. Are there any examples?  thank you.

**Comment by AndyFong** [comment]
As the description above, we support drill-down feature partially, it supports free drill-down with `Widget` in `Pivot` mode, which means you do not need to set it in advance.  

Here are the steps,  
1. add a `Widget` in `Pivot` mode
2. add it to a `Dashboard`
3. click the drill-down **icon button** in **top right corner**, where the toolbar located, of the dashboard item when **hovering** it
4. now you are in  drill-down mode, and you can start to drill with mouse drag and click operations

**Comment by tjthink** [comment]
yes, i do like that, but 
![image](https://user-images.githubusercontent.com/5283107/55771667-8d72b580-5abb-11e9-89e4-70e6f88f4a48.png),
so i'm confused.

**Comment by AndyFong** [comment]
@ruanhan

**Comment by ruanhan** [comment]
In fact, we only have drill on charts in some specific modes. it’s on  dev-0.3.
because of the adjustment of past work plans, the  development of the drill has been shelved. 
For the next time, I will  refactor these drill functions. And other features released in the next release.

**Comment by tjthink** [comment]
ok

**Comment by jackalkln** [comment]
what's the plan of drill function? when can it be released?
