### ISSUE TITLE
Why remove video and time components from display pages

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#815]
Why remove video and time components from display pages

**Comment by AndyFong** [comment]
We do not remove these two types of component, if these components do not be shown on `Display`, it might be caused by kind of bugs.

**Comment by tjthink** [comment]
I used davinci0.3, but have been removed.

![image](https://user-images.githubusercontent.com/5283107/55771031-002e6180-5ab9-11e9-8c67-1b3318878487.png)
![image](https://user-images.githubusercontent.com/5283107/55771060-150af500-5ab9-11e9-8bae-88d087694b78.png)

**Comment by AndyFong** [comment]
https://github.com/edp963/davinci/blob/dev-0.3/webapp/app/containers/Display/components/util.ts#L33

**Comment by tjthink** [comment]
maybe my version is old
