### ISSUE TITLE
In version 0.3, when the front end deploys itself, the display page does not have a property panel.

### ISSUE THREAD

**Issue by sq8852161** [edp963/davinci#816]
![davinci-display](https://user-images.githubusercontent.com/9211058/55779118-3d095100-5ad7-11e9-89f7-c8a17c31716a.PNG)

**Comment by scottsut** [comment]
Caused by chrome updates, will fix in next release.

**Comment by AndyFong** [comment]
Fixed in 0.3.0-beta-5 version
