### ISSUE TITLE
in master, when add team is error

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#820]
![image](https://user-images.githubusercontent.com/5283107/55792691-c038a000-5af3-11e9-9312-d766ee3c4940.png)

![image](https://user-images.githubusercontent.com/5283107/55792673-b44cde00-5af3-11e9-8523-84f3d8cec8c1.png)

**Comment by scottsut** [comment]
Check if the mysql procedure 'parentTeamIds' is executed correctly.
￼
<img width="770" alt="screenshot" src="https://user-images.githubusercontent.com/4098913/56780286-43a30280-6811-11e9-8cc2-169666a9c696.png">

**Comment by AndyFong** [comment]
`Team` has been remove in 0.3.0-beta-5 version
