### ISSUE TITLE
in master, when add View, the Data page, Field type can't selected

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#821]
use oralce
![image](https://user-images.githubusercontent.com/5283107/55793605-e8290300-5af5-11e9-87a7-d989e23420fe.png)

**Comment by RedA1ert** [comment]
sql中使用中文作为别名，返回值乱码，请问您是怎么解决的 ？

**Comment by AndyFong** [comment]
View editing page has been refactored in 0.3.0-beta-5 version, if you find the problem still exists in this version, please open a new issue.
