### ISSUE TITLE
in master, build error

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#823]
![image](https://user-images.githubusercontent.com/5283107/55798704-36440380-5b02-11e9-8fee-8478086adf63.png)

**Comment by AndyFong** [comment]
#727

**Comment by tjthink** [comment]
Compile error still
![image](https://user-images.githubusercontent.com/5283107/55924724-9c817100-5c3d-11e9-988f-0ed3799b7e00.png)

**Comment by iceflag** [comment]
I also have the same issue. in latest version of master.
cnpm  version 6.0.0 
npm version 6.9.0 
node version 10.15.3 
npm install version 3.20.2

**Comment by AndyFong** [comment]
TypeScript typing errors do not effect the build.
