### ISSUE TITLE
大屏管理（Display）中，图层及背景设置功能缺失

### ISSUE THREAD

**Issue by a447987428** [edp963/davinci#826]
大屏管理（Display）中，图层及背景设置功能缺失
![image](https://user-images.githubusercontent.com/16891124/55950643-f73fba80-5c87-11e9-975c-0127bff721d5.png)
 正确示例（见下图蓝色文字）： 
![image](https://user-images.githubusercontent.com/16891124/55950650-fad34180-5c87-11e9-9baf-0b6a756bfb17.png)

**Comment by scottsut** [comment]
Caused by chrome updates, will fix in next release.

**Comment by AndyFong** [comment]
#827
