### ISSUE TITLE
in master, schedule cronExpression is wrong

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#829]
when edit, fill in like this
![image](https://user-images.githubusercontent.com/5283107/56023779-43026a80-5d41-11e9-93ad-5b54baa638c1.png)

but final like this
![image](https://user-images.githubusercontent.com/5283107/56023905-82c95200-5d41-11e9-8c4d-4c858721def6.png)

**Comment by AndyFong** [comment]
`Davinci` uses `cron expression` to describe the execution time of schedule. [Here is a website](http://www.cronmaker.com/) that you can generate and test `cron expression`.   

But by the screenshots you post, they do not match.  
By the example you give, I test it on the `Davinci`, here is the result:   

![image](https://user-images.githubusercontent.com/6837655/56074410-64686280-5de4-11e9-80d5-d64e138d257e.png)

![image](https://user-images.githubusercontent.com/6837655/56074446-4bac7c80-5de5-11e9-8518-f2980427ab1b.png)

Please check it to confirm it's a screenshot misoperation or  a potential `Davinci` bug.
