### ISSUE TITLE
yarn and yarn run build,package in webapp have wrong?how packge

### ISSUE THREAD

**Issue by JiaNan-168** [edp963/davinci#831]

**Comment by zhenchuan** [comment]
step 1.  npm/cnpm install
step 2. yarn build

**Comment by JiaNan-168** [comment]
WARNING in ./node_modules/antd/node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'C:\Users\DYB\Desktop\last\webapp\node_modules\antd\node_modules\moment\src\lib\locale'
 @ ./node_modules/antd/node_modules/moment/src/lib/locale/locales.js 56:12-46
 @ ./node_modules/antd/node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/antd/node_modules/moment/src/moment.js
 @ ./node_modules/antd/lib/date-picker/RangePicker.js
 @ ./node_modules/antd/lib/date-picker/index.js
 @ ./app/containers/Dashboard/components/DashboardItemControlForm.tsx
 @ ./app/containers/Dashboard/components/fullScreenPanel/FullScreenPanel.tsx
 @ ./share/containers/Dashboard/index.tsx
 @ ./share/routes.ts
 @ ./share/app.tsx
 @ multi ./share/app.tsx


WARNING in ./node_modules/antd/lib/Button/button.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\DYB\Desktop\last\webapp\node_modules\antd\lib\Button\button.js
    Used by 1 module(s), i. e.
    C:\Users\DYB\Desktop\last\webapp\node_modules\antd\lib\Button\index.js
* C:\Users\DYB\Desktop\last\webapp\node_modules\antd\lib\button\button.js
    Used by 1 module(s), i. e.
    C:\Users\DYB\Desktop\last\webapp\node_modules\antd\lib\button\index.js

ERROR in [at-loader] ./app/containers/Widget/components/Pivot/Chart.tsx:647:30 
    TS2345: Argument of type '{ grid: any[]; xAxis: any[]; yAxis: any[]; series: any[]; brush: { toolbox: string[]; throttleTyp...' is not assignable to parameter of type 'EChartOption'.
  Object literal may only specify known properties, and 'brush' does not exist in type 'EChartOption'.
Child html-webpack-plugin for "index.html":
     1 asset
Child html-webpack-plugin for "share.html":
     1 asset

**Comment by JiaNan-168** [comment]
> step 1. npm/cnpm install
> step 2. yarn build

iI have try ,have two warning and one error

**Comment by scottsut** [comment]
After we use typescript, we recommend using npm instead of yarn. Yarn may cause nested dependencies
