### ISSUE TITLE
in branch dev-0.3 , use DateFilter plug have err in Dashboard

### ISSUE THREAD

**Issue by iceflag** [edp963/davinci#835]
1.use the DateFilter plug-in in dashboard. 
2.choose Date  
![image](https://user-images.githubusercontent.com/3365611/56401345-eba55280-628a-11e9-9159-85fc69e251cf.png)

**Comment by AndyFong** [comment]
Please provide detailed operating descriptions for each step.

**Comment by iceflag** [comment]
1. 创建看板（create dashboard)
2. 添加全局过滤器(add global filters）
3. 选择时间类型过滤器（select Date filter)
4.在看板中使用时间过滤控件，选择一个时间 (select any Date )

**Comment by scottsut** [comment]
Looks like a build problem. Please use Node10 LTS version and npm to build frontend project.
