### ISSUE TITLE
in tag  v0.3.0-beta.4 webapp proxy is invalid

### ISSUE THREAD

**Issue by victorzwp** [edp963/davinci#836]
hi,i download v0.3.0-beta.4 source,then open webapp use webstorm , after run the webapp ,by cannnot send  request to proxy url successfull.
but ,when run the webapp ,the console log show [HPM] Proxy created: /  ->  http://xxxxx:8080/ ,
i cannot find the reason

**Comment by AndyFong** [comment]
The default proxy address of `Davinci` api is `http://localhost:8080/`, the path of the config file is 
 `webapp/server/middlewares/addDevMiddlewares.js`, you can change it to a proper value that corresponding to your exact server address.

**Comment by victorzwp** [comment]
Tks,I have do this,but it does not work,my server service is ok, Is it working properly in your environment?

**Comment by AndyFong** [comment]
Yes, make sure that you have installed npm packages properly.

**Comment by victorzwp** [comment]
hello，I found that the path in target cannot be configured with  `http://localhost:8080/api/v3`

To configure it to `http://localhost:8080/` now it works.

**Comment by weishaodaren** [comment]
mine too, I changed proxy in the addDevMiddlewares.js and termial did work, but request always http://localhost:5002
![BDFBB9EB-DF71-413c-AAC9-EE7CABB0A441](http
![F61898AD-09BB-499e-B4BD-97855B5F34BE](https://user-images.githubusercontent.com/45391716/90124749-7de03c80-dd93-11ea-9318-0c9ac9dbbd12.png)
![3ACCE2D0-269E-45aa-AEE6-94E22F1FDF63](https://user-images.githubusercontent.com/45391716/90124830-9bada180-dd93-11ea-864d-746289fa2dd6.png)

s://user-images.githubusercontent.com/45391716/90124653-56896f80-dd93-11ea-9f78-51e7e83ad252.png)
