### ISSUE TITLE
in master,  ambiguous column naming in select list

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#837]
![image](https://user-images.githubusercontent.com/5283107/56412875-3093ae00-62b8-11e9-827b-2186ed43c1bc.png)

**Comment by AndyFong** [comment]
It seems that you are editing a pie widget from a Oracle database, which can not select multiple same columns in one select sql.  In this case, column [民族] is selected by twice. Remove dimension [民族] and keep [民族] in color and it will work.

**Comment by tjthink** [comment]
Wow, can do like this, np
