### ISSUE TITLE
in master, bar chart Legend Not Displayed

### ISSUE THREAD

**Issue by tjthink** [edp963/davinci#838]
![image](https://user-images.githubusercontent.com/5283107/56413099-e959ed00-62b8-11e9-9723-0efb398fe8e8.png)

**Comment by AndyFong** [comment]
Could you post the screenshot of Tab data setting?

**Comment by tjthink** [comment]
yes, like this
![image](https://user-images.githubusercontent.com/5283107/56479830-f873b180-64e9-11e9-9b6b-344d0a7a75ed.png)

**Comment by lawrencehjf** [comment]
拖动民族到“颜色”栏

**Comment by AndyFong** [comment]
Single dimension dose not have legend, if you really want to show a legend, you can use the method by move the dimension from dimension panel to color panel to show the legend.
