### ISSUE TITLE
in master, radar chart Legend Not Displayed

### ISSUE THREAD

**Issue by a447987428** [edp963/davinci#841]
1.the first step，create a radar chart，like this
![image](https://user-images.githubusercontent.com/16891124/56485841-341d7400-6508-11e9-86a1-b2e99fcbf7f6.png)
2.the second step，save the widget.
3.reopen the widget, it can't display. You can see a blank screen.

**Comment by AndyFong** [comment]
In which branch?

**Comment by a447987428** [comment]
> In which branch?

dev-0.3

**Comment by AndyFong** [comment]
#850
