### ISSUE TITLE
I need a double Y axis to show the data with different precision

### ISSUE THREAD

**Issue by a447987428** [edp963/davinci#842]
For example，the first axis has mega data，like 100,000 dollars，the second axis has few data，like 75%. 
I can't see the second axis,it shows a parallel lines to me.
![image](https://user-images.githubusercontent.com/16891124/56486481-50baab80-650a-11e9-81b2-ed18170307ce.png)

**Comment by scottsut** [comment]
Will support in next release.

**Comment by ruanhan** [comment]
It's Supported.
