### ISSUE TITLE
In bar chart and line chart, multidimensionality and stacking are not supported

### ISSUE THREAD

**Issue by a447987428** [edp963/davinci#843]
![image](https://user-images.githubusercontent.com/16891124/56486689-0dad0800-650b-11e9-8800-39c800ff1f82.png)

I need the chart below
![image](https://user-images.githubusercontent.com/16891124/56486720-346b3e80-650b-11e9-83ff-6d95f90543a8.png)
![image](https://user-images.githubusercontent.com/16891124/56486722-36cd9880-650b-11e9-9f4f-834ee31b3ca6.png)

**Comment by ruanhan** [comment]
![image](https://user-images.githubusercontent.com/11482353/58679610-df86d780-8396-11e9-83ce-c586f505c0ae.png)

As same as line.
