### ISSUE TITLE
when the display has lots of widget,it needs a scrollbar

### ISSUE THREAD

**Issue by a447987428** [edp963/davinci#844]

**Comment by a447987428** [comment]
when the display has lots of widget,it needs a scrollbar or I can't see all the widgets completely and clearly.
![image](https://user-images.githubusercontent.com/16891124/56494803-18c16180-6526-11e9-8a7a-e4065d19b534.png)

**Comment by scottsut** [comment]
Caused by chrome updates, will fix in next release.

**Comment by AndyFong** [comment]
fixed in 0.3.0-beta-5 version
