### ISSUE TITLE
The question of Pivot and Charts

### ISSUE THREAD

**Issue by lzymax** [edp963/davinci#905]
What is the difference between these two modes in daily use?
Is it just some graphical difference?
![QQ图片20190521110222](https://user-images.githubusercontent.com/48306335/58065402-2ff07f00-7bb8-11e9-851d-2e8c0519a5c8.png)

**Comment by AndyFong** [comment]
https://zh.wikipedia.org/wiki/%E9%80%8F%E8%A7%86%E8%A1%A8
