### ISSUE TITLE
master branch. how to run the front code .

### ISSUE THREAD

**Issue by Vincent2015** [edp963/davinci#908]
1. down load the master branch code 
2.run the server DavinciServerApplication ok. it runs at 8080 port
"

![image](https://user-images.githubusercontent.com/6760575/58086265-e5d7bf80-7bf0-11e9-8601-446736c9c1df.png)
3.under the webapp dir, cnpm install and cnpm start,but the localhost:5002 show words only "Not found
![image](https://user-images.githubusercontent.com/6760575/58086344-07d14200-7bf1-11e9-8295-aad14f76a4e4.png)

![image](https://user-images.githubusercontent.com/6760575/58086306-f425db80-7bf0-11e9-962c-67fc02cf088e.png)

**Comment by Vincent2015** [comment]
@scottsut

**Comment by AndyFong** [comment]
Please wait until the console prints `webpack built XXX ms`

**Comment by Vincent2015** [comment]
> Please wait until the console prints `webpack built XXX ms`

thank you. if had one dev guide,that's very good.
