### ISSUE TITLE
schedule cannot screenshots,alert ReferenceError: Can't find variable: Proxy

### ISSUE THREAD

**Issue by waters321** [edp963/davinci#940]
/usr/local/bin/phantomjs /devtools/davinci/bin/phantom.js http://127.0.0.1:9999///share.html\#/share/dashboard\?shareInfo\=DA1C3E7DAF7EC46FDC39861F361C78B7517FC6CEF4F1ED425FFF75A2CB7527D3ABD4F0725AF12462EE9485E57D5234010C33F929668BC6DDE6D36426DD245BEC11B09934F87FA1D8A9969EC181C66A97505882525C1B90DAA8AF9BC321CA5D97B2A61355A235625968FC7D51AA20A6E9028C5418F60CA9F922D29C69AF58F9D043419A59BADDBEF1AF47E27705A851E0082330FCB5F8DCAF31ED3F082AB43E3142166BF6698FAA50F03574BC352254E32DC0F3AFCD0CA41593594205E0DD1C57BBF2D273ABF09D59DECA0979C6768107D20DC9527DA56D8720F832E7290BEF6B54A4A9331D6775A0825AC437E3C6EB38FD751F1B54622A30D3F0FAA533794447\&type\=dashboard /devtools/davinci/userfiles/tempFiles/201905/3b9f41bd-d449-4dfe-b3c0-196d15fa9a9a.png
ReferenceError: Can't find variable: Proxy

  http://127.0.0.1:9999/app~share.ed2c290e1285e257043f.chunk.js:1 in a
  http://127.0.0.1:9999/app~share.ed2c290e1285e257043f.chunk.js:1 in 88a09aae288902a34b11
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in a
  http://127.0.0.1:9999/app~share.ed2c290e1285e257043f.chunk.js:1 in 602b42c082df5da972c7
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in a
  http://127.0.0.1:9999/app~share.ed2c290e1285e257043f.chunk.js:1 in 4bb8fc755414fd86c195
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in a
  http://127.0.0.1:9999/app~share.ed2c290e1285e257043f.chunk.js:1 in cd16e7d68404f3230c38
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in a
  http://127.0.0.1:9999/share.fc81e373fef6c8f6e658.chunk.js:1 in 162badf8105dc7af2987
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in a
  http://127.0.0.1:9999/share.fc81e373fef6c8f6e658.chunk.js:1
  http://127.0.0.1:9999/share.fc81e373fef6c8f6e658.chunk.js:1 in baf7021f8a6fabdc859e
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in a
  http://127.0.0.1:9999/share.fc81e373fef6c8f6e658.chunk.js:1
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in a
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in t
  http://127.0.0.1:9999/runtime~share.abb929c03d2888cbc8ef.js:1 in r

phantom version 2.1.1 on mac

**Comment by waters321** [comment]
phantomjs is not supported ES6
is consider use puppeteer replace?

**Comment by cloth32** [comment]
Have you solved your problem? I have the same problem as you

**Comment by AndyFong** [comment]
temporary fixed in beta 6 version.  
https://github.com/edp963/davinci/releases/tag/v0.3.0-beta.6
