### ISSUE TITLE
import CSV file in Source doesn't work

### ISSUE THREAD

**Issue by gygesM** [edp963/davinci#949]
BUG: **Import CSV file in Sourced doesn't work**

![image](https://user-images.githubusercontent.com/11797588/58528693-25fafb80-820a-11e9-8e4b-79154e54fdfc.png)

**Comment by scottsut** [comment]
https://edp963.github.io/davinci/source_guide.html

**Comment by gygesM** [comment]
> https://edp963.github.io/davinci/source_guide.html

thanx
