### ISSUE TITLE
display load widget and get error

### ISSUE THREAD

**Issue by gygesM** [edp963/davinci#952]
- Davinci 3.0
- When I add  two widgets to Display layer , nothing display and I got these errors in following pic
![image](https://user-images.githubusercontent.com/11797588/58543796-afbebf00-8232-11e9-9257-3c1221ace5ef.png)
- JDBC
- select count(account_no) as 'number', bank_name from accounting_bank_account group by bank_name
- see pic
- null

**Comment by AndyFong** [comment]
fixed by #958
