### ISSUE TITLE
wrong encoding 

### ISSUE THREAD

**Issue by RedA1ert** [edp963/davinci#956]
![image](https://user-images.githubusercontent.com/32149042/58613085-4056d700-82e7-11e9-86a6-7f5e60cad9cf.png)

**Comment by RedA1ert** [comment]
version:0.3 bate5 
encoding: utf-8

**Comment by AndyFong** [comment]
Please check your database encoding config, and after that, create new database table and add some data to verify.

**Comment by RedA1ert** [comment]
database encoding config is right . but when i use Chinese as column alias，return wrong enconding

**Comment by RedA1ert** [comment]
![image](https://user-images.githubusercontent.com/32149042/58617325-6635a900-82f2-11e9-9f31-c1c2a39f7386.png)

**Comment by RedA1ert** [comment]
直接查询的时候，返回值中包含中文也是正确的 。但是使用别名的时候，返回值乱码
