### ISSUE TITLE
share

### ISSUE THREAD

**Issue by RedA1ert** [edp963/davinci#961]
how to share dashboard with parameters?
version:0.3 beta5

**Comment by AndyFong** [comment]
Could you describe what parameters that you want to share with dashboard?

**Comment by RedA1ert** [comment]
When integrating with a third party, the value of the variable defined in the view is passed by a third party.

**Comment by AndyFong** [comment]
At present, we have not supported this feature yet.  

We know that it is a scenario indeed when initializing `Dashboard` data query by its query parameter values come from outer caller.   

However, there still remains some problems. How outer caller perceives the parameter types and values change? The preferred way that pass the outer parameters to a specific `Dashboard`?  How to integrate these outer parameters with the present feature global filter control in a `Dashboard`? A friendly way that config different parameters to different roles and users or just to different types of anonymous users?  

When we make sure how to design to handle these problems well, we will start to develop this feature. And also welcome to leave your ideas with these feature designs.

**Comment by RedA1ert** [comment]
Thank you for your answer, I look forward to your launch of the new version.
