### ISSUE TITLE
The table of pagination in 'Display' doesn't work

### ISSUE THREAD

**Issue by GZ315200** [edp963/davinci#964]
-  Davinci 3.0

- the function, Please  check Pic
![image](https://user-images.githubusercontent.com/11797588/58677898-5076c100-8390-11e9-93f9-c6629e195f27.png)

- console error log , Please Check pic
![image](https://user-images.githubusercontent.com/11797588/58677778-e2ca9500-838f-11e9-93d9-4c2f3c7f6310.png)

**Comment by AndyFong** [comment]
#969
