### ISSUE TITLE
the dropbox doesn't work and  the items  can not be picked up 

### ISSUE THREAD

**Issue by GZ315200** [edp963/davinci#980]
- version: Davinci 3.0

- issue: 
![image](https://user-images.githubusercontent.com/11797588/58924785-ca83bd00-8777-11e9-8a76-80dba733f0a2.png)

- what's going on?
When I use dropbox component  of the global control configuration . found it doesn't work, I can't pick up the item and the data was refreshed fast.

**Comment by AndyFong** [comment]
Please post this global filter control setting screenshot.

**Comment by gygesM** [comment]
@AndyFong  I have fixed it now. Do you guys wanna this commit?

**Comment by AndyFong** [comment]
If you confirm that this is a bug, you can create a PR, and also explain when the bug happens.

**Comment by gygesM** [comment]
@AndyFong  It's an exactly bug. Terrible experience.  the DOM of selector was refreshed consistently. I tried to pick up the element of it but I failed.

**Comment by AndyFong** [comment]
Already fixed by official.
